### ISSUE TITLE
Re-enable incremental compilation

### ISSUE THREAD

**Issue by niklaslong** [AleoHQ/snarkOS#1010]
Rust `1.54.0` [re-enables incremental compilation by default](https://blog.rust-lang.org/2021/07/29/Rust-1.54.0.html#incremental-compilation-is-re-enabled-by-default) following issues reported in the `1.52.0` and it being disabled in `1.52.1`. We may want to wait until the next release before re-enabling it ourselves, to be extra safe.

**Comment by ljedrz** [comment]
Closed by https://github.com/AleoHQ/snarkOS/pull/1168.
