### ISSUE TITLE
[Feature] Add metric tests

### ISSUE THREAD

**Issue by ljedrz** [AleoHQ/snarkOS#1029]
## 🚀 Feature

We're currently utilizing many different metrics, and it's easy for a bug to slip through the cracks and break their value, even in some seemingly unrelated code. We should be testing the metrics using a test `Node` and some external source of messages; when the `Node` receives message of a specific type, the related metric should be altered accordingly, and the same goes for adding/removing connections etc.

**Comment by ljedrz** [comment]
Partial implementation done in https://github.com/AleoHQ/snarkOS/pull/1190.

**Comment by ljedrz** [comment]
Closing, as it's no longer applicable to testnet2. @niklaslong something to consider when you're adding new metrics.

**Comment by niklaslong** [comment]
Yes, it's in the pipeline 👍
