### ISSUE TITLE
[Feature] Store peer lists to storage

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#1032]
Right now, whenever we boot a node, it has to connect to our bootnodes to find any peers, no matter what.

This is a centralization issue, but also a SPOF for booting nodes as our bootnodes have scaling/capacity problems intermittently.

Having a local store of good nodes would be an easy and effective mitigation. Longer term solutions may include public peer registries.

**Comment by ljedrz** [comment]
Closed by https://github.com/AleoHQ/snarkOS/pull/1160.
