### ISSUE TITLE
[Docs] Re-enable external docs for rpc traits

### ISSUE THREAD

**Issue by niklaslong** [AleoHQ/snarkOS#1044]
#1007 re-enables the external md documentation using `#[doc = include_str!()]` which unfortunately doesn't seem to play nice with the rpc traits (as of rust `1.54`). We may need to wait for a future release of rust to include this documentation.

**Comment by ljedrz** [comment]
Closed by https://github.com/AleoHQ/snarkOS/pull/1209.
