### ISSUE TITLE
[Bug] Syncing seems to freeze up until node is restarted every 50-100k blocks.

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#1066]
It seems that when syncing, every 50-100k blocks, we have a chance to get stuck in a node until the node is restarted.

Unconfirmed, but it seems to me the issue is peer isolation resulting in only being connected to peers on forks since they don't send us sync blocks. It seems plausible that failures accumulate and that the 15 minute expiry timer for failures is overzealous or a bad approach in a congested network (perhaps we should just deprioritize low quality nodes rather than disconnect?)

**Comment by ljedrz** [comment]
Cc https://github.com/AleoHQ/snarkOS/issues/1037

**Comment by ljedrz** [comment]
sounds plausible :+1:

**Comment by ljedrz** [comment]
I haven't encountered this in a while now; marking the issue as `likely fixed`.

**Comment by ljedrz** [comment]
I haven't encountered this issue in a good while now, so it appears to have been fixed.
