### ISSUE TITLE
[Feature] Aggressive Sync

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#1081]
Right now nodes have two competing priorities:
* Make sure they don't waste bandwidth/send useless blocks to sync up others
* Get sync blocks from as many peers as possible, as fast as possible.

The middleground of these two priorities is the current sync negotiation. This issue proposes a more aggressive form of this sync negotiation, possible with no protocol changes, but would benefit the syncing node somewhat disproportionally.

Syncing node:
* Node A sends block locator hashes to Peer B. (and others in parallel, omitted for brevity onward)
* Peer B sends it's 64 sync block proposed hashes to Node A.
* Node A simultaneously requests the 64 blocks from Peer B, and immediately reforwards the sync hashes as block locator hashes to Peer B.
* Peer B sends the first batch of 64 blocks, and the next 64 sync hashes simultaneously.

We can continue our parallel node approach to load balance block transfers. This change should improve sync time significantly by eliminating a lot of network overhead, and basically being continuous.

**Comment by ljedrz** [comment]
An implementation was filed in https://github.com/AleoHQ/snarkOS/pull/1120.
