### ISSUE TITLE
[Bug] Corrupt/illegal blocks on longest chain cause node halting

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#1089]
If we have a block in the longest chain that is invalid for the node's consensus (i.e. 2 coinbase transactions) -- it will cause the node to halt syncing and freeze.

**Comment by ljedrz** [comment]
Cc https://github.com/AleoHQ/snarkOS/issues/1106.

**Comment by ljedrz** [comment]
Is this issue now closed with https://github.com/AleoHQ/snarkOS/pull/1231, @Protryon?

> Fixes consensus not removing invalid blocks causing sync stalls.

**Comment by ljedrz** [comment]
Closing, as it's no longer applicable to testnet2.
