### ISSUE TITLE
[Bug] snarkOS 1.3.15 crash

### ISSUE THREAD

**Issue by depool-live** [AleoHQ/snarkOS#1163]
## 🐛 Bug Report

(Write your description here)

snarkOS 1.3.15 crash after 1 day work

## Steps to Reproduce

1. Step 1...
2. Step 2...
3. Step 3...

sync from zero

(code=exited, status=134)
SIGABRT

## Expected Behavior

(Write what you expected to happen here)

## Your Environment

-  1.3.15
-  1.54.0
-  Ubuntu 20.04.2 LTS

**Comment by niklaslong** [comment]
Thank you for reporting this issue. Did you perchance save the logs when this happened? I'm assuming you were running a miner (`--is-miner`) with the default configuration?

**Comment by depool-live** [comment]
node mode (without --is-miner)

Welcome to Aleo! We thank you for running a network node and supporting privacy.

Starting a client node on testnet1.

Sep 17 07:04:01.446  INFO snarkos: Loading storage at '~/.snarkOS/snarkos_testnet1'...
Sep 17 07:04:01.447 TRACE snarkos_storage::storage::async_adapter: received storage request: Canon()    
Sep 17 07:04:01.447  INFO snarkos: Storage is ready
Sep 17 07:04:01.447 DEBUG snarkos: Loading Aleo parameters...
Sep 17 07:04:01.571  INFO snarkos: Loaded Aleo parameters
Sep 17 07:04:01.609  INFO snarkos: Loading Ledger
Sep 17 07:04:01.609 TRACE snarkos_storage::storage::async_adapter: received storage request: GetLedgerDigests()    
Sep 17 07:04:01.938 TRACE snarkos_storage::storage::async_adapter: received storage request: GetCommitments()    
Sep 17 07:04:02.488 TRACE snarkos_storage::storage::async_adapter: received storage request: GetSerialNumbers()    
Sep 17 07:04:03.042 TRACE snarkos_storage::storage::async_adapter: received storage request: GetMemos()    
Sep 17 07:04:03.546  INFO snarkos: Initializing Ledger
Sep 17 07:04:13.072  INFO snarkos: Loaded Ledger
Sep 17 07:04:13.073 TRACE snarkos_storage::storage::async_adapter: received storage request: Canon()    
Sep 17 07:04:13.073 TRACE snarkos_storage::storage::async_adapter: received storage request: Canon()    
Sep 17 07:04:13.073 TRACE snarkos_storage::storage::async_adapter: received storage request: GetBlockDigestTree(7470f24eea85e296b1cac1f94da99c3ec2fff6dd059302c462affb95074c7fa4)    
Sep 17 07:04:13.083 DEBUG snarkos_network::node: Initializing metrics
Sep 17 07:04:23.556 TRACE snarkos_storage::storage::async_adapter: received storage request: Canon()    
Sep 17 07:04:23.556 DEBUG snarkos_consensus::consensus::inner::commit: Attempting to canonize the descendants of block at height 137634.
Sep 17 07:04:23.556  INFO snarkos_network::inbound::inbound: Initializing listener for node (ce32b8eeff0079f6)
Sep 17 07:04:23.556  INFO snarkos_network::inbound::inbound: Listening for nodes at 0.0.0.0:4131
Sep 17 07:04:23.556  INFO snarkos_network::node: Updating peers
Sep 17 07:04:23.556  INFO snarkos_network::peers::peers: Connected to 0 peers

**Comment by Protryon** [comment]
This was fixed by #1159, release planned for today.
