### ISSUE TITLE
[Bug] The storage queue metric can underflow

### ISSUE THREAD

**Issue by ljedrz** [AleoHQ/snarkOS#1183]
## 🐛 Bug Report

I encountered `"queues.storage": 18446744073709552000` when calling `getnodestats`; this suggests some underflow in the calculation of the associated metric.

**Comment by ljedrz** [comment]
note: I haven't encountered this ever since, so it's either fixed or a very rare glitch.

**Comment by niklaslong** [comment]
Haven't seen this either, including on long running nodes—optimistically closing for now.
