### ISSUE TITLE
[Bug] Slow RPC response times

### ISSUE THREAD

**Issue by evgeny-garanin** [AleoHQ/snarkOS#1184]
## 🐛 Bug Report

Since latest updates (1.3.16, maybe 1.3.15 too), RPC calls to node sometime take way longer to get response from.
Specifically method "getblockcount".

## Steps to Reproduce

1. Get your node running
2. Run following calls (in .sh script preferably)
curl -s --data-binary '{"jsonrpc": "2.0", "id":"documentation", "method": "getpeerinfo", "params": [] }' -H 'content-type: application/json' http://$1:3030/   | jq '.[].peers?';
echo "NODE INFO:";
curl -s --data-binary '{"jsonrpc": "2.0", "id":"documentation", "method": "getnodeinfo", "params": [] }' -H 'content-type: application/json' http://$1:3030/ | jq '.result?';
printf "CONNECTION COUNT:\t";
curl -s --data-binary '{"jsonrpc": "2.0", "id":"documentation", "method": "getconnectioncount", "params": [] }' -H 'content-type: application/json' http://$1:3030/ | jq '.result?';
printf "BLOCK COUNT:\t\t";
curl -s --data-binary '{"jsonrpc": "2.0", "id":"documentation", "method": "getblockcount", "params": [] }' -H 'content-type: application/json' http://$1:3030/ | jq '.result?';
echo "BLOCKS MINED:";
curl -s --data-binary '{"jsonrpc": "2.0", "id":"documentation", "method": "getnodestats", "params": [] }' -H 'content-type: application/json' http://$1:3030/ | jq '.[].misc?.blocks_mined?';
echo "OVERALL:";
curl -s --data-binary '{"jsonrpc": "2.0", "id":"1", "method": "getnodestats" }' -H 'content-type:application/json' http://$1:3030/ | jq '.result?';
3. Sometimes its instant, sometimes it takes 30+ seconds to respond

## Expected Behavior

Expected to be instant

## Your Environment

-  1.3.16
-  1.24.3, 1.55.0
-  Ubuntu 20.04

**Comment by zosorock** [comment]
I can confirm this :+1:

**Comment by ljedrz** [comment]
It can happen when the node is currently aggressively syncing blocks - this can cause many storage-related requests to get queued, meaning the RPC is waiting its turn.

This behavior is currently expected, and we don't want to prioritize RPCs over network operations, but this can certainly be improved.

Cc https://github.com/AleoHQ/snarkOS/issues/1176, which is a related issue

**Comment by damons** [comment]
What is strange to me is that all the other RPC calls return almost immediately.  Why is only getblockcount slow?

**Comment by ljedrz** [comment]
It involves a call to storage, which can get queued; doesn't the same slowdown happen with e.g. `getbestblockhash` or `getblockhash` (it should)?

**Comment by ljedrz** [comment]
I confirmed that this applies to other storage-related requests as well.
