### ISSUE TITLE
[Bug] Unexpected drop of blocks height from  430 000 to 386 000 on Ubuntu 20.04 /Snarkos 1.3.16

### ISSUE THREAD

**Issue by WishMaster2010** [AleoHQ/snarkOS#1189]
## 🐛 Bug Report

A bug has been found. It related to an unexpected decrease in the height of blocks after starting the miner.
I Started miner after the 430 000 height yesterday(28.09.2021). Today I looked at my Grafana and saw that the height of blocks is 386000. 

## Steps to Reproduce

 1) downloaded a snapshot with a block height of 429,000.
2) launched the node, waited until the node catches up with the network
3) disabled the node and launched the miner
4) in about 20 hours after launching the miner, I saw that block height dropped to 387,000

## Your Environment

-  1/3/16
-  Last one
-  Ubuntu 20.04.3
- IP 45.32.157.41

**Comment by ljedrz** [comment]
The most probable explanation is that the node just realized that it's not on the best chain and decided to roll back and sync to a better fork. There is currently no fork length limit, but it might be reintroduced in the future (which would avoid block height drops of this magnitude).

**Comment by damons** [comment]
Did the node eventually sync up after de-committing all those fork blocks?

**Comment by ljedrz** [comment]
It did for me in a similar scenario.

**Comment by ljedrz** [comment]
Marking the issue as `likely fixed`, as this is currently expected behavior, and the node is quite quick to return to the tip after it swaps forks.
