### ISSUE TITLE
[Bug] Node fills all the available memory (30Gb+)

### ISSUE THREAD

**Issue by kovart** [AleoHQ/snarkOS#1193]
## 🐛 Bug Report

Aleo node consumes 30gb+ RAM memory. Is it ok? 
Looks like there is a memory leak because memory usage is increasing gradually and fills up all the available space (32Gb).
`journalctl -u aleod -f` shows good logs (like it's syncing) but [aleo_monitor.sh](https://api.nodes.guru/aleo_monitor.sh) stuck at block count section. 

![image](https://user-images.githubusercontent.com/3381640/135841540-2ae70ce6-b47f-45ae-995a-8c16ab0def38.png)

## Steps to Reproduce

1. Run clear node `systemctl start aleod`
2. Start syncing
2. Wait until the RAM is full

## Expected Behavior

The node service shouldn't use much memory.

## Your Environment

Snakros v.1.3.16
Ubuntu 20.04
rustc 1.55.0 (c8dfcfe04 2021-09-06)

**Comment by ljedrz** [comment]
Thanks for the report! This issue is already tracked under https://github.com/AleoHQ/snarkOS/issues/1176.
