### ISSUE TITLE
[Bug] max-peers can be set below min-peers

### ISSUE THREAD

**Issue by yogggoy** [AleoHQ/snarkOS#1195]
## 🐛 Bug Report

snarkOS flasg max-peers and min-peers can be set as parameter. But user may enter wrong values, MAX may be less than MIN.  
This may have effect :  
https://github.com/AleoHQ/snarkOS/blob/b405b57715cf62ddd209466bc859caaaee41f960/network/src/peers/peers.rs#L88

## Steps to Reproduce

`snarkos --max-peers 10 --min-peers 50`

or more real case:

```
snarkos --min-peers 100
# default max-peers is 50
```

## Expected Behavior

Maybe snarkos should be set default values and inform user?

**Comment by ljedrz** [comment]
I'm sure this used to be checked, but perhaps this logic got borked in the meantime; I'm going to check this :+1:.

**Comment by ljedrz** [comment]
Fixed by https://github.com/AleoHQ/snarkOS/pull/1196.
