### ISSUE TITLE
[Bug] On every restart snarkos overwrites the .snarkOS/config.toml file with its default values.

### ISSUE THREAD

**Issue by aditya-manit** [AleoHQ/snarkOS#1250]
## 🐛 Bug Report

On every restart snarkos overwrites the `.snarkOS/config.toml` file with its default values.
One has to alway use the cli flags to set stuff that can be set in config.

## Steps to Reproduce

1. Start snarkos with miner configurations: `snarkos --is-miner --miner-address <miner-address>`
2. Stop snarkos after its initiate the node and create the config file
3. Set `is_miner` and `miner_address` address in `.snarkOS/config.toml` or just change any other config value
```
[miner]
is_miner = true
miner_address = "aleo1ym99a52hjqq95lwd....."
```
4. Starts snarkos again but without flags this time:  `snarkos`

## Expected Behavior

 **What was supposed to happen in snarkOS?**
 
 The snarkos was supposed to pick flags from `config.toml` file and start as a miner.
 
 **What happened instead?**
 
It overwrites the `config.toml` file and recreates it and starts as a full node.
Check the file now `cat .snarkOS/config.toml ` they will be reverted to `false` and empty string `""`
```
[miner]
is_miner = false
miner_address = ""
```

## Your Environment

-  snarkOS 1.3.14
-  rustc 1.56.0
-  ubuntu 20.04 LTS
----
[Originally reported on discord here](https://discord.com/channels/700454073459015690/700477705422110761/904428900870930442)

**Comment by niklaslong** [comment]
Thank you for reporting this, should be fixed once #1252 is in.

**Comment by aditya-manit** [comment]
Great Thanks !

**Comment by ljedrz** [comment]
Closing, as it's no longer applicable to testnet2.
