### ISSUE TITLE
[Bug] Possible memory leak with `--is-miner` option❓

### ISSUE THREAD

**Issue by yatsvic** [AleoHQ/snarkOS#1256]
## 🐛 Bug Report

Probably memory leak.

I just run miner and it consume whole RAM and swap.

## Steps to Reproduce

1. Run node to catchup the blockchain:
  ```
snarkos \
	--min-peers 10 \
	--max-peers 20 \
	--verbose 1
  ```
2. Run miner:
  ```
snarkos \
	--min-peers 10 \
	--max-peers 20 \
	--no-recanonize \
	--is-miner \
	--miner-address aleo... \
	--verbose 1
  ```
3. SnarkOS will consume whole 64G RAM in ~30 min

p.s. I tried to restrict threads count via `taskset --cpu-list 1,3,5,7,9,11,13,15 snarkos ...`, but it just took a bit more time to consume all memory.

## Expected Behavior

SnarkOS mines blocks and consume limited amount of memory.

## Your Environment

- SnarkOS 1.3.17 (installed via cargo)
- Ubuntu 18.04 with core 5.11.16
- Ryzen 5950X, 64G RAM

**Comment by yatsvic** [comment]
I use memory limits in systemd and it kills and start miner every 30 minutes
```
[Unit]
Description=Aleo Miner
After=network-online.target

[Service]
User=aleo
ExecStart=/home/aleo/run-miner.sh
Restart=always
RestartSec=10
LimitNOFILE=10000
MemoryAccounting=true
MemoryHigh=24G
MemoryMax=32G

[Install]
WantedBy=multi-user.target
```

**Comment by ljedrz** [comment]
Thanks for the report, @yatsvic! I'm going to try to reproduce this.

**Comment by ljedrz** [comment]
There's definitely a leak related to mining alright; I'm able to reproduce it reliably, going to try to fix it :factory_worker:.

**Comment by yatsvic** [comment]
@ljedrz I am not experienced in Rust, so I can suggest only to test fix when it is ready.

**Comment by ljedrz** [comment]
After having memory-profiled a miner node using different tools, I actually don't think there is a leak, but rather an issue with the allocator, where the node doesn't release memory "proactively" enough.

@yatsvic while I'm still working on a general solution, could you try out [my temporary branch](https://github.com/ljedrz/snarkOS/tree/jemalloc), which uses the `jemalloc` allocator, and run it with `JEMALLOC_SYS_WITH_MALLOC_CONF="background_thread:true,narenas:1,tcache:false,dirty_decay_ms:0,muzzy_decay_ms:0,abort_conf:true" <snarkos binary and its arguments>`? With this aggressive allocator setup I was able to mine over 100 blocks without running out of memory.

**Comment by ljedrz** [comment]
I have further confirmed that this is caused by the system allocator by using `gdb` and calling `malloc_trim` :heavy_check_mark:.

**Comment by yatsvic** [comment]
@ljedrz thanks! I am trying your branch with `JEMALLOC_SYS_WITH_MALLOC_CONF`. 
It mined 27 blocks in 24 minutes and it is in 4 - 12 GB RAM, more time is about 5GB.
Looks like it is not leaking!
I will report long run results in 8-9 hours (my morning, it is night at my location).

**Comment by yatsvic** [comment]
@ljedrz it is definitely running fine! 
I started it 9.5 hours ago, it works without crashes and restarts. And currently it consumes 10.5Gb RAM.
upd: mined 463 blocks

**Comment by yatsvic** [comment]
It has been running for two days without restarts!

**Comment by yatsvic** [comment]
@ljedrz did you have a chance to fix it? Thanks

**Comment by ljedrz** [comment]
@yatsvic since the beginning of testnet2, the node has undergone a full rewrite, so this issue is unlikely to be applicable anymore; however, until it is certain that the new implementation is staying for good, the issues applicable to testnet1 remain open.
