### ISSUE TITLE
[Feature] Initial node wallet with coinbase records for miners

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#1258]
## 🚀 Feature

@julesdesmit after thinking through this design further, I actually would suggest the following design:

1. Keep a single pool of records (irrespective of their existence on canon).
2. When fetching records for a specific account, call `ledger.contains_commitment(record.commitment())` on every single record that belongs to the address (i.e. `record.owner() == miner_address`).
3. Return all records that exist in the current canon chain (i.e. anything that returned `true`)

This approach has the advantage that we can support long fork rebases (in case we need to), and the call to `contains_commitment` is a constant/1-step operation in our new DB design. Given we check this for every block, I can say that should be fairly performant (i.e. tens of milliseconds if I had to guess).

**Comment by howardwu** [comment]
@julesdesmit what's the status on this impl?

**Comment by jules** [comment]
@howardwu currently migrating my work from the old repo - there’s quite a few merge conflicts I need to resolve for both PRs so I assume I’ll have them ready in a day or so
