### ISSUE TITLE
[Bug] The read-only database is not catching up to the primary database correctly.

### ISSUE THREAD

**Issue by raychu86** [AleoHQ/snarkOS#1290]
## 🐛 Bug Report

The snarkOS node runs a primary RocksDB database for standard node operations and a read-only `secondary` database for the RPC server. This `secondary` database is uses a `try_catch_up_with_primary` to update it's state. Despite this, the `secondary` seems to occasionally fall behind the primary database and not update properly. 

Initially, we called `try_catch_up_with_primary` every time an RPC endpoint was hit, however we noticed that a high frequency of these `try_catch_up_with_primary` calls jumps the `secondary` database state back and forth between new and old state. This can be seen in the `secondary` database latest sequence number, which was also updating, then reverting back to the original.

To get around the original issue, we have a loop that calls `try_catch_up_with_primary` every X seconds, and only updates the read-only state if the sequence number increases properly. However, this approach still has issues keeping state live/udpated for the `secondary` database.

This is the current iteration of our design - https://github.com/AleoHQ/snarkOS/blob/f9f3210ab8e3b1b7626d133317a1dbfbb5c7715e/ledger/src/state/ledger.rs#L171-L210

## Steps to Reproduce

1. Run a node
2. Query the RPC for block state
3. Look for mismatches in block height or latest block state.

## Expected Behavior

The `secondary` database should catch up to the primary state properly every time the `try_catch_up_with_primary` function is called.

## Your Environment

`testnet2` branch
Latest commit - `8bf81be47aa6be2145abd7a188507848d1dcb4c3`

**Comment by howardwu** [comment]
Closing as we've switched to primary. Pending `rust-rocksdb` new release, we can switch back to secondary.
