### ISSUE TITLE
[Bug] snarkos account creation gets stuck on fresh build

### ISSUE THREAD

**Issue by evgeny-garanin** [AleoHQ/snarkOS#1314]
## 🐛 Bug Report

On fresh build of snarkos 2.0.0 (23-Nov) bash does not terminate the snarkos process after calling new_account method

## Steps to Reproduce

1. Build fresh snarkos 2.0.0 following official instruction
2. snarkos experimental new_account
3. output of new account is printed, but you have to Ctrl+C now (opposed to last week's build)

## Expected Behavior

Process should stop and give you bash control

## Your Environment

- 
- 2.0.0
- 
- latest
- 
- Ubuntu 20.04

**Comment by howardwu** [comment]
Closing as I believe this issue has been fixed with the latest changes.
