### ISSUE TITLE
[Feature] [nice-to-have] Change rust logging to stdout versus default stderr

### ISSUE THREAD

**Issue by brianventuro** [AleoHQ/snarkOS#1341]
## 🐛 Bug Report

When running snarkOS interactively, or even in a docker container on a bare metal host, the current rust logging mechanism is fine (it prints to `stderr`). However, if this is deployed in an orchestration environment where logging is expected to be on `stdout` (i.e. Kubernetes), you no longer get access to logs (`kubectl logs -f` streams `stdout` only), leading to someone potentially spending 48 hours trying to figure out why their node is stuck at boot, before checking the docker logs on the bare metal host.

## Steps to Reproduce

1. Deploy a node via Kubernetes.
2. Cry while you attempt to find logs via `kubectl logs -f <container name>`.
3. Realize rust logging prints to `stderr` by default.
4. Check logs on bare metal host using `docker logs -f <container name>`.

## Expected Behavior

Expect logs to be accessible via the industry standard container orchestration platform.

**Comment by ljedrz** [comment]
Can you please check if this is still the case with the current version of the node? A [recent change](https://github.com/AleoHQ/snarkOS/pull/1339) should have redirected the logs to `stdout` by default (even when not running with `--display`).

**Comment by ljedrz** [comment]
Closing this issue, as `stdout` is default now. Please feel free to reopen if anything is left to do.
