### ISSUE TITLE
[Bug] error[E0658]: arbitrary expressions in key-value attributes are unstable

### ISSUE THREAD

**Issue by myzhang** [AleoHQ/snarkOS#1343]
## 🐛 Bug Report

Error when running either of:
cargo run --release -- experimental new_account
./run-miner.sh

error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> src/rpc/rpc_trait.rs:84:13
   |
84 |     #[doc = include_str!("./documentation/public_endpoints/sendtransaction.md")]
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

## Steps to Reproduce

1. Step 1. Take new machine
2. Step 2. Follow build instructions
3. Step 3. Run ./run_miner.sh or cargo run --release -- experimental new_account

## Expected Behavior

Miner should start without error
## Your Environment

- 
- 1.56
- ubunutu 20

**Comment by grsahil20** [comment]
Similar to what I posted already here https://github.com/AleoHQ/snarkOS/issues/1342

**Comment by myzhang** [comment]
@grsahil20 indeed I also saw the warning you reported. But when i saw your issue, it at least could continue. For the error above it comes to a hard stop

**Comment by myzhang** [comment]
@grsahil20 You're right, I read your item but not the comment you later added

**Comment by BruceLoveDecimal** [comment]
I met this problem too, and it cant be fixed even my rustc version is 1.57
