### ISSUE TITLE
[Bug] Low CPU utilization when running miner node

### ISSUE THREAD

**Issue by xbeastx** [AleoHQ/snarkOS#1346]
## 🐛 Bug Report

Most time miner node is just in 'Syncing' or 'Peering' state. And some times it become 'Mining' but not so long. Just for a couple seconds.

## Steps to Reproduce

Just compile latest testnet2 source
1. run-miner.sh

## Expected Behavior

Because Aleo is POSW most of the time it must mine new blocks and utilize 100% CPU

## Your Environment

- snarkOS Version
2.0.0
- Rust Version
1.56.1
- Computer OS
Ubuntu 20.04

**Comment by CodeGp2018** [comment]
I also encountered this difficulty. waiting for solve.

**Comment by howardwu** [comment]
How many cores is your machine? 16-cores is the minimum requirement for testnet2.

**Comment by xbeastx** [comment]
> How many cores is your machine? 16-cores is the minimum requirement for testnet2.

Sure, I have server with 24 core/48 threads and it almost inactive... like 8 threads of 48 sometime is busy and even not always:

<img width="1434" alt="htop" src="https://user-images.githubusercontent.com/3618442/143873824-d15bb6b2-8013-4ea9-ba6a-4abf3eb33956.png">

**Comment by PNZ20** [comment]
Same problem here;
the miner use only 1 CPU...

![htop](https://user-images.githubusercontent.com/42167577/144091430-b9223c68-156a-4759-b064-26361a69f5c9.jpg)

**Comment by 0xPNZ** [comment]
Same problem here;
the miner uses only 1 CPU...

![htop2](https://user-images.githubusercontent.com/42167577/144096018-1c7fe3db-4d5a-4fb1-88cc-0e8975da4c60.jpg)

**Comment by alar0n** [comment]
I see this picture. Only One or two core is loaded about 50% of the time. Other 50% of the time is loaded all cores. The situation alternates every 5-10 seconds
![image](https://user-images.githubusercontent.com/31000576/144207031-c6703946-9d75-40c1-9747-92f1c9662ef5.png)
![image](https://user-images.githubusercontent.com/31000576/144207382-aa536c80-33e0-451c-b020-6b14cdc052fe.png)

**Comment by ljedrz** [comment]
This should have improved with the recent changes, but there is probably still room for improvement here.

**Comment by ljedrz** [comment]
Not applicable to testnet3.
