### ISSUE TITLE
Failed to connect to '161.35.106.91:4132': '0s {code: 61, kind: connectionRefused,...

### ISSUE THREAD

**Issue by xgc820313** [AleoHQ/snarkOS#1350]
## 🐛 Bug Report

(Write your description here)

## Steps to Reproduce

1. Step 1...
2. Step 2...
3. Step 3...

## Expected Behavior

(Write what you expected to happen here)

## Your Environment

- 
- 
-

**Comment by ljedrz** [comment]
It is expected that the node will sometimes fail to connect to one of the sync nodes (or a regular peer), e.g. if the target is at its connection limit, and as long as it doesn't happen all the time, it doesn't indicate any underlying issue.

Please reopen and describe the situation in more detail if this happens constantly.
