### ISSUE TITLE
[Bug] Miner stats cannot be retrieved while miner is running.

### ISSUE THREAD

**Issue by CumpsD** [AleoHQ/snarkOS#1354]
## 🐛 Bug Report

When the miner is not running:

```
~/aleo/snarkOS$ cargo run --release -- miner stats aleoxxxxx
    Blocking waiting for file lock on build directory
    Finished release [optimized] target(s) in 29.66s
     Running `target/release/snarkos miner stats aleoxxxxx`
2021-11-30T13:31:16.013948Z TRACE [Read-Only] Ledger successfully loaded at block 136
2021-11-30T13:31:16.032716Z  INFO Prover successfully initialized
Mining Report (confirmed_blocks = 0, pending_blocks = 0, miner_address = aleoxxxxx)
```

When the miner is running:
```
~/aleo/snarkOS$ cargo run --release -- miner stats aleoxxx
    Finished release [optimized] target(s) in 0.09s
     Running `target/release/snarkos miner stats aleoxxx`
2021-11-30T13:31:42.754784Z TRACE [Read-Only] Ledger successfully loaded at block 152
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IO error: While lock file: /home/ubuntu/.aleo/storage/prover-2/LOCK: Resource temporarily unavailable', src/node.rs:419:111
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Your Environment

- SnarkOS https://github.com/AleoHQ/snarkOS/commit/c8b6de53325721e7c584cd8360ec72d37215bc5c
- rustc 1.56.1 (59eed8a2a 2021-11-01)

**Comment by howardwu** [comment]
@raychu86 We may want to introduce a secondary reader on `ProverState` to access this while the node is running

**Comment by ethisscam** [comment]
By the way, readme.md said you can also use snarkos miner stats aleo1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx . But when I try this command it showed `error: Found argument 'miner' which wasn't expected, or isn't valid in this context
`

**Comment by xbeastx** [comment]
May be better just return number of mined blocks with `getnodestate` RPC-method or introduce another RCP-method?

**Comment by CumpsD** [comment]
> May be better just return number of mined blocks with `getnodestate` RPC-method or introduce another RCP-method?

That would be nicer yes! :)

**Comment by skvoo** [comment]
> > May be better just return number of mined blocks with `getnodestate` RPC-method or introduce another RCP-method?
> 
> That would be nicer yes! :)

Yes, sir

**Comment by rashidovich** [comment]
btw, same issue when calling from docker instance (like so `docker exec --interactive snarkos_latest /aleo/bin/snarkos miner stats aleo1x`)

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IO error: While lock file: /root/.aleo/storage/prover-2/LOCK: Resource temporarily unavailable', src/node.rs:419:111
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by you-yyds9527** [comment]
![image](https://user-images.githubusercontent.com/96114822/145979359-e8c668e6-1b83-413a-9d29-564b5ff3e442.png)
I also encountered the same problem

**Comment by CrazyAz10** [comment]
I also encountered the same problem
