### ISSUE TITLE
[Bug]thread 'main' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by shiziwen** [AleoHQ/snarkOS#1360]
## 🐛 Bug Report

Hi, when I run the node as a miner by run-miner.sh, I got this message:

2021-12-01T03:37:37.318354Z DEBUG Validating the ledger up to block 501 (100%)
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `AleoLocator { hrp: "al", data: Fp256(4619787663255699868380503070830983446310800127672507699873419694325959801458) }`,
 right: `AleoLocator { hrp: "al", data: Fp256(2653325756165159360435354610554457667538798484789708984161589585860663028319) }`', /data/snarkOS/storage/src/state/ledger.rs:212:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by shiziwen** [comment]
I have tried to restart the node, but the panic happened again.

I you need more information, connection me.

**Comment by rayn316** [comment]
```
2021-12-01T06:54:41.562590Z DEBUG Validating the ledger up to block 501 (100%)
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `AleoLocator { hrp: "al", data: Fp256(2180413841631221483869035365579606912076225239550174444205460207040035170284) }`,
 right: `AleoLocator { hrp: "al", data: Fp256(6625747389475706972641387426803392449301567419990991643240503084430759780944) }`', /root/snarkOS/storage/src/state/ledger.rs:212:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: snarkos_storage::state::ledger::LedgerState<N>::open_writer
   5: snarkos::network::server::Server<N,E>::initialize::{{closure}}
   6: snarkos::node::Node::start::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: tokio::park::thread::CachedParkThread::block_on
   9: tokio::runtime::thread_pool::ThreadPool::block_on
  10: tokio::runtime::Runtime::block_on
  11: snarkos::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by howardwu** [comment]
If you run into this, I suggest cleaning the database, and starting the node again.

In the snarkOS directory, run:
```
cargo run --release -- clean
```

**Comment by aditya-manit** [comment]
hey @howardwu any idea what causes this  ? and how can we avoid this ? I see a lot of people reporting this in discord ?

**Comment by iamnader** [comment]
just happened to me fyi
