### ISSUE TITLE
[Bug] run-client.sh fails to run on windows

### ISSUE THREAD

**Issue by Evan-Kim2028** [AleoHQ/snarkOS#1361]
## 🐛 Bug Report

(Write your description here)

## Steps to Reproduce

1. rune `run-client.sh` in cmd

## Your Environment

- 
- 
-

**Comment by kiennd** [comment]
I ran on windows and i got this error message:
standard_init_linux.go:228: exec user process caused: no such file or directory

**Comment by ljedrz** [comment]
This is because Windows doesn't handle `.sh` files by default; I currently don't have access to a Windows PC, but I think you need to compile the node manually. A windows `cmd` script might be added in the future.

This should probably be addressed in the `README`.

**Comment by ljedrz** [comment]
Removing the `bug` label, as bash scripts not working under Windows is not a bug.

**Comment by ljedrz** [comment]
Closing in favor of https://github.com/AleoHQ/snarkOS/issues/1620.
