### ISSUE TITLE
[Bug] Numeric `id` not supported anymore in JSON RPC call

### ISSUE THREAD

**Issue by nmeilick** [AleoHQ/snarkOS#1369]
## 🐛 Bug Report

JSON RPC does not accept a numeric `id` anymore and responds with `Couldn't parse the RPC body`. When `id` is given as a String or Null, the API call works. This behavior is new and was apparently introduced in a change within the past 12 hours.

## Steps to Reproduce

1. `curl -s -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"latestblockheight","params":[],"id":1}' localhost:3032`
Output: `{"jsonrpc":"2.0","error":{"code":-32700,"message":"Couldn't parse the RPC body"},"id":null}`

2. `curl -s -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"latestblockheight","params":[],"id":"1"}' localhost:3032`
Output: `{"jsonrpc":"2.0","result":6864,"id":"1"}`

## Expected Behavior

Support `id` as String, Number and Null, as in the JSON RPC specs

## Your Environment

snarkOS: 2.0.0 (c762a1d453b98e2e34208b16a3405e6a9e63c33d)
Rust: 1.56.1
OS: Ubuntu Linux 20.04

**Comment by ljedrz** [comment]
Correct, the JSON-RPC 2.0 spec allows the `id` to be numeric.
