### ISSUE TITLE
Node crashed and can't restart with message thread 'main' panicked at 'assertion failed: `(left == right)`

### ISSUE THREAD

**Issue by wufangfang1984** [AleoHQ/snarkOS#1375]
## 🐛 Bug Report

I'm run a miner for 3 days, today I found that it crashed with following message:

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `AleoLocator { hrp: "al", data: Fp256(5282275773890731157584737813554920628646489886080748107602225735608185483169) }`,
 right: `AleoLocator { hrp: "al", data: Fp256(1884776062570810188821888786119248707234339675300075632591471437638835544945) }`', /root/snarkOS/storage/src/state/ledger.rs:212:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

then miner can not be restarted anylonger with the stored ledger, I must delete the whole ledger and re-sync.

## Expected Behavior

No crashing here.

## My Environment

Dedicated Server: Contabo, 96core, 256G 
 snarkOS Version: 11
Rust Version: 1.56.1
 Computer OS: ubuntu

**Comment by wudizhuzhuxia** [comment]
rm -rf .ledger-2
cargo run --release -- clean
./run-miner.sh

**Comment by ljedrz** [comment]
Previously reported in https://github.com/AleoHQ/snarkOS/issues/1360.

**Comment by iamnader** [comment]
Still happening

**Comment by ljedrz** [comment]
You can also use `cargo run --release -- clean` instead of the manual `rm -rf .ledger-2` (which will work only if you're using the default port for the listener).

**Comment by ljedrz** [comment]
A potential fix applicable to cases where there was no actual storage corruption was filed as https://github.com/AleoHQ/snarkOS/pull/1413. In order to double-check that it solves the issue, if you encounter it locally, please perform the following steps in your snarkOS directory:
1. `git remote add harukama https://github.com/HarukaMa/snarkOS.git`
2. `git fetch harukama ledger-load-fix`
3. `git checkout harukama/ledger-load-fix`
4. start the node as you normally would

**Comment by TiredFingers** [comment]
@ljedrz should step 3 be like `git commit` ?

**Comment by ljedrz** [comment]
That solution is no longer applicable, as the linked patch is already in the codebase; the final fix for storage inconsistencies is pending in https://github.com/AleoHQ/snarkOS/pull/1542 but sadly, that one won't fix an already inconsistent ledger (just prevent it from happening).
