### ISSUE TITLE
[Bug] PoSW difficulty target is not met

### ISSUE THREAD

**Issue by gddrx** [AleoHQ/snarkOS#1376]
## 🐛 Bug Report

PoSW difficulty target is not met. Expected 46079330320939720, found 6467670547318679853
PoSW difficulty target is not met. Expected 46079330320939720, found 1765425414809729745
PoSW difficulty target is not met. Expected 46079330320939720, found 16559348865332598953

## Steps to Reproduce

1. Start Aleod-miner
2. Step Wait Sync
3. Step When mining this strings in logs showing by: 
`journalctl -u aleod-miner -o cat -n 10 -f | grep -w 'successfully\|block\|ping\|fatal\|error\|critical\|mining\|PoSW'`

## Expected Behavior

Nothing.

## Your Environment

- snarkos 2.0.0 
- rustc 1.57.0 (f1edd0429 2021-11-29)
- Ubuntu 20.04.3 LTS

Some bigger log in file.

[poswbug.log](https://github.com/AleoHQ/snarkOS/files/7652710/poswbug.log)

**Comment by raychu86** [comment]
This output is simply saying the mined (candidate) block has not met the difficulty target that deems it valid. 

Since people seem to find the message a bit confusing, we'll look into updating it.
