### ISSUE TITLE
[Proposal] Drop current rpc

### ISSUE THREAD

**Issue by e4m7he6g** [AleoHQ/snarkOS#1381]
## 💥 Proposal

Some nodes closed by firewall or running nodes on same IP with different network port. RPC port closed. Nobody knows height, peers for closed RPC nodes. 

In near future 
Nobody knowns real mined blocks by node `getblocksmined` https://github.com/AleoHQ/snarkOS/pull/1305 because closed RPC

My vision RPC
1) metrics for prometheus like this https://github.com/unordered-set/AleoRPC2Prometheus

2) something like wasm or another RPC **running on network protocol** (eg 4132 port) with params for all queries

```
method: "getblocks"
params: [{ ip: "1.1.1.1", port: 4132, from: 20, to: 40 }]
```

**Comment by ljedrz** [comment]
A network-based crawler node is a planned feature; it will not rely on RPC to collect data from all the nodes in the network.

**Comment by ljedrz** [comment]
Linking the pending network-based crawler implementation: https://github.com/AleoHQ/snarkOS/pull/1662.

**Comment by ljedrz** [comment]
Not applicable to testnet3.
