### ISSUE TITLE
[Proposal] Decentralization improvement proposal (DIP)

### ISSUE THREAD

**Issue by tokenoman** [AleoHQ/snarkOS#1386]
## 💥 Decentralization improvement proposal (DIP)

For every blocks sequence of lengh N: block author of every block should be unique. Constant N could be changed to balance network decentralization and performance.

Pros:
  
  1. DIP will help to increase decentralization of the protocol: N is minimum guaranteed size of network peers;
  2. For the current testnet condition it will eliminate "selfish mining" (when one or couple of power miner nodes found all the blocks) and will encourage contest parties to find new ways to reach the top score, and thus make testnet context more competetive and diversified in favor of mainnet;
  3. proposal realisation in code seems to be simple enough and could be excluded from mainnet codebase if it will show negative impact on network performance and if there will be found more convenient ways to ensure decentralization;
  4. in current testnet conditions DIP will help testers became players, not watchers.

Cons:

  May have impact on network performance

**Comment by howardwu** [comment]
Closing as a miner may choose to be public or private. For the incentivized testnet, miners have chosen to opt-in to a public coinbase record.
