### ISSUE TITLE
[Bug] snarkOS 1.3.17 installation from cargo fails at snarkos-storage v1.3.17

### ISSUE THREAD

**Issue by 1elbaz** [AleoHQ/snarkOS#1387]
## 🐛 Bug Report

Installing snarkOS from cargo fails when compiling snarkos-storage v1.3.17.

^[[B^[[B    Building [=======================> ] 398/409: librocksdb-sys            Compiling rocksdb v0.17.0
   Compiling snarkos-storage v1.3.17
error: 1 positional argument in format string, but no arguments were given
  --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/key_value/store.rs:70:57
   |
70 |             return Err(anyhow!("invalid length for u32: {}"));
   |                                                         ^^

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/rocks.rs:177:9
    |
156 |       fn open_cf<P: AsRef<Path>>(path: P, num_cfs: u32) -> Result<Self, StorageError> {
    |                                                            -------------------------- expected `std::result::Result<RocksDb, StorageError>` because of return type
...
177 | /         Ok(Self {
178 | |             db: Some(storage),
179 | |             cf_names,
180 | |             current_transaction: None,
181 | |         })
    | |__________^ expected enum `StorageError`, found struct `anyhow::Error`
    |
    = note: expected enum `std::result::Result<_, StorageError>`
               found enum `std::result::Result<_, anyhow::Error>`

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:185:66
    |
185 |         self.conn.query_row(r"PRAGMA journal_mode=WAL;", [], |_| Ok(()))?;
    |                                                                  ^^^^^^
    |                                                                  |
    |                                                                  expected enum `rusqlite::Error`, found struct `anyhow::Error`
    |                                                                  help: try using a variant of the expected enum: `objects::peer::_::_serde::__private::Ok(Ok(()))`
    |
    = note: expected enum `std::result::Result<_, rusqlite::Error>`
               found enum `std::result::Result<(), anyhow::Error>`

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:387:21
    |
387 | /                     Ok(SerialBlockHeader {
388 | |                         previous_block_hash: row.get(0)?,
389 | |                         merkle_root_hash: MerkleRootHash(read_static_blob(row, 1)?),
390 | |                         pedersen_merkle_root_hash: PedersenMerkleRootHash(read_static_blob(row, 2)?),
...   |
394 | |                         nonce: row.get(6)?,
395 | |                     })
    | |______________________^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
    |
    = note: expected enum `std::result::Result<_, rusqlite::Error>`
               found enum `std::result::Result<objects::block_header::SerialBlockHeader, anyhow::Error>`
help: try using a variant of the expected enum
    |
387 ~                     objects::peer::_::_serde::__private::Ok(Ok(SerialBlockHeader {
388 +                         previous_block_hash: row.get(0)?,
389 +                         merkle_root_hash: MerkleRootHash(read_static_blob(row, 1)?),
390 +                         pedersen_merkle_root_hash: PedersenMerkleRootHash(read_static_blob(row, 2)?),
391 +                         proof: ProofOfSuccinctWork(read_static_blob(row, 3)?),
392 +                         time: row.get(4)?,
  ...

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:460:13
    |
460 | /             Ok(SerialTransaction {
461 | |                 id: read_static_blob(row, 0)?,
462 | |                 network: Network::from_id(row.get(1)?),
463 | |                 ledger_digest: row.get(2)?,
...   |
473 | |                 inner_circuit_id: row.get(16)?,
474 | |             })
    | |______________^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
    |
    = note: expected enum `std::result::Result<_, rusqlite::Error>`
               found enum `std::result::Result<objects::transaction::SerialTransaction, anyhow::Error>`
help: try using a variant of the expected enum
    |
460 ~             objects::peer::_::_serde::__private::Ok(Ok(SerialTransaction {
461 +                 id: read_static_blob(row, 0)?,
462 +                 network: Network::from_id(row.get(1)?),
463 +                 ledger_digest: row.get(2)?,
464 +                 old_serial_numbers: vec![row.get(3)?, row.get(4)?],
465 +                 new_commitments: vec![row.get(5)?, row.get(6)?],
  ...

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:686:44
    |
686 |             .query_map([block_hash], |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)))?
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
    |
    = note: expected type `std::result::Result<_, rusqlite::Error>`
               found enum `std::result::Result<(_, _, _), anyhow::Error>`

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:759:44
    |
759 |             .query_map([scan_depth], |row| Ok((row.get(0)?, row.get(1)?)))?
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
    |
    = note: expected type `std::result::Result<_, rusqlite::Error>`
               found enum `std::result::Result<(_, _), anyhow::Error>`

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:780:21
    |
780 | /                     Ok(TransactionLocation {
781 | |                         index: row.get(0)?,
782 | |                         block_hash: row.get(1)?,
783 | |                     })
    | |______________________^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
    |
    = note: expected enum `std::result::Result<_, rusqlite::Error>`
               found enum `std::result::Result<transaction_location::TransactionLocation, anyhow::Error>`
help: try using a variant of the expected enum
    |
780 ~                     objects::peer::_::_serde::__private::Ok(Ok(TransactionLocation {
781 +                         index: row.get(0)?,
782 +                         block_hash: row.get(1)?,
783 +                     }))
    |

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:819:21
    |
819 | /                     Ok(SerialTransaction {
820 | |                         id: read_static_blob(row, 0)?,
821 | |                         network: Network::from_id(row.get(1)?),
822 | |                         ledger_digest: row.get(2)?,
...   |
832 | |                         inner_circuit_id: row.get(16)?,
833 | |                     })
    | |______________________^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
    |
    = note: expected enum `std::result::Result<_, rusqlite::Error>`
               found enum `std::result::Result<objects::transaction::SerialTransaction, anyhow::Error>`
help: try using a variant of the expected enum
    |
819 ~                     objects::peer::_::_serde::__private::Ok(Ok(SerialTransaction {
820 +                         id: read_static_blob(row, 0)?,
821 +                         network: Network::from_id(row.get(1)?),
822 +                         ledger_digest: row.get(2)?,
823 +                         old_serial_numbers: vec![row.get(3)?, row.get(4)?],
824 +                         new_commitments: vec![row.get(5)?, row.get(6)?],
  ...

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:874:21
    |
874 | /                     Ok(SerialRecord {
875 | |                         owner: row
876 | |                             .get::<_, String>(0)?
877 | |                             .parse()
...   |
888 | |                         position: None,
889 | |                     })
    | |______________________^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
    |
    = note: expected enum `std::result::Result<_, rusqlite::Error>`
               found enum `std::result::Result<objects::record::SerialRecord, anyhow::Error>`
help: try using a variant of the expected enum
    |
874 ~                     objects::peer::_::_serde::__private::Ok(Ok(SerialRecord {
875 +                         owner: row
876 +                             .get::<_, String>(0)?
877 +                             .parse()
878 +                             .map_err(|_| rusqlite::Error::InvalidQuery)?,
879 +                         is_dummy: row.get(1)?,
  ...

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:948:45
    |
948 |             .query_map([block_start], |row| Ok([row.get(0)?, row.get(1)?]))?
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
    |
    = note: expected type `std::result::Result<_, rusqlite::Error>`
               found enum `std::result::Result<[_; 2], anyhow::Error>`

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:972:45
    |
972 |             .query_map([block_start], |row| Ok([row.get(0)?, row.get(1)?]))?
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
    |
    = note: expected type `std::result::Result<_, rusqlite::Error>`
               found enum `std::result::Result<[_; 2], anyhow::Error>`

error[E0308]: mismatched types
    --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:1220:21
     |
1220 | /                     Ok(Peer {
1221 | |                         address,
1222 | |                         block_height: row.get(0)?,
1223 | |                         first_seen: row
...    |
1238 | |                         connection_transient_fail_count: row.get(10)?,
1239 | |                     })
     | |______________________^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
     |
     = note: expected enum `std::result::Result<_, rusqlite::Error>`
                found enum `std::result::Result<peer::Peer, anyhow::Error>`
help: try using a variant of the expected enum
     |
1220 ~                     objects::peer::_::_serde::__private::Ok(Ok(Peer {
1221 +                         address,
1222 +                         block_height: row.get(0)?,
1223 +                         first_seen: row
1224 +                             .get::<_, Option<i64>>(1)?
1225 +                             .map(|x| DateTime::from_utc(NaiveDateTime::from_timestamp(x, 0), Utc)),
   ...

error[E0308]: mismatched types
    --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/sync.rs:1270:13
     |
1270 | /             Ok(Peer {
1271 | |                 address: row
1272 | |                     .get::<_, String>(0)?
1273 | |                     .parse()
...    |
1291 | |                 connection_transient_fail_count: row.get(11)?,
1292 | |             })
     | |______________^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
     |
     = note: expected enum `std::result::Result<_, rusqlite::Error>`
                found enum `std::result::Result<peer::Peer, anyhow::Error>`
help: try using a variant of the expected enum
     |
1270 ~             objects::peer::_::_serde::__private::Ok(Ok(Peer {
1271 +                 address: row
1272 +                     .get::<_, String>(0)?
1273 +                     .parse()
1274 +                     .map_err(|_| rusqlite::Error::InvalidQuery)?,
1275 +                 block_height: row.get(1)?,
   ...

error[E0308]: mismatched types
  --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/mod.rs:69:37
   |
67 |     fn column_result(value: ValueRef<'_>) -> FromSqlResult<Self> {
   |                                              ------------------- expected `std::result::Result<digest::Digest, FromSqlError>` because of return type
68 |         match value {
69 |             ValueRef::Blob(blob) => Ok(Self::from(blob)),
   |                                     ^^^^^^^^^^^^^^^^^^^^ expected enum `FromSqlError`, found struct `anyhow::Error`
   |
   = note: expected enum `std::result::Result<_, FromSqlError>`
              found enum `std::result::Result<_, anyhow::Error>`

error[E0308]: mismatched types
  --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/storage/sqlite/mod.rs:77:9
   |
76 |     fn to_sql(&self) -> rusqlite::Result<ToSqlOutput<'_>> {
   |                         --------------------------------- expected `std::result::Result<ToSqlOutput<'_>, rusqlite::Error>` because of return type
77 |         Ok(ToSqlOutput::Borrowed(ValueRef::Blob(&self[..])))
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `rusqlite::Error`, found struct `anyhow::Error`
   |
   = note: expected enum `std::result::Result<ToSqlOutput<'_>, rusqlite::Error>`
              found enum `std::result::Result<ToSqlOutput<'_>, anyhow::Error>`

error[E0308]: mismatched types
  --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/objects/block.rs:70:9
   |
64 |     pub fn write_transactions<W: Write>(&self, mut writer: W) -> IoResult<()> {
   |                                                                  ------------ expected `std::result::Result<(), std::io::Error>` because of return type
...
70 |         Ok(())
   |         ^^^^^^ expected struct `std::io::Error`, found struct `anyhow::Error`
   |
   = note: expected enum `std::result::Result<_, std::io::Error>`
              found enum `std::result::Result<_, anyhow::Error>`

error[E0308]: mismatched types
  --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/objects/record.rs:77:5
   |
74 | fn to_bytes_to_digest<B: ToBytes>(from: &B) -> IoResult<Digest> {
   |                                                ---------------- expected `std::result::Result<digest::Digest, std::io::Error>` because of return type
...
77 |     Ok(out)
   |     ^^^^^^^ expected struct `std::io::Error`, found struct `anyhow::Error`
   |
   = note: expected enum `std::result::Result<_, std::io::Error>`
              found enum `std::result::Result<_, anyhow::Error>`

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/objects/transaction.rs:109:9
    |
88  |     fn write_le<W: Write>(&self, mut writer: W) -> IoResult<()> {
    |                                                    ------------ expected `std::result::Result<(), std::io::Error>` because of return type
...
109 |         Ok(())
    |         ^^^^^^ expected struct `std::io::Error`, found struct `anyhow::Error`
    |
    = note: expected enum `std::result::Result<_, std::io::Error>`
               found enum `std::result::Result<_, anyhow::Error>`

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/objects/transaction.rs:122:5
    |
119 | fn serialize_digest<B: ToBytes>(bytes: &B) -> IoResult<Digest> {
    |                                               ---------------- expected `std::result::Result<digest::Digest, std::io::Error>` because of return type
...
122 |     Ok(Digest(out))
    |     ^^^^^^^^^^^^^^^ expected struct `std::io::Error`, found struct `anyhow::Error`
    |
    = note: expected enum `std::result::Result<_, std::io::Error>`
               found enum `std::result::Result<_, anyhow::Error>`

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/objects/transaction.rs:128:5
    |
125 | fn serialize_bytes<B: ToBytes>(bytes: &B) -> IoResult<Vec<u8>> {
    |                                              ----------------- expected `std::result::Result<Vec<u8>, std::io::Error>` because of return type
...
128 |     Ok(out)
    |     ^^^^^^^ expected struct `std::io::Error`, found struct `anyhow::Error`
    |
    = note: expected enum `std::result::Result<_, std::io::Error>`
               found enum `std::result::Result<_, anyhow::Error>`

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/objects/transaction.rs:136:5
    |
131 | fn serialize_many_digests<B: ToBytes>(items: &[B]) -> IoResult<Vec<Digest>> {
    |                                                       --------------------- expected `std::result::Result<Vec<digest::Digest>, std::io::Error>` because of return type
...
136 |     Ok(out)
    |     ^^^^^^^ expected struct `std::io::Error`, found struct `anyhow::Error`
    |
    = note: expected enum `std::result::Result<_, std::io::Error>`
               found enum `std::result::Result<_, anyhow::Error>`

error[E0308]: mismatched types
   --> /Users/XXX/.cargo/registry/src/github.com-1ecc6299db9ec823/snarkos-storage-1.3.17/src/objects/transaction.rs:155:9
    |
148 |       fn deserialize(tx: &SerialTransaction) -> IoResult<Self> {
    |                                                 -------------- expected `std::result::Result<snarkvm_dpc::testnet1::Transaction<T>, std::io::Error>` because of return type
...
155 | /         Ok(Transaction {
156 | |             network: tx.network,
157 | |             ledger_digest: deserialize_bytes(&tx.ledger_digest)?,
158 | |             old_serial_numbers,
...   |
167 | |             inner_circuit_id: deserialize_bytes(&tx.inner_circuit_id)?,
168 | |         })
    | |__________^ expected struct `std::io::Error`, found struct `anyhow::Error`
    |
    = note: expected enum `std::result::Result<snarkvm_dpc::testnet1::Transaction<T>, std::io::Error>`
               found enum `std::result::Result<snarkvm_dpc::testnet1::Transaction<_>, anyhow::Error>`

For more information about this error, try `rustc --explain E0308`.
error: failed to compile `snarkos v1.3.17`, intermediate artifacts can be found at `/var/folders/1b/29nxcvcd5bxflv40lycy1lyw0000gn/T/cargo-installZ97BKG`

Caused by:
  could not compile `snarkos-storage` due to 23 previous errors

## Steps to Reproduce

(following this https://developer.aleo.org/testnet/getting_started/installation)
1. Install Rust via Rustup
2. Install snarkos via cargo

## Expected Behavior

Complete installation successfully with no errors

## Your Environment

-  snarkOS 1.3.17
-  rustc 1.57.0 (f1edd0429 2021-11-29)
-  macOS

**Comment by ljedrz** [comment]
The currently supported node version is `2.0.0`; please follow the instructions in the [README](https://github.com/AleoHQ/snarkOS/blob/testnet2/README.md) to switch to the current setup.
