### ISSUE TITLE
[Feature] Increase block time generation

### ISSUE THREAD

**Issue by xbeastx** [AleoHQ/snarkOS#1388]
## 🚀 Feature

I believe that network is not stable because (at least) the block generation time (calculated with difficulty inside [this function](https://github.com/AleoHQ/snarkVM/blob/29bfb3ac537c75bb51ef55e7318a6f48def35182/dpc/src/ledger/blocks.rs#L408)) is really low.
Because miners generate blocks so fast and they intersect with each others as a result too many forks on network. If we will increase block generation time new blocks will be more distributed across the network as a result more miners will participate in generating new blocks based on this one.

## Motivation

Network is not stable

## Implementation

https://github.com/AleoHQ/snarkVM/pull/520

I ended up with 5 minutes. But we can discuss what time more acceptable...

**Comment by steven004** [comment]
Strongly supporting this. 
The first thing for a chain in the testnet is to verify the functionality, security, and later to try performance. Firstly stablize the network, and then to test the limit.
