### ISSUE TITLE
[Bug] "posw.proving.b2d14c7" does not exist

### ISSUE THREAD

**Issue by daijingping** [AleoHQ/snarkOS#1401]
## 🐛 Bug Report

i run  ./run-miner.sh
 there is a attention ATTENTION - "posw.proving.b2d14c7" does not exist, downloading this file remotely and storing it locally. Please ensure "posw.proving.b2d14c7" is stored in "/Users/xxxxx/.aleo/./resources/posw.proving.b2d14c7".

and an error  NaNthread 'main' panicked at 'Failed to load parameter bytes for posw proving key: Crate("curl::error", "Error { description: \"Couldn't connect to server\", code: 7, extra: Some(\"Failed to connect to s3-us-west-1.amazonaws.com port 443: Operation timed out\") }")', /Users/xxxxxx/.cargo/git/checkouts/snarkvm-f1160780ffe17de8/471e03b/dpc/src/network/testnet2.rs:269:5

i ping this server its really timeout

**Comment by goomario** [comment]
Please make sure you can access AWS. The launch file will download from `https://s3-us-west-1.amazonaws.com/aleo.parameters`

**Comment by daijingping** [comment]
![image](https://user-images.githubusercontent.com/8671101/145527094-9dae39e1-06f3-401b-828b-5e1d5c4034de.png)

**Comment by daijingping** [comment]
> Please make sure you can access AWS. The launch file will download from `https://s3-us-west-1.amazonaws.com/aleo.parameters`

![image](https://user-images.githubusercontent.com/8671101/145527180-a08b3c2d-fbb0-49a3-ac6a-2647267f7246.png)

**Comment by howardwu** [comment]
@daijingping Please try this link:

https://s3-us-west-1.amazonaws.com/aleo.parameters/posw.proving.b2d14c7

This is the link that snarkOS uses to fetch the PoSW parameters from. I can verify it works here. If it does not work on your machine, you will likely need a proxy or VPN to operate. If you do use a proxy or VPN, please ensure your node has sufficient bandwidth to operate performantly on the network.

Feel free to close this issue if it is resolved.

**Comment by daijingping** [comment]
> 

this link is useful，thanks，i will close this
