### ISSUE TITLE
[snarkos-metrics] Implement exporter for Prometheus

### ISSUE THREAD

**Issue by devzorg** [AleoHQ/snarkOS#1402]
## 🚀 Feature

Would like to see in Grafana confirmed blocks, pending blocks, current height, cumulative height and etc metrics using Prometheus

## Motivation

It's would be convenience for monitoring numbers of nodes in Grafana.

## Implementation

Looks like it implemented in snarkos-metrics

**Comment by unordered-set** [comment]
Yes, there was some code for that, but it got lost during testnet2 as I can see from git. Meanwhile I'm working on https://github.com/unordered-set/AleoRPC2Prometheus - proxy between RPC and PRometheus

**Comment by ljedrz** [comment]
Done in https://github.com/AleoHQ/snarkOS/pull/1480; initial metrics introduced in https://github.com/AleoHQ/snarkOS/pull/1651, more will come shortly.
