### ISSUE TITLE
[Bug] Fatal error on start if node not exists

### ISSUE THREAD

**Issue by devzorg** [AleoHQ/snarkOS#1407]
## 🐛 Bug Report

If we set node to connect manually in argument using --node and node is not exist (not ran) it could prevent tot fatal error on start up.

(Write your description here)

## Steps to Reproduce

1. Run snark os with argument --node IP:4132
2. Check logs

## Expected Behavior

Just show warning 'Cann't connect to node' instead of fatal error on start.

## Your Environment

Snarkos 2.0.0 v11
Rust 1.57
Ubuntu 20.04 minimal

**Comment by ljedrz** [comment]
`--node` is used to specify your node's address, not an address for it to connect to (that's `--connect`); do you mean that a node should pick a random port if the default one is unavailable?
