### ISSUE TITLE
Split `DPC` into subtraits and individual structs

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#141]
This step was originally intended to be performed after migration to `snarkVM`.

As parameters have become a blocker, we're moving up this split to facilitate the migration of parameters and testing parameters out of `snarkos-dpc` and into `genesis` and `testing` modules.

This split should help to ensure developers have inconvenient access to the `Setup` operation, and enforce system safety for Aleo runtimes.

**Comment by ljedrz** [comment]
Other than DPC having been moved to snarkVM, I think this has already been achieved; please feel free to reopen+transfer the issue to snarkVM if there's anything left to do here @howardwu.
