### ISSUE TITLE
[Bug] Mining the same block for a long time is not the latest block 

### ISSUE THREAD

**Issue by guqing7** [AleoHQ/snarkOS#1428]
## 🐛 Bug Report

 Mining the same block for a long time is not the latest block : 43780

## Steps to Reproduce

1. Step 1 ./run-miner.sh
2. Step 2 peering
3. Step 3 syncing
4.  mining
5. Log report

2021-12-15T09:20:06.882899Z DEBUG Status Report (type = Miner, status = Mining, block_height = 43780, cumulative_weight = 795706509, block_requests = 0, connected_peers = 12)
PoSW difficulty target is not met. Expected 658631888161057, found 1056885358682504724
PoSW difficulty target is not met. Expected 655557788657232, found 15702499025041923761
PoSW difficulty target is not met. Expected 1537980225957643, found 15311264760474457074
PoSW difficulty target is not met. Expected 8527678965673, found 1055665586009922255
PoSW difficulty target is not met. Expected 1627798271153565, found 8869983944097521137
PoSW difficulty target is not met. Expected 899564718569106, found 745405401213105526
PoSW difficulty target is not met. Expected 8976504174393, found 13205161163534207870
PoSW difficulty target is not met. Expected 268325230298759, found 7894022812825003974
2021-12-15T09:20:15.883399Z DEBUG Status Report (type = Miner, status = Mining, block_height = 43780, cumulative_weight = 795706509, block_requests = 0, connected_peers = 12)
PoSW difficulty target is not met. Expected 4609705501003019, found 7442030088942069820
2021-12-15T09:20:24.884867Z DEBUG Status Report (type = Miner, status = Mining, block_height = 43780, cumulative_weight = 795706509, block_requests = 0, connected_peers = 12)
PoSW difficulty target is not met. Expected 3245785146773661, found 1802171027546316509
PoSW difficulty target is not met. Expected 225436026295956, found 18440280605219869229
PoSW difficulty target is not met. Expected 875891962817288, found 2297332992976671689
PoSW difficulty target is not met. Expected 3770127642156272, found 3306964693323285162

## Expected Behavior

 After sync 43780, why not continue to sync the block height 
## Your Environment

snarkos 2.0.0
rustc 1.57.0 (f1edd0429 2021-11-29)
ubuntu 20.04

**Comment by xbeastx** [comment]
It's not a bug. There is a log line inside mining loop [here](https://github.com/AleoHQ/snarkVM/blob/testnet2/dpc/src/posw/posw.rs#L118) which logs unsuccessful attempts of creating new block.

**Comment by guqing7** [comment]
> It's not a bug. There is a log line inside mining loop [here](https://github.com/AleoHQ/snarkVM/blob/testnet2/dpc/src/posw/posw.rs#L118) which logs unsuccessful attempts of creating new block.

Stay at this height for a long long time ago!

**Comment by ljedrz** [comment]
This indeed doesn't look like a bug; there is some forking at the tip which, AFAIK, is quite normal, as they get resolved after a short amount of time. In the end, it's your chain that might become recognized as the canonical one.

> a long long time

How long is that?

**Comment by guqing7** [comment]
> 

Run again ./run-miner. sh, it's normal.

**Comment by guqing7** [comment]
2021-12-16T03 : 13 : 29 . 467756Z INFO Mining Report ( confirmed blocks = 0 , pending blocks = 0 miner address = aleo1dmdv5d666t2yfg7uwu7x5ua0yzcdyc46fjxl）

 Does this report mean that the miner has started, but no block has been miner.

**Comment by ljedrz** [comment]
Yes.

**Comment by howardwu** [comment]
If your node is stuck on a block height, I suggest running `cargo run --release -- clean` to clear the ledger.
