### ISSUE TITLE
What affects block mining?

### ISSUE THREAD

**Issue by guqing7** [AleoHQ/snarkOS#1438]
## 🐛 Bug Report

Aleo mining node has been run. How can mining a block!

## Steps to Reproduce

1. Step 1...
2. Step 2...
3. Step 3...

## Expected Behavior

(Write what you expected to happen here)

## Your Environment

- 
- 
-

**Comment by ljedrz** [comment]
I'm not sure what this means, but I'm assuming that your node hasn't mined a block in a long time? Please fill out the expected behavior and your observations.

**Comment by guqing7** [comment]
> I'm not sure what this means, but I'm assuming that your node hasn't mined a block in a long time? Please fill out the expected behavior and your observations.

I've been running for two days. I want to know what affects my mined a block

**Comment by ljedrz** [comment]
Your node needs to be fully synced and have at least the minimum number of peers.

**Comment by guqing7** [comment]
> Your node needs to be fully synced and have at least the minimum number of peers.

snarkos stats

CONNECTED PEERS:
"61.173.37.223:4132"
"121.15.197.237:4132"
"95.181.153.195:4132"
"185.191.127.145:4132"
"65.108.104.58:4132"
"67.227.130.43:4132"
"8.209.98.148:4132"
"157.90.130.43:4132"
"67.227.130.61:4132"
"118.193.103.172:4132"
"178.208.95.9:4132"
"36.189.234.237:20000"
"95.214.55.88:4132"
"206.189.44.102:4132"
"31.222.238.3:4132"
"134.249.187.129:4132"
"89.108.109.231:4132"
"121.52.246.85:20003"
"35.204.209.130:4132"

LATEST BLOCK HEIGHT:	49728
-----------------------------------------------

NODE STATE:	{
  "candidate_peers": [
    "121.52.246.85:20010",
    "185.244.175.231:4132",
    "185.37.190.43:4132",
    "135.181.95.165:4132",
    "23.29.117.106:4132",
    "5.39.217.125:4132",
    "47.254.128.145:4132",
    "122.224.89.173:191",
    "46.148.231.72:4132",
    "194.242.56.59:4132",
    "194.242.56.168:4132",
    "122.224.89.173:6431",
    "147.75.62.83:4155",
    "65.21.227.172:4132",
    "65.108.45.132:4132",
    "176.57.150.5:4132",
    "176.9.26.180:4132",
    "161.35.145.210:4132",
    "146.59.47.102:4132",
    "162.55.243.237:4132",
    "65.108.96.98:4132",
    "144.126.129.76:4132",
    "175.106.99.65:4132",
    "142.132.128.111:4132",
    "65.21.197.219:4132",
    "31.131.254.51:4132",
    "146.0.78.78:4132",
    "65.108.73.148:4132",
    "209.145.60.171:4132",
    "95.217.74.37:4132",
    "65.108.76.44:4132",
    "159.223.124.150:4132",
    "193.70.81.130:4132",
    "183.2.157.209:4132",
    "117.21.202.44:4132",
    "44.196.88.107:4132",
    "46.31.77.23:4132",
    "103.39.230.54:4132",
    "8.209.109.34:4132",
    "46.191.234.235:4132",
    "116.202.227.177:4132",
    "65.21.192.215:4132",
    "5.161.51.71:4132",
    "154.31.41.217:4132",
    "95.216.39.139:4132",
    "188.40.94.94:4132",
    "122.224.89.173:6111",
    "47.254.129.16:4132",
    "180.119.136.6:4132",
    "185.225.233.184:4132",
    "146.0.228.179:4132",
    "141.94.115.190:4132",
    "47.89.185.88:4132",
    "88.198.81.218:4132",
    "185.225.233.125:4132",
    "159.223.118.35:4132",
    "154.31.41.236:4132",
    "78.81.147.113:4132",
    "107.149.163.67:4132",
    "143.198.164.241:4132",
    "88.99.59.61:4132",
    "23.88.72.187:4132",
    "69.46.15.194:4132",
    "159.146.90.45:4132",
    "147.182.213.228:4132",
    "141.94.115.181:4132",
    "66.94.120.12:4132",
    "45.67.229.45:4132",
    "38.91.101.253:4132",
    "82.202.162.162:4132",
    "115.236.46.99:20004",
    "185.244.175.36:4132",
    "8.209.109.36:4132",
    "142.132.136.81:4132",
    "47.108.171.26:4132",
    "65.108.40.173:4132",
    "8.209.101.222:4132",
    "185.132.176.151:4132",
    "176.215.23.238:4132",
    "162.55.0.225:4132",
    "154.85.33.36:4132",
    "92.63.111.18:4132",
    "116.202.82.111:4132",
    "142.132.136.86:4132",
    "120.226.39.46:4132",
    "136.243.73.54:4132",
    "122.224.89.173:6551",
    "84.38.188.129:4132",
    "161.97.149.45:4132",
    "23.88.113.206:4132",
    "104.233.197.175:4132",
    "47.91.79.80:4132",
    "165.232.145.194:4132",
    "47.253.43.43:4132",
    "132.226.195.179:4132",
    "85.14.245.90:4132",
    "142.132.128.205:4132",
    "65.108.43.43:4132",
    "46.4.23.42:4132",
    "121.52.246.85:20004",
    "54.215.102.146:4132",
    "54.183.190.54:4132",
    "85.114.132.90:4132",
    "38.114.114.122:4132",
    "149.28.58.30:4132",
    "150.246.81.189:4132",
    "66.94.114.1:4132",
    "157.245.82.252:4132",
    "31.135.8.113:4132",
    "94.26.231.201:4132",
    "95.216.246.24:4132",
    "45.57.227.186:4132",
    "138.201.195.163:4132",
    "128.199.188.224:4132",
    "5.161.50.172:4132",
    "65.108.76.31:4132",
    "194.163.136.100:4132",
    "3.145.207.233:4132",
    "86.109.15.135:4151",
    "152.89.219.174:4132",
    "65.108.79.238:4132",
    "122.224.89.173:1101",
    "89.108.72.177:4132",
    "51.222.240.137:4132",
    "95.217.227.227:4132",
    "144.126.129.182:4132",
    "5.167.77.144:4132",
    "51.222.203.181:4132",
    "62.141.45.89:4132",
    "104.233.192.252:4132",
    "112.31.76.10:4132",
    "118.195.154.215:4132",
    "194.190.153.213:4132",
    "36.189.234.238:62226",
    "69.46.15.26:4132",
    "122.224.89.173:6541",
    "185.151.240.219:4132",
    "135.181.215.49:4132",
    "47.89.155.73:4132",
    "65.21.231.105:4132",
    "144.126.129.248:4132",
    "113.107.201.166:4132",
    "141.94.131.83:4132",
    "88.99.249.87:4132",
    "169.197.143.230:4132",
    "52.87.100.172:4132",
    "194.61.52.243:4132",
    "162.251.62.17:4132",
    "94.137.224.91:4132",
    "65.108.4.126:4132",
    "61.173.37.223:14539",
    "113.89.4.201:4132",
    "80.93.93.125:4132",
    "217.79.189.111:4132",
    "178.170.39.10:4132",
    "185.194.219.16:4132",
    "222.92.184.74:4132",
    "141.105.66.132:4132",
    "35.88.53.68:4132",
    "5.61.53.28:4132",
    "118.116.1.34:4132",
    "78.46.43.130:4132",
    "24.63.107.107:4002",
    "61.147.117.101:4132",
    "130.193.41.1:4132",
    "1.13.8.246:4132",
    "3.115.105.92:4132",
    "128.199.191.232:4132",
    "185.105.91.62:4132",
    "95.217.33.52:4132",
    "89.222.182.62:4132",
    "121.52.246.85:20008",
    "122.224.89.173:6851",
    "162.251.61.217:4132",
    "65.21.135.24:4132",
    "67.227.130.60:4132",
    "193.34.172.133:4132",
    "154.31.0.73:4132",
    "135.125.160.9:4132",
    "159.69.58.44:4132",
    "59.29.238.114:4132",
    "141.98.205.82:4132",
    "144.126.144.157:4132",
    "119.147.211.233:30039",
    "66.94.109.78:4132",
    "89.163.135.97:4132",
    "91.199.137.4:4132",
    "5.39.222.73:4132",
    "51.195.234.223:4132",
    "31.206.56.98:4132",
    "103.195.103.126:4132",
    "13.59.3.64:4132",
    "47.253.32.105:4132",
    "118.193.44.186:4132",
    "135.181.129.249:4132",
    "5.199.161.187:4132",
    "134.195.198.98:4132",
    "89.163.148.108:4132",
    "119.45.27.215:4132",
    "169.197.142.33:4132",
    "91.142.77.198:4132",
    "122.224.89.173:151",
    "151.106.52.141:4132",
    "162.62.124.157:4132",
    "137.184.202.162:4132",
    "8.217.10.111:4132",
    "110.53.221.139:3310",
    "86.109.15.135:4155",
    "95.214.55.193:4132",
    "65.108.15.155:4132",
    "119.45.30.72:4132",
    "23.29.126.186:4132",
    "47.252.43.59:4132",
    "54.250.161.214:4132",
    "157.90.168.221:4132",
    "47.241.66.113:4132",
    "65.108.106.123:4132",
    "139.64.165.67:4132",
    "103.73.119.21:4132",
    "121.52.246.85:20005",
    "92.241.105.140:4132",
    "185.16.39.22:4132",
    "46.31.77.37:4132",
    "142.202.241.147:4132",
    "84.252.73.142:4132",
    "213.21.210.8:4132",
    "198.244.165.50:4132",
    "65.108.77.174:4132",
    "65.108.78.187:4132",
    "161.97.183.158:4132",
    "88.99.242.181:4132",
    "31.135.8.195:4132",
    "188.68.217.197:4132",
    "167.99.40.226:4132",
    "159.223.45.176:4132",
    "142.132.134.28:4132",
    "185.132.133.20:4132",
    "65.108.13.58:4132",
    "144.76.82.241:4132",
    "141.94.139.18:4132",
    "104.233.197.174:4132",
    "38.121.43.129:4132",
    "95.217.104.222:4132",
    "178.151.164.212:4132",
    "185.225.233.152:4132",
    "168.119.39.16:4132",
    "89.108.111.133:4132",
    "169.197.141.62:4132",
    "8.211.190.16:4132",
    "27.210.212.149:4132",
    "121.52.246.85:20011",
    "185.130.226.92:4132",
    "144.126.130.160:4132",
    "146.0.229.227:4132",
    "39.103.221.94:4132",
    "39.103.201.8:4132",
    "8.209.108.94:4132",
    "62.171.175.170:4132",
    "5.189.180.205:4132",
    "113.107.201.163:4132",
    "66.94.127.51:4132",
    "161.35.210.106:4132",
    "95.214.55.100:4132",
    "194.61.52.241:4132",
    "135.181.210.194:4132",
    "185.211.6.254:4132",
    "142.132.132.221:4132",
    "139.155.92.12:4132",
    "141.95.45.177:4132",
    "137.184.192.155:4132",
    "159.69.69.42:4132",
    "65.108.15.62:4132",
    "137.74.219.52:4132",
    "89.163.151.123:4132",
    "61.147.117.110:4132",
    "104.238.220.160:4132",
    "38.64.138.243:4132",
    "178.18.245.198:4132",
    "51.79.93.165:4132",
    "185.40.31.78:4132",
    "108.171.214.26:4132",
    "103.39.230.54:20030",
    "65.21.143.220:4132",
    "121.52.246.85:20006",
    "65.21.33.220:4132",
    "154.31.41.243:4132",
    "122.224.89.173:131",
    "47.90.242.138:4132",
    "84.252.138.39:4132",
    "94.45.6.121:4132",
    "185.151.241.245:4132",
    "168.119.66.75:4132",
    "180.141.77.41:4132",
    "65.108.96.171:4132",
    "176.98.40.49:4132",
    "3.138.60.5:4132",
    "31.131.254.60:4132",
    "60.27.133.251:4132",
    "188.124.46.12:4132",
    "194.242.56.57:4132",
    "185.132.134.45:4132",
    "117.31.113.54:4132",
    "135.181.18.74:4132",
    "49.12.234.155:4132",
    "122.224.89.173:1111",
    "135.181.222.137:4132",
    "103.90.155.134:4132",
    "65.108.45.182:4132",
    "85.17.5.5:4132",
    "141.94.28.63:4132",
    "144.126.144.156:4132",
    "65.21.138.24:4132",
    "144.76.118.120:4132",
    "65.108.43.203:4132",
    "161.97.154.202:4132",
    "8.209.90.78:4132",
    "178.20.45.212:4132",
    "91.199.137.6:4132",
    "8.209.81.35:4132",
    "31.134.184.71:4132",
    "65.108.83.65:4132",
    "112.74.91.110:4132",
    "121.52.246.85:20009",
    "66.94.114.7:4132",
    "159.223.105.153:4132",
    "136.243.39.231:4132",
    "94.198.50.134:4132",
    "115.236.46.213:4132",
    "195.2.70.84:4132",
    "54.89.166.211:4132",
    "36.189.235.196:62225",
    "31.135.8.123:4132",
    "65.21.194.114:4132",
    "91.230.110.185:4132",
    "142.132.136.143:4132",
    "82.208.122.68:4132",
    "115.236.46.205:4132",
    "185.9.144.138:4132",
    "146.0.228.127:4132",
    "88.80.145.54:4132",
    "66.94.114.2:4132",
    "77.246.156.40:4132",
    "122.224.89.173:6481",
    "38.68.135.104:4132",
    "65.108.75.114:4132",
    "45.87.106.99:4132",
    "107.148.145.144:4132",
    "162.55.134.237:4132",
    "35.87.189.245:4132",
    "135.181.67.117:4132",
    "120.77.57.186:4132",
    "122.224.89.173:6521",
    "158.51.121.49:4132",
    "139.64.165.19:4132",
    "119.45.160.15:4132",
    "185.253.33.41:4132",
    "47.91.95.59:4132",
    "34.81.219.139:4132",
    "69.46.16.202:4132",
    "65.108.43.49:4132",
    "122.224.89.173:6651",
    "212.41.0.92:4132",
    "104.131.52.142:4132",
    "45.87.106.76:4132",
    "185.211.6.71:4132",
    "85.195.119.43:4132",
    "94.198.55.155:4132",
    "52.5.107.241:4132",
    "134.195.196.241:4132",
    "103.61.39.130:4132",
    "39.173.177.196:4132",
    "89.108.122.104:4132",
    "209.126.11.155:4132",
    "85.132.18.202:4132",
    "38.114.114.43:4132",
    "23.88.9.125:4132",
    "119.45.26.158:4132",
    "51.79.101.17:4132",
    "47.252.73.173:4132",
    "137.74.219.50:4132",
    "65.108.78.189:4132",
    "15.235.9.211:4132",
    "119.147.211.233:30041",
    "143.198.166.150:4132",
    "134.119.221.157:4132",
    "23.88.72.139:4132",
    "162.55.99.142:4132",
    "46.243.142.46:4132",
    "185.9.144.131:4132",
    "185.151.241.127:4132",
    "95.217.73.253:4132",
    "188.127.253.229:4132",
    "120.25.176.19:4132",
    "144.126.150.104:4132",
    "185.246.84.178:4132",
    "31.135.8.91:4132",
    "154.31.41.86:4132",
    "82.202.165.37:4132",
    "38.68.135.198:4132",
    "157.230.20.222:4132",
    "147.135.64.121:4132",
    "185.16.39.31:4132",
    "67.227.130.35:4132",
    "119.45.27.189:4132",
    "104.233.196.70:4132",
    "115.236.46.99:20012",
    "168.138.164.40:4132",
    "185.246.84.171:4132",
    "65.108.97.124:4132",
    "35.75.9.198:4132",
    "147.75.62.83:4154",
    "65.21.236.183:4132",
    "87.128.76.11:4135",
    "47.253.42.163:4132",
    "150.138.79.36:4132",
    "31.135.8.27:4132",
    "141.95.45.104:4132",
    "95.217.224.118:4132",
    "193.111.199.17:4132",
    "23.88.74.30:4132",
    "65.21.92.176:4132",
    "161.97.150.157:4132",
    "146.0.231.101:4132",
    "138.201.225.89:4132",
    "114.226.98.10:4132",
    "92.63.195.73:4132",
    "49.12.4.183:4132",
    "47.251.41.232:4132",
    "93.189.31.68:4132",
    "8.209.90.149:4132",
    "51.83.227.191:4132",
    "122.224.89.173:121",
    "142.132.133.24:4132",
    "15.235.12.144:4132",
    "146.0.35.54:4132",
    "86.109.15.135:4152",
    "144.126.131.15:4132",
    "59.63.199.203:4132",
    "178.62.75.246:4132",
    "50.28.14.15:4132",
    "146.0.228.167:4132",
    "103.90.155.130:4132",
    "154.31.41.212:4132",
    "120.25.173.154:4132",
    "103.244.117.50:4132",
    "65.108.46.39:4132",
    "103.244.117.30:4132",
    "62.113.118.78:4132",
    "115.236.46.99:20005",
    "185.211.6.253:4132",
    "46.3.197.23:4132",
    "195.201.197.168:4132",
    "157.90.134.95:4132",
    "93.95.103.53:4132",
    "135.181.112.106:4132",
    "188.166.7.13:4132",
    "122.224.89.173:6411",
    "144.76.197.42:4132",
    "212.64.215.43:4132",
    "116.202.192.177:4132",
    "23.88.72.69:4132",
    "119.147.211.233:30033",
    "103.90.155.112:4132",
    "65.108.71.188:4132",
    "65.21.194.218:4132",
    "65.108.97.252:4132",
    "162.55.135.11:4132",
    "154.85.38.154:4132",
    "39.108.37.153:4132",
    "3.225.75.71:4132",
    "213.246.39.191:4132",
    "95.217.38.158:4132",
    "103.149.93.54:5001",
    "138.201.55.113:4132",
    "8.209.102.4:4132",
    "94.130.132.41:4132",
    "31.135.8.19:4132",
    "168.119.69.60:4132",
    "122.224.89.173:6591",
    "46.3.197.33:4132",
    "62.213.85.246:4132",
    "155.138.221.100:4132",
    "161.35.106.91:4132",
    "194.163.144.29:4132",
    "65.21.77.245:4132",
    "91.242.229.175:4132",
    "3.128.87.56:4132",
    "198.244.176.199:4132",
    "117.23.165.135:4132",
    "146.0.231.71:4132",
    "107.155.64.226:4132",
    "136.243.7.91:4132",
    "119.147.211.233:30029",
    "141.94.131.43:4132",
    "103.164.54.150:4132",
    "161.97.123.12:4132",
    "109.197.120.95:4132",
    "31.131.254.38:4132",
    "173.249.57.88:4132",
    "3.112.225.103:4132",
    "92.119.76.226:4132",
    "61.173.33.155:4132",
    "115.236.46.219:4132",
    "65.108.98.124:4132",
    "38.68.135.213:4132",
    "65.108.96.169:4132",
    "8.209.99.158:4132",
    "144.126.135.120:4132",
    "65.21.89.251:4132",
    "65.108.79.58:4132",
    "38.68.135.199:4132",
    "178.18.244.20:4132",
    "115.236.46.99:20009",
    "95.217.104.247:4132",
    "157.245.133.62:4132",
    "62.141.43.142:4132",
    "119.45.115.96:4132",
    "47.89.155.0:4132",
    "152.89.219.103:4132",
    "109.248.175.48:4132",
    "141.95.85.71:4132",
    "159.223.22.98:4132",
    "65.108.69.56:4132",
    "38.105.232.81:4132",
    "45.138.48.57:4132",
    "157.90.70.170:4132",
    "148.72.153.25:4132",
    "212.41.6.75:4132",
    "95.217.38.226:4132",
    "34.90.153.98:4132",
    "162.55.244.160:4132",
    "47.89.159.218:4132",
    "47.251.15.99:4132",
    "95.217.192.250:4132",
    "144.126.221.71:4132",
    "194.242.56.33:4132",
    "159.69.70.59:4132",
    "190.2.144.15:4132",
    "5.9.14.87:4132",
    "85.17.77.84:4132",
    "142.132.137.226:4132",
    "198.57.27.34:4132",
    "5.61.52.164:4132",
    "47.253.63.184:4132",
    "103.139.212.44:4132",
    "8.209.98.227:4132",
    "94.250.201.118:4132",
    "5.9.104.158:4132",
    "138.201.51.33:4132",
    "54.193.74.178:4132",
    "194.190.153.64:4132",
    "122.4.236.106:4135",
    "84.252.142.156:4132",
    "154.85.33.73:4132",
    "115.236.46.99:20008",
    "62.141.43.171:4132",
    "94.130.149.198:4132",
    "185.132.176.12:4132",
    "142.132.139.124:4132",
    "212.64.215.156:4132",
    "79.143.73.129:4132",
    "144.126.144.159:4132",
    "65.108.46.180:4132",
    "159.65.192.162:4132",
    "142.132.134.153:4132",
    "91.189.133.101:4132",
    "162.55.89.197:4132",
    "193.111.198.168:4132",
    "185.150.190.58:4132",
    "18.170.115.227:4132",
    "92.255.207.228:4132",
    "110.53.221.139:3342",
    "65.108.102.60:4132",
    "188.127.250.243:4132",
    "3.101.112.222:4132",
    "47.253.51.228:4132",
    "45.140.146.39:4132",
    "88.218.226.103:4132",
    "31.135.8.110:4132",
    "89.39.104.135:4132",
    "66.94.124.16:4132",
    "176.214.77.176:4132",
    "5.199.161.189:4132",
    "65.21.73.156:4132",
    "8.209.99.217:4132",
    "110.53.221.139:4132",
    "144.126.219.193:4132",
    "80.241.212.22:4132",
    "95.216.225.118:4132",
    "66.29.129.171:4132",
    "65.108.77.116:4132",
    "167.86.123.64:4132",
    "207.154.224.153:4132",
    "88.198.188.243:4132",
    "61.10.9.34:62226",
    "103.73.119.116:4132",
    "103.195.100.11:4132",
    "35.74.235.118:4132",
    "178.57.87.214:4132",
    "141.95.61.197:4132",
    "8.209.98.215:4132",
    "75.119.159.28:4132",
    "89.108.82.191:4132",
    "188.166.91.116:4132",
    "195.2.76.68:4132",
    "45.79.195.25:4132",
    "65.108.96.172:4132",
    "54.166.152.201:4132",
    "188.34.167.89:4132",
    "178.18.250.7:4132",
    "157.90.130.105:4132",
    "65.108.46.32:4132",
    "144.126.144.152:4132",
    "65.21.193.39:4132",
    "162.55.232.124:4132",
    "78.46.72.7:4132",
    "54.199.13.229:4132",
    "75.119.149.40:4132",
    "161.97.144.103:4132",
    "146.0.231.39:4132",
    "65.108.69.104:4132",
    "47.252.4.224:4132",
    "164.92.255.24:4132",
    "142.132.139.54:4132",
    "183.129.161.10:4132",
    "31.135.8.89:4132",
    "103.39.230.54:20020",
    "185.230.143.238:4132",
    "65.108.45.181:4132",
    "31.131.254.31:4132",
    "193.34.217.151:4132",
    "178.20.43.41:4132",
    "119.147.211.233:30021",
    "180.119.121.235:4132",
    "144.126.132.1:4132",
    "135.181.218.95:4132",
    "136.243.48.189:4132",
    "115.58.248.162:4132",
    "34.90.246.142:4132",
    "31.135.8.115:4132",
    "134.195.196.46:4132",
    "122.4.236.106:4132",
    "8.209.96.107:4132",
    "49.48.53.225:4132",
    "31.131.254.33:4132",
    "158.51.121.166:4132",
    "95.214.55.2:4132",
    "65.108.8.122:4132",
    "38.107.226.12:4132",
    "146.0.232.15:4132",
    "51.222.240.138:4132",
    "208.68.37.148:4132",
    "194.242.56.44:4132",
    "89.248.192.152:4132",
    "135.125.4.7:4132",
    "38.17.50.2:4132"
  ],
  "connected_peers": [
    "61.173.37.223:4132",
    "121.15.197.237:4132",
    "95.181.153.195:4132",
    "185.191.127.145:4132",
    "65.108.104.58:4132",
    "67.227.130.43:4132",
    "8.209.98.148:4132",
    "157.90.130.43:4132",
    "67.227.130.61:4132",
    "118.193.103.172:4132",
    "178.208.95.9:4132",
    "36.189.234.237:20000",
    "95.214.55.88:4132",
    "206.189.44.102:4132",
    "31.222.238.3:4132",
    "134.249.187.129:4132",
    "89.108.109.231:4132",
    "121.52.246.85:20003",
    "35.204.209.130:4132"
  ],
  "latest_block_hash": "ab1sjhcx895fkpufqy3g9xftxh67g9ynumffj9hyw3pfpemqqq3dgqsut0yed",
  "latest_block_height": 49728,
  "latest_cumulative_weight": 1477821840,
  "number_of_candidate_peers": 656,
  "number_of_connected_peers": 19,
  "number_of_connected_sync_nodes": 0,
  "software": "snarkOS 2.0.0",
  "status": "Syncing",
  "type": "Miner",
  "version": 11
}
"number_of_connected_peers": 19，"latest_block_height": 49728, fully synced

**Comment by howardwu** [comment]
Closing as this is not a snarkOS technical issue. I suggest reading up on how mining generally works.
