### ISSUE TITLE
[Bug] the mining_pool branch fails to compile with a futures-related error

### ISSUE THREAD

**Issue by StrangeTcy** [AleoHQ/snarkOS#1446]
## 🐛 Bug Report
```
error: failed to compile `snarkos v2.0.0 

Caused by:
  failed to select a version for the requirement `futures = "^0.3.18"`
````

## Steps to Reproduce

1. Clone the snarkOS repo
2. Checkout the feat/mining_pool branch
3. run `testnet2_ubuntu.sh` or just `cargo install --path .`

## Expected Behavior
It should either compile or suggest using some other version of the futures would be my best guess.

## Your Environment

-  snarkos v 2.0.0
-   1.57
-  Ubuntu 20.04

**Comment by ljedrz** [comment]
This was fixed with https://github.com/AleoHQ/snarkOS/pull/1440 in `testnet2`.

**Comment by ljedrz** [comment]
The `feat/mining_pool` branch is not ready yet and will eventually get rebased and get that fix from `testnet2`.
