### ISSUE TITLE
[Feature] add subcommand to get mining status

### ISSUE THREAD

**Issue by xander988** [AleoHQ/snarkOS#1471]
## 🚀 Feature

add subcommands to get mining status like peers, height, connection  status ...

## Motivation

in our mining machine, we prefer  to use the command directly instead  of rpc call.

## Implementation

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

i will open a pull request later  if its ok to add this feat

**Comment by ljedrz** [comment]
There's already a mining status command that will be fixed with https://github.com/AleoHQ/snarkOS/pull/1656; the rest can already be obtained via RPC.

Please feel free to reopen the PR if there's some piece of information not available yet.
