### ISSUE TITLE
[Bug] error: could not compile `snarkvm-curves`

### ISSUE THREAD

**Issue by SametBasturkk** [AleoHQ/snarkOS#1498]
## 🐛 Bug Report

   Compiling snarkvm-curves v0.7.5 (https://github.com/AleoHQ/snarkVM.git?rev=d3ae7e6#d3ae7e61)
error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> /root/.cargo/git/checkouts/snarkvm-f1160780ffe17de8/d3ae7e6/curves/src/bls12_377/mod.rs:17:28
   |
17 | #![cfg_attr(nightly, doc = include_str!("../../documentation/the_aleo_curves/02_bls12-377.md"))]
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> /root/.cargo/git/checkouts/snarkvm-f1160780ffe17de8/d3ae7e6/curves/src/bw6_761/mod.rs:17:28
   |
17 | #![cfg_attr(nightly, doc = include_str!("../../documentation/the_aleo_curves/04_bw6-761.md"))]
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> /root/.cargo/git/checkouts/snarkvm-f1160780ffe17de8/d3ae7e6/curves/src/edwards_bls12/mod.rs:17:28
   |
17 | #![cfg_attr(nightly, doc = include_str!("../../documentation/the_aleo_curves/01_edwards_bls12.md"))]
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> /root/.cargo/git/checkouts/snarkvm-f1160780ffe17de8/d3ae7e6/curves/src/edwards_bw6/mod.rs:17:28
   |
17 | #![cfg_attr(nightly, doc = include_str!("../../documentation/the_aleo_curves/03_edwards_bw6.md"))]
   |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `snarkvm-curves`

## Steps to Reproduce

1. Step 1...
2. Step 2...
3. Step 3...

## Expected Behavior

(Write what you expected to happen here)

## Your Environment

- 
- 
- 
ubuntu

![Screenshot from 2021-12-23 20-12-20](https://user-images.githubusercontent.com/8701394/147272726-4c1a9902-c941-43fa-88bf-90d678d71df5.png)

**Comment by coolagrwal** [comment]
kindly resolve or provide workaround for this issue
