### ISSUE TITLE
[Bug] Failed to start the node: io error: unexpected end of file', src/main.rs:64:28

### ISSUE THREAD

**Issue by meetrick** [AleoHQ/snarkOS#1503]
## 🐛 Bug Report

```log
2021-12-26T18:26:20.420644Z DEBUG Validating the ledger up to block 86085 (97%)
2021-12-26T18:26:21.423261Z DEBUG Validating the ledger up to block 87086 (98%)
thread 'main' panicked at 'Failed to start the node: io error: unexpected end of file', src/main.rs:64:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Finished release [optimized] target(s) in 0.08s
     Running `target/release/snarkos --miner aleo1h5ly5qnndj3x8wyhc402w6ausnrx7z7nm4lahwuewyg79naf4yyqhuyhln --trial --verbosity 2`
```
![image](https://user-images.githubusercontent.com/19239345/147419398-7e286267-24df-401f-9c37-701e83f92796.png)

## Steps to Reproduce

1. It just node restart only

## Expected Behavior

Node will restart normally.
My Aleo node are worked more than 3weeks.
But suddenly It entered kernel panic.

## Your Environment

-  Aleo version 11
- rustc 1.56.1 (59eed8a2a 2021-11-01)
-  Ubuntu 20.xx

**Comment by alextop** [comment]
I had the same but my node wasn't restarted properly, I had to call `snarkos clean` and start sync from scratch.
The error on node restart was:
```thread 'main' panicked at 'Failed to start the node: io error: unexpected end of file', src/main.rs:64:28```

**Comment by meetrick** [comment]
> I had the same but my node wasn't restarted properly, I had to call `snarkos clean` and start sync from scratch. The error on node restart was: `thread 'main' panicked at 'Failed to start the node: io error: unexpected end of file', src/main.rs:64:28`

It just only solution for this problem?

**Comment by ljedrz** [comment]
If your node had been working without restarts for 3 weeks, you might have missed some of the recent fixes that guard it against db corruption. Hopefully you won't get this issue again - just be sure to update your testnet2 branch.

**Comment by meetrick** [comment]
> If your node had been working without restarts for 3 weeks, you might have missed some of the recent fixes that guard it against db corruption. Hopefully you won't get this issue again - just be sure to update your testnet2 branch.

Thanks reply. But my node restart every 10hour BTW.

**Comment by vasrox** [comment]
It was same problem, had to remove ledger and restart service.

**Comment by raychu86** [comment]
This issue seems to stem from a corrupted DB, the best solution is to clear the ledger (by removing the relevant `~/.aleo/storage/ledger-*` file) and restart the node.

**Comment by yasiryagi** [comment]
Same here, it work after deleting the ledger!
