### ISSUE TITLE
[Bug]SSL error: received early EOF; class=Ssl (16); code=Eof (-20)

### ISSUE THREAD

**Issue by AmIReady** [AleoHQ/snarkOS#1520]
Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  SSL error: received early EOF; class=Ssl (16); code=Eof (-20)

**Comment by howardwu** [comment]
Closing as this issue intermittently happens on crates.io's side. I suggest opening an issue on their Github if it persists.
