### ISSUE TITLE
When the operator is restarted the provers all have to be restarted also

### ISSUE THREAD

**Issue by xorinox** [AleoHQ/snarkOS#1521]
## 🐛 When the operator is restarted the provers all have to be restarted also.

When the operator is restarted the provers all have to be restarted also.

## Steps to Reproduce

Start an operator and proved that connects to the operator. Then restart the operator. Now the prover will sit in a loop reporting that it cannot a message to non-connected peer. It wont reconnect to the operator until restarted.

`2022-01-04T14:04:24.953457Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011`
`2022-01-04T14:04:25.170778Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011`
`2022-01-04T14:04:26.172272Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011`
`2022-01-04T14:04:27.173024Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011`
`2022-01-04T14:04:28.173802Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011`

## Expected Behavior

Prover can reconnect to operator, once latter becomes available again.

**Comment by zosorock** [comment]
@xorinox can you confirm you are still seeing this behavior? I believe PR #1531 fixed it.

**Comment by xorinox** [comment]
Yes this seems to work.
