### ISSUE TITLE
[Bug] Pool operator reports "could not deserialize block"

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkOS#1522]
There are still issues:

The operator reports `could not deserialize block` on `PoolResponse`.

It looks like when deserializing `BlockHeader`, there is another `is_valid` check (`snarkVM/dpc/src/block/header.rs`, line 375 -> 143 -> 230) so the operator will be unable to deserialize the header. We might need a `from_unchecked` for `BlockHeader` as well.

_Originally posted by @HarukaMa in https://github.com/AleoHQ/snarkOS/issues/1492#issuecomment-1000500810_

I guess this comment was ignored and I was using a modified snarkVM so I didn't think about this again.

The line numbers might be out of date but it should still be the deserialization from bytes process.

**Comment by xorinox** [comment]
network/peers.rs

I find this code much improved, so one has actually an idea what's going on if de-serialization fails.


                                Message::PoolRequest(share_difficulty, block_template) => {
                                    if E::NODE_TYPE != NodeType::Prover {
                                        trace!("Skipping 'PoolRequest' from {}", peer_ip);
                                    } else {
                                        match block_template.deserialize().await {
                                            Ok(block_template) => {
                                                if let Err(error) = prover_router.send(ProverRequest::PoolRequest(peer_ip, share_difficulty, block_template)).await {
                                                    warn!("[PoolRequest] {}", error);
                                                }
                                            }
                                            Err(error) => {
                                                warn!("[PoolRequest] could not deserialize block template from {}: {}", peer_ip, error);
                                            }
                                        }
                                    }
                                }
                                Message::PoolResponse(address, block_header) => {
                                    if E::NODE_TYPE != NodeType::Operator {
                                        trace!("Skipping 'PoolResponse' from {}", peer_ip);
                                    } else {
                                        match block_header.deserialize().await {
                                            Ok(block_header) => {
                                                if let Err(error) = operator_router.send(OperatorRequest::PoolResponse(peer_ip, block_header, address)).await {
                                                    warn!("[PoolResponse] {}", error);
                                                }
                                            }
                                            Err(error) => {
                                                warn!("[PoolResponse] could not deserialize block from {}: {}", peer_ip, error);
                                            }
                                        }
                                    }
                                }

**Comment by xorinox** [comment]
That said, the code now reports as the issue

`2022-01-04T16:06:38.772476Z  WARN [PoolResponse] could not deserialize block from 192.168.1.114:4006: Invalid block header`

I find it odd, to report an issue on de-serialization, when in fact the de-serialization worked, but a downstream check is_valid(), returned false.

**Comment by xbeastx** [comment]
Can confirm that we have same warning.

**Comment by howardwu** [comment]
#1527 should address the issue here
