### ISSUE TITLE
In prover mode, the node still syncs with ledger

### ISSUE THREAD

**Issue by xorinox** [AleoHQ/snarkOS#1523]
## 🐛 Bug Report

In prover mode, the node still syncs with ledger. Can you explain why? It doesn't seem to mine before  synchronized.

## Steps to Reproduce

Start an operator and connect a prover to it. The prover will still synchronize the ledger.

`2022-01-04T14:20:55.058228Z  INFO Prover successfully mined a share for unconfirmed block 122414 with proof difficulty of 17911401710125624605`
`2022-01-04T14:20:57.071668Z  INFO Prover successfully mined a share for unconfirmed block 122414 with proof difficulty of 5960236136753585787`
`2022-01-04T14:20:58.986271Z  INFO Prover successfully mined a share for unconfirmed block 122414 with proof difficulty of 17571565586786987224`
`2022-01-04T14:20:59.362113100+00:00...block height 122414 with weight 325839`
`2022-01-04T14:21:05.987481Z  INFO Ledger successfully advanced to block 122414 (ab1225jsentgeg764clmrh9yj2cp7ussm6s4n5l2q7v7z0c2r5ctczqj5v39f)`
`2022-01-04T14:21:06.161747Z  INFO Ledger successfully advanced to block 122415 (ab1vthjnh874rwedrmskegsvk3mn9n9jvwe8tcpycjr9f9u8m44jspszdenw0)`

## Expected Behavior

A prover does not need to keep the ledger up to date. It should only focus on mining.

**Comment by howardwu** [comment]
Keeping state is a necessary requirement on mainnet if:

1. if a prover wishes to be compensated for their work
2. if a prover wants to be able to detect a malicious miner (for example, not being paid for a won block)

It is desirable to preserve this even on testnet to:

1. minimize code change for mainnet, as these features are fairly large
2. you'd like to emulate realistic behavior for mainnet

**Comment by ljedrz** [comment]
Closing the issue, as this is expected behavior; please feel free to reopen if you'd like to present some new arguments for changing the current design.
