### ISSUE TITLE
[Proposal] Provers should not depend on the ledger to work

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkOS#1524]
## 💥 Proposal

Currently the prover nodes still need a fully synced ledger to start working on proofs, however this should not be needed - all required info are handed over by the operator in `PoolRequest` message and the prover just need to generate proofs.

A initial sync takes a long time to do, and the legder validation at the start of the prover is essentially wasted as well.

A prover shouldn't participate in the network as a normal node IMO as it's meant to be a prover only, handling network consensus only slows down the proving work.

**Comment by HarukaMa** [comment]
This should be the same as #1523.

**Comment by howardwu** [comment]
Duplicates #1523

Closing
