### ISSUE TITLE
Operator node should run with same thread settings as sync node

### ISSUE THREAD

**Issue by xorinox** [AleoHQ/snarkOS#1526]
In main.rs of snarkOS, I think the operator node should be configured the same as sync node?

    let (num_tokio_worker_threads, max_tokio_blocking_threads) = if !node.sync {
        ((num_cpus::get() / 8 * 2).max(1), num_cpus::get())
    } else {
        (num_cpus::get(), 512) // 512 is tokio's current default
    };

    // Initialize the runtime configuration.
    let runtime = runtime::Builder::new_multi_thread()
        .enable_all()
        .thread_stack_size(8 * 1024 * 1024)
        .worker_threads(num_tokio_worker_threads)
        .max_blocking_threads(max_tokio_blocking_threads)
        .build()?;

    let num_rayon_cores_global = if !node.sync {
        (num_cpus::get() / 8 * 5).max(1)
    } else {
        num_cpus::get()
    };

**Comment by howardwu** [comment]
Closing as the thread pool that the operator needs to have scale is not the global thread pool.

**Comment by xorinox** [comment]
> Closing as the thread pool that the operator needs to have scale is not the global thread pool.

Can you provide which threadpool instead that is? My operator runs a lot smoother using the same threadpool settings as a sync node.
