### ISSUE TITLE
Hidden danger after message:: poolresponse is modified [Bug]

### ISSUE THREAD

**Issue by kaola526** [AleoHQ/snarkOS#1540]
If the prover uses an old version, it will cause memory problems in the operator

`13 => Self::PoolResponse(bincode::deserialize(&data[0..32])?, Data::Buffer(data[32..].to_vec()))`
modified
`13 => Self::PoolResponse(
                bincode::deserialize(&data[0..32])?,
                bincode::deserialize(&data[32..64])?,
                Data::Buffer(data[64..].to_vec()),
            ),`

**Comment by ljedrz** [comment]
This might be causing https://github.com/AleoHQ/snarkOS/issues/1534.

**Comment by HarukaMa** [comment]
... and now I can almost reliably crash the operator using a specifically structured message.

**Comment by HarukaMa** [comment]
PR: https://github.com/AleoHQ/snarkVM/pull/592

**Comment by ljedrz** [comment]
Closing, as client with an older version are rejected during the handshake and due to the memory problem already being covered by another issue.
