### ISSUE TITLE
[Bug] thread 'main' panicked at 'Failed to start the node: Loaded a ledger with inconsistent state (120669 != 120670) (unable to automatically resolve)', src/main.rs:64:28

### ISSUE THREAD

**Issue by ruscomm** [AleoHQ/snarkOS#1550]
## Steps to Reproduce

./run-miner.sh

## Your Environment

-  2.0
-  1.57.0 
-  ubuntu 20.04

**Comment by ljedrz** [comment]
https://github.com/AleoHQ/snarkOS/pull/1542 should put an end to these.

**Comment by ljedrz** [comment]
Until https://github.com/AleoHQ/snarkOS/pull/1542 is in, run `snarkos clean` and then download and unpack the official ledger snapshot in your home folder: https://aleo-testnet2-ledger.fra1.cdn.digitaloceanspaces.com/snapshot.tar.gz.

**Comment by ljedrz** [comment]
Closed by https://github.com/AleoHQ/snarkOS/pull/1542 (merged as part of https://github.com/AleoHQ/snarkOS/pull/1639) in testnet3.
