### ISSUE TITLE
[Bug] Prover does not mine with cuda feature enable

### ISSUE THREAD

**Issue by zosorock** [AleoHQ/snarkOS#1555]
## 🐛 Bug Report

When running as prover, the node never goes into the `Mining` state.

## Steps to Reproduce
Compile `feat/expose-cuda` and join the official beta mining pool.

## Expected Behavior
Miner should go into `state = Mining` every so often and submit proofs to the Operator.

## Your Environment
Ubuntu 20.04 LTS
Nvidia A100

**Comment by ljedrz** [comment]
Closing, as the issue references an old implementation.
