### ISSUE TITLE
[Proposal]Solution for the top 100 places in the test network to be controlled by one team

### ISSUE THREAD

**Issue by bananooo-zhang** [AleoHQ/snarkOS#1560]
## 💥 Proposal

It's already clear that there's some team occupying a top 100 spot right now.
And I think the aleo team is having a hard time catching these people right now because they can turn on firewalls for miners and mining pools to not be accessible to the public and then go through a few client nodes to broadcast the data.
So I offer a solution
The first step is to immediately turn on the registration system and allow only registered members to participate in this test network. The registration form has two required fields, the name used as kyc, and the participating wallet.
Step 2, work on kyc for the first 200 people. And require video interviews, video interviews will be technically oriented, the same as mina had done, this effect is the best, no one.
The third step, after completing 200 people kyc interview, snapshot the current ranking, and then if a new wallet is found to produce five 10 blocks or more in a day, then a one-on-one video interview will be conducted within three days.

To be honest, I really need the aleo team to get me back on message about aleo, I love aleo, made my own videos and am promoting it to my community, but there are so many issues at the moment.

I think it's a very negative move to let it go like this, even if the aleo team eventually sends out a public saying that the first 100 people are normal, but will the community members believe it? 6p/s or so of arithmetic power to theoretically produce a block a day, and that 6ps of arithmetic power requires about 15 7282x2 machines to reach, and those 15 machines need 300$ a month each There is too much evidence in the discord for everyone to see.

I have no objection to rewarding the geek, even if he alone mines 99 percent of the blocks, which is his ability, and those of us who can go for the rest of the blocks. But now all changed, he not only wants top5, even top100 he all want, which touches everyone's interests.

So please team seriously consider this proposal, this proposal has no burden for the normal participating players and it is great protection for them. The only thing that hurts is the people who break the rules.

**Comment by Markgpnc** [comment]
I couldn't agree with you more.👍 While the world of blockchain is free, these measures are necessary to implement if a harmonious and stable blockchain environment is to be created.

**Comment by d4mk0** [comment]
![image](https://user-images.githubusercontent.com/4139198/149636794-ace4147b-b532-47c5-9d82-ddda80d8990f.png)

**Comment by Baimu** [comment]
I agree with you that if there is no fair competition, we will lose our meaning here

**Comment by slon36** [comment]
**Agree +1**  

MINA was the best testnet experience!!!
And there was everything very clear for the community.

_Please VOTE: ThumbUP or ThumbDown_

**Comment by AlexeyGas1979** [comment]
It will be adequate if the project team at least somehow marks and rewards the nodes without mined blocks. These nodes participated in the project, people helped the project, although not as actively as those who have access to super-powerful GPUs.

**Comment by herralexandro** [comment]
I completely agree. Testers with 32+ core servers cannot mine even one block. With the current state of affairs, 90% of testers will be left without rewards. It's not fair.

**Comment by donihellatrigger** [comment]
_I fully agree with all the above statements and complaints._

**It would be fair to give testers at least a priority, not a guaranteed allocation of course, but a priority. Because after all, this team did not take into account the factors that led to the disappointment that many are experiencing. I'm not talking about the guys who have been driving all the server power for several months without results.**

**Comment by ljedrz** [comment]
Closing, as this doesn't seem to be applicable to the current testnet.
