### ISSUE TITLE
ERROR: Miner Loaded a Ledger with inconsistant state

### ISSUE THREAD

**Issue by ChrisLivermore** [AleoHQ/snarkOS#1563]
thread 'main' panicked at 'Failed to start the node: Loaded a ledger with inconsistent state (162844 != 162845) (unable to automatically resolve)', src/main.rs:64:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

First run but have been using previously with : https://nodes.guru/aleo/setup-guide/en Guide(which also no longer works (just loads up with no connection/info)

wget -O snarkos_monitor.sh https://api.nodes.guru/snarkos_monitor.sh && chmod +x snarkos_monitor.sh && ./snarkos_monitor.sh Produces:

Aleo.org TESTNET2 monitoring for:	localhost:3032

-----------------------------------------------
CONNECTED PEERS:

LATEST BLOCK HEIGHT:	-----------------------------------------------

NODE STATE:	-----------------------------------------------

ANy Help with this would be appreciated, I followed all the guide as described and ports are Open.

**Comment by ljedrz** [comment]
Thanks for the report! It's already tracked under https://github.com/AleoHQ/snarkOS/issues/1550.
