### ISSUE TITLE
Disable or limit the check whether the prover listener port is open

### ISSUE THREAD

**Issue by winlin** [AleoHQ/snarkOS#1574]
## 💥 disable or limit the check whether the prover listen port

We run prover in home network, and the `operator` just disconnect the `prover` because we can not set the NAT or port forwarding in our router. As the help from @HarukaMa, we disable the check for port in `operator` and `prover`. Indeed, it not easy to do the NAT and port forwarding in home network, so we suggest disable the check for `prover`.

**Comment by ljedrz** [comment]
In addition to this, there used to be [a proposal to use UPnP for automatic port forwarding for testnet1](https://github.com/AleoHQ/snarkOS/pull/1218). I'll try to revive it for testnet2 shortly.

**Comment by ljedrz** [comment]
I just filed https://github.com/AleoHQ/snarkOS/pull/1575 that should aid port forwarding with UPnP-enabled routers.

**Comment by winlin** [comment]
ok, it should be an option logic, not default logic

**Comment by wanyvic** [comment]
https://github.com/AleoHQ/snarkOS/blob/506fcbf33d555a528efcec6c0fc1fe5c21902f22/src/network/peer.rs#L234-L248
Consider whether to delete this lines?
I run node behind NAT in home. ISP give me a LAN IP (such as 10.0.0.1).
My node listens `0.0.0.0:4132`. but remote is `x.x.x.x:9157`. It can not be connected successfully with this lines. but I'm not sure if it will have some ploblem.

**Comment by ljedrz** [comment]
@wanyvic while this suggestion is being considered, have you tried the workaround described [here](https://github.com/AleoHQ/snarkOS/issues/1574#issuecomment-1015430278)?

**Comment by wanyvic** [comment]
I had tried https://github.com/AleoHQ/snarkOS/pull/1575, The problem still exists.

**Comment by wanyvic** [comment]
+------------------------------------------------------------------------------------------------------------+   
        |                                                                                                            |   
        |                                                                                                            |   
        |              public IP 113.30.25.32                                                                        |   
        |      +----------------------------------------------+                                                      |   
        |      |                                              |                                                      |   
        |      |             ISP NAT                          |                                                      |   
        |      |                                              |                                                      |   
        |      |     +------------------------------+         |                                                      |   
        |      |     |       my home router         |         |                                                      |   
        |      |     |                              |         |                                                      |   
        |      |     |       WAN IP: 10.25.25.2     |         |                                                      |   
        |      |     |                              |         |                                                      |   
        |      |     |      +--------------+        |         |                                  +----------------+  |   
        |      |     |      |   my peer    |        |         |                                  |                |  |   
        |      |     |      |              |        |         |                                  |                |  |   
        |      |     |      |  192.168.1.2 |4132--------4132 -----9165                           |   other peer   |  |   
        |      |     |      |              |        |         |extern: 113.30.25.32:9165    4132 |                |  |   
        |      |     |      +--------------+        |         |--------------------------------- |                |  |   
        |      |     +------------------------------+         |                                  |                |  |   
        |      +----------------------------------------------+                                  +----------------+  |   
        |                                                                                                            |   
        +------------------------------------------------------------------------------------------------------------+   
Here is my network topology.
So I can not receive `ChallengeResponse-A`

**Comment by ljedrz** [comment]
This check is currently disabled, so closing the issue.
