### ISSUE TITLE
[Bug] password should be passed from a file

### ISSUE THREAD

**Issue by happysalada** [AleoHQ/snarkOS#1583]
## 🐛 Bug Report

The password is read from a value in the config or command line, it should be read from a file. This way you can pass it to a systemd service from load credentials or to docker from docker secrets. (usually secrets should be read from files).

I would be happy to make a Proposal PR if you are open to the change.

(I filed it as a bug because this is potentially a security risk, let me know if you want to classify it differently)

**Comment by ljedrz** [comment]
Which password do you have in mind? The RPC one?

**Comment by happysalada** [comment]
yes

**Comment by ljedrz** [comment]
I don't think there are even private calls in testnet2 right now, so you don't need to use a password. In addition, I wonder if instead in the end we shouldn't provide an option to allow only the specified sources to access RPC, instead of requiring credentials for the private calls.

**Comment by happysalada** [comment]
it would make sense.
I was trying to make a systemd service for running a node to contribute to nixos. Passing secrets in the cli is a big no-no there, so happy to have another solution. I don't mind either way personally.

**Comment by howardwu** [comment]
Closing as this feature is now supported.
