### ISSUE TITLE
[Bug] The operator sends PoolRequest to the provers that were not registered with that operator

### ISSUE THREAD

**Issue by alextop** [AleoHQ/snarkOS#1638]
## 🐛 Bug Report
The prover was started with the `--pool 65.108.104.9:4132` parameter and successfully connected to the operator.
```Feb 16 00:08:30 root1822 snarkos[3879945]: 2022-02-15T23:08:30.475764Z  INFO Connected to 65.108.104.9:4132```

Despite that, the log contains many `PoolRequest` messages from other operators, e.g.:

```
Feb 16 00:10:55 root1822 snarkos[3879945]: 2022-02-15T23:10:55.352533Z TRACE Received 'PoolRequest' from 194.163.163.22:4132
Feb 16 00:10:55 root1822 snarkos[3879945]: 2022-02-15T23:10:55.352577Z TRACE Received 'PoolRequest' from 185.130.226.134:4132
```
Those operators have the host IP or the prover in the `connected_peers` list (and vice versa).

## Steps to Reproduce
Examine the log of any prover.

## Expected Behavior
The operator should not send `PoolRequest` to all of its connected peers but only to those that were registered with that operator.

## Your Environment

- snarkos 2.0.2
- rustc 1.58.1 (db9d1b20b 2022-01-20)
- Ubuntu 20.04
- AMD Ryzen 3900x, 64GB RAM, 2*1TB NVMe Raid 0
- 1GBPs network

**Comment by HarukaMa** [comment]
I don't think official snarkOS does this; most probably those operators are using my modified code.

I'm deprecating that kind of usage right now so hopefully it won't be an issue in the future.

**Comment by ljedrz** [comment]
Not applicable to testnet3.
