### ISSUE TITLE
[HELP] Failed to start the node

### ISSUE THREAD

**Issue by Destore2023** [AleoHQ/snarkOS#1666]
## 🐛 Bug Report

when I follow the instruction 3a. Run an Aleo Client Node, the system show me below:

rm: remove write-protected regular file 'Cargo.lock'? error: failed to open: /home/cru/snarkOS/target/release/.cargo-lock

Caused by:
  Permission denied (os error 13)

the system stop running untill ctrl+c show me 

./run-client.sh: line 16: kill: (30062) - No such process

can any one show me how to fix it? Thanks

## Steps to Reproduce

1. Step 1... ./build_ubuntu.sh  success
2. Step 2... ./run-client.sh        **fail**
3. Step 3... ./run-client.sh: line 16: kill: (30062) - No such process

## Expected Behavior

(when I follow the instruction 3a. Run an Aleo Client Node, system me "rm: remove write-protected regular file 'Cargo.lock'? error: failed to open: /home/cru/snarkOS/target/release/.cargo-lock

Caused by:
  Permission denied (os error 13)
" )

## Your Environment

- narkOS Version lastest
- Rust Version lastest
- Computer OS Distributor ID: Ubuntu  Description:    Ubuntu 20.04.4 LTS  Release:        20.04  Codename:       focal

**Comment by Destore2023** [comment]
I solve it, please close this issue, Thanks Admin~

**Comment by NaokiLH** [comment]
> I solve it, please close this issue, Thanks Admin~

Can you tell me how to solve it? I meet this problem too
