### ISSUE TITLE
why my snarkos time is wrong

### ISSUE THREAD

**Issue by luhui5** [AleoHQ/snarkOS#1701]
## 👉 [Please follow one of these issue templates](https://github.com/AleoHQ/snarkOS/issues/new/choose) 👈

![image](https://user-images.githubusercontent.com/44595912/159653578-4b7361bf-11d9-4595-b77e-06c2d6bde683.png)

**Comment by ljedrz** [comment]
Note that the snarkOS timestamps end with the `Z` suffix, indicating that they are in UTC. This is not an error.

**Comment by ljedrz** [comment]
To expand on this, it's useful to have everyone's logs in the same timezone in order to be able to correlate any potential issues more easily etc.
