### ISSUE TITLE
aleo test2 already over, I want test my server Computational power, What should I do? Thanks

### ISSUE THREAD

**Issue by tmzxi** [AleoHQ/snarkOS#1743]
I want to test my server's computational power. What should I do?

**Comment by goodbabynow** [comment]
You can continue to run the test in the testnet2 environment. His testnet is open, but there is no point reward.

**Comment by tmzxi** [comment]
&nbsp; &nbsp; &nbsp; &nbsp; Thanks！
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;I run the test in the testnet2 environment，I want How to show computing power or HashRate？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AleoHQ/snarkOS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 晚上6:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AleoHQ/snarkOS] aleo test2 already over, I want test my server Computational power, What should I do? Thanks (Issue #1743)





 
You can continue to run the test in the testnet2 environment. His testnet is open, but there is no point reward.

**Comment by ljedrz** [comment]
Closing, as https://github.com/AleoHQ/snarkOS/issues/2132 is now tracking this matter.
