### ISSUE TITLE
[Bug]Failed to start the node: IO error: While lock file: /home/work/.aleo/storage/ledger-2/LOCK: Resource temporarily unavailable', snarkos/main.rs:56:28

### ISSUE THREAD

**Issue by kimtony** [AleoHQ/snarkOS#1781]
## 🐛 Bug Report

run operator and miner  at the same time  on the server  has err
![image](https://user-images.githubusercontent.com/34413109/171080937-aa6572aa-65ba-41f8-abb1-f5fefdcb46c9.png)

## Steps to Reproduce

1. snarkos --operator 'aleoaddr' --trial --verbosity 2  --node 0.0.0.0:4135 --rpc 0.0.0.0:3035 
2. snarkos --miner 'aleoaddr' --trial --verbosity 2  --node 0.0.0.0:4136 --rpc 0.0.0.0:3032

## Expected Behavior

Excuse me, can the operator and the miner run at the same time, does the miner also need to do the corresponding synchronization, and how is the block log reflected?

## Your Environment

- 
How to check snarkos version？
- 
rustc 1.59.0 (9d1b2106e 2022-02-23)
- 
Linux version 5.15.0-33-generic (buildd@lcy02-amd64-037) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38)

**Comment by ljedrz** [comment]
This is the `testnet2` branch, correct? It's fixed in `testnet3`.

**Comment by kimtony** [comment]
> This is the `testnet2` branch, correct? It's fixed in `testnet3`.

i run this branch 'testnet3 3bace88'

the operator and the miner run at the same time has this bug

**Comment by ljedrz** [comment]
Oh, I missed the fact that the operator and miner were running at the same time (thought it was just https://github.com/AleoHQ/snarkOS/issues/1354 at first); I don't think those two should be running at the same time, as they would attempt to share databases if they are running on the same network.

It's likely undesirable to run those 2 node types at the same time; you'd rather want an operator and a prover.

**Comment by ljedrz** [comment]
I'm applying the `unconfirmed` label, as I'm not sure if we want to support it. Feel free to propose it (the possibility to run both these nodes) in [aleo-std](https://github.com/AleoHQ/aleo-std) if you feel that it's needed.

**Comment by kimtony** [comment]
@ljedrz Thanks for the reply, I am now running in the mode of operator + prover and can generate blocks

**Comment by ljedrz** [comment]
Not applicable to testnet3, at least not in this shape.
