### ISSUE TITLE
when is testnet3 start？

### ISSUE THREAD

**Issue by feiyiban** [AleoHQ/snarkOS#1810]
When will testnet3 start and how to participate

**Comment by goodbabynow** [comment]
june

**Comment by feiyiban** [comment]
windows can‘t work well

**Comment by goodbabynow** [comment]
> windows can‘t work well

u need use ubentu or centos,don't use win

**Comment by ljedrz** [comment]
You can build on Windows, it's just more difficult and currently not documented (https://github.com/AleoHQ/snarkOS/issues/1620).

**Comment by goodbabynow** [comment]
> 您可以在 Windows 上构建，只是更困难，目前没有记录（#1620）。

When run-client.sh is compiled under windows, an error will be reported near 345, and the compilation cannot be successful.

**Comment by ljedrz** [comment]
The `sh` script (and the rest of the installation instructions) are for Unix-like systems, not Windows.

**Comment by chuanliangyan** [comment]
同问

**Comment by mlsmith** [comment]
`testnet3` phase one started today.  The announcement and how to participate is on twitter:
https://twitter.com/AleoHQ/status/1561745029584011264
