### ISSUE TITLE
[Bug]run-client.sh is compiled in the windows10 environment, and the operation will stop at librocksdb-sys v0.6.1+6.28.2

### ISSUE THREAD

**Issue by goodbabynow** [AleoHQ/snarkOS#1819]
## 🐛 Bug Report
run-client.sh is compiled in the windows10 environment, and the operation will stop at librocksdb-sys v0.6.1+6.28.2, tried many times

-------------------------error message------------------------------------------

   Compiling librocksdb-sys v0.6.1+6.28.2
error: failed to run custom build command for `librocksdb-sys v0.6.1+6.28.2`

Caused by:
  process didn't exit successfully: `C:\Users\aleo\snarkOS\target\release\build\librocksdb-sys-d7349eb0b0d8a32c\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\aleo\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.59.2\src/lib.rs:2144:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by ljedrz** [comment]
The error states the issue: `Unable to find libclang`; you need to have LLVM installed in order to conclude compilation.

Cc https://github.com/AleoHQ/snarkOS/issues/1620
