### ISSUE TITLE
can GPU run  the Aleo snarkOS?and how about the effect?

### ISSUE THREAD

**Issue by chuanliangyan** [AleoHQ/snarkOS#1825]
## 💥 Proposal

(Write your proposal here)

**Comment by goodbabynow** [comment]
没数据，要等testnet3，但是不支持AMD显卡。从代码来看完善度也不高。不建议豪赌。如果数据一般，那你就赔惨了。因为显卡跌价速度过快，ETH年底合并成POS会彻底抛弃显卡计算。

**Comment by chuanliangyan** [comment]
收到，谢谢。😁

fenderman ***@***.***> 于2022年7月8日周五 10:02写道：

**Comment by ljedrz** [comment]
Closing as inactive; as far as I'm aware, there are still plans to release a CUDA implementation.
