### ISSUE TITLE
[Bug] the coinbase_transaction in not included in `get_block_template` rpc

### ISSUE THREAD

**Issue by DogLi** [AleoHQ/snarkOS#1827]
## 🐛 Bug Report
the block template in `get_block_template` RPC response is different from the one in the operator, which is updated [here](https://github.com/AleoHQ/snarkOS/blob/testnet3/network/src/operator.rs#L126).
in the rpc block template,  coinbase transaction is not included, and I see the coinbase transaction comes from [here](https://github.com/AleoHQ/snarkOS/blob/testnet3/storage/src/state/ledger.rs#L491). But in my test, it will use 15 to 25 seconds(at least more than 10 seconds) to calculate the coinbase transaction. I don't know if it is the reason that the coinbase transaction is not included.

the problem is:
1. if I use the block template (without transaction) to mine, will the coinbase get the reward without coinbase transaction?
2. if add the coinbase transaction, it takes a long time to update the new template, the miner will always mine the old block before the update get ready(in the operator),  and I think this is the reason in issue #1472

**Comment by ljedrz** [comment]
This issue is no longer applicable to testnet3. If you believe otherwise, please feel free to reopen.
