### ISSUE TITLE
when I test aleo,  How to show computing power or HashRate？

### ISSUE THREAD

**Issue by tangmizhong** [AleoHQ/snarkOS#1839]
## 👉 [Please follow one of these issue templates](https://github.com/AleoHQ/snarkOS/issues/new/choose) 👈

Note: to keep the backlog clean and actionable, issues may be immediately closed if they do not follow one of the above issue templates.

**Comment by ljedrz** [comment]
Closing in favor of https://github.com/AleoHQ/snarkOS/issues/2132.
