### ISSUE TITLE
Block synchronization is abnormal. Procedure

### ISSUE THREAD

**Issue by johnnychen8188** [AleoHQ/snarkOS#1887]
2022-08-23T03:34:41.760988Z  INFO Synced up to block 7035 of 13837 - 50% complete (est. 19 minutes remaining)
2022-08-23T03:34:41.761017Z TRACE Requesting block 7135 of 13837
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid block version', /root/snarkOS/snarkos/ledger/mod.rs:255:81
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(1600), ...)', /root/snarkOS/snarkos/ledger/mod.rs:276:22

snarkOS Version: v2.0.2
system Version:ubuntu-20.04.1

**Comment by HarukaMa** [comment]
dup #1873

**Comment by johnnychen8188** [comment]
> 重复#1873

I found the problem that reboot can be synchronized, which has been solved, thank you
