### ISSUE TITLE
[Feature] Provide private key from config file

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkOS#1888]
## 🚀 Feature

Read private key (preferably also rpc username / password) from config file instead of command line. 

## Motivation

Currently it seems the only way to provide private key to the snarkOS is through the command line option. However this is considered a very bad practice - everyone can just `ps` to get the private key, plus the private key will be left in the shell's command history unless you suppress that behavior with prepended spaces.

Environment variables are also acceptable IMO as all modern OSes should have `/proc/<pid>/environ` protected, and if we use `.env` the injected new env variables won't even be visible in the `environ` file.

## Implementation

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Currently busy with other projects, so probably not.

**Comment by beck-8** [comment]
looks good

**Comment by ljedrz** [comment]
That's the plan AFAIK :+1:.

**Comment by HarukaMa** [comment]
Looks like the phase 2 is coming soon but this is still not implemented. Leaving the private key in the cmdline is really insecure, so I'd suggest implementing this before starting the phase 2.

(There is also a PR element in this IMO.)

**Comment by howardwu** [comment]
Closing as this issue has been resolved.

Private keys can now be provided via a file.
