### ISSUE TITLE
The public key address will be different after the restart

### ISSUE THREAD

**Issue by johnnychen8188** [AleoHQ/snarkOS#1889]
Why does a new wallet address appear every time you reboot?

snarkOS Version: v2.0.2
system Version:ubuntu-20.04.1

**Comment by beck-8** [comment]
https://github.com/AleoHQ/snarkOS/blob/96db82859d9bd1a12c7b6a67d5b98baf17ce21ba/snarkos/cli.rs#L131
It is because you did not specify the private key
This is not a problem, please close issues

**Comment by johnnychen8188** [comment]
ok
