### ISSUE TITLE
[Bug]  stuck happens on 2.72%

### ISSUE THREAD

**Issue by goodbenya** [AleoHQ/snarkOS#1906]
## 🐛 Bug Report

**My output**

root@vm610352:~/snarkOS# ./run-client.sh 
Running client node...
Checking for updates...
Saved working directory and index state WIP on testnet3: f8c0d95 Merge pull request #1884 from ljedrz/post_dev_tweaks
    Updating crates.io index
    Updating git repository `https://github.com/AleoHQ/snarkVM.git`
   Compiling snarkos v2.0.2 (/root/snarkOS)
    Finished release [optimized] target(s) in 1m 02s
     Running `target/release/snarkos --verbosity 2`

         ╦╬╬╬╬╬╦
        ╬╬╬╬╬╬╬╬╬                    ▄▄▄▄        ▄▄▄
       ╬╬╬╬╬╬╬╬╬╬╬                  ▐▓▓▓▓▌       ▓▓▓
      ╬╬╬╬╬╬╬╬╬╬╬╬╬                ▐▓▓▓▓▓▓▌      ▓▓▓     ▄▄▄▄▄▄       ▄▄▄▄▄▄
     ╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬              ▐▓▓▓  ▓▓▓▌     ▓▓▓   ▄▓▓▀▀▀▀▓▓▄   ▐▓▓▓▓▓▓▓▓▌
    ╬╬╬╬╬╬╬╜ ╙╬╬╬╬╬╬╬            ▐▓▓▓▌  ▐▓▓▓▌    ▓▓▓  ▐▓▓▓▄▄▄▄▓▓▓▌ ▐▓▓▓    ▓▓▓▌
   ╬╬╬╬╬╬╣     ╠╬╬╬╬╬╬           █▓▓▓▓▓▓▓▓▓▓█    ▓▓▓  ▐▓▓▀▀▀▀▀▀▀▀▘ ▐▓▓▓    ▓▓▓▌
  ╬╬╬╬╬╬╣       ╠╬╬╬╬╬╬         █▓▓▓▌    ▐▓▓▓█   ▓▓▓   ▀▓▓▄▄▄▄▓▓▀   ▐▓▓▓▓▓▓▓▓▌
 ╬╬╬╬╬╬╣         ╠╬╬╬╬╬╬       ▝▀▀▀▀      ▀▀▀▀▘  ▀▀▀     ▀▀▀▀▀▀       ▀▀▀▀▀▀
╚╬╬╬╬╬╩           ╩╬╬╬╬╩

Welcome to Aleo! We thank you for running a node and supporting privacy.

Your Aleo address is aleo18gkjr8e0yqlzxqvpf2722trn2wyyyhx70l5myqjj9ra7k8rshyzsqpwq4x.

Starting a client on Aleo Testnet3.

ATTENTION - "universal.srs.trial.3747e59" does not exist, downloading this file remotely and storing it locally. Please ensure "universal.srs.trial.3747e59" is stored in "/root/.aleo/resources/universal.srs.trial.3747e59".

snarkvm_parameters::testnet3 - Downloading parameters...
snarkvm_parameters::testnet3 - 2.thread 'main' panicked at 'Failed to start the node: curl::error: Error { description: "Transferred a partial file", code: 18, extra: Some("transfer closed with 299937167 bytes remaining to read") }', snarkos/main.rs:62:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The issue has been detected on several different VPS and different developers.

**Comment by goodbenya** [comment]
Add backtrace  

root@vm610352:~/snarkOS# export $RUST_BACKTRACE=1
...
Starting a client on Aleo Testnet3.

thread 'main' panicked at 'Failed to start the node: IO error: While lock file: /root/.aleo/storage/ledger-3/LOCK: Resource temporarily unavailable', snarkos/main.rs:62:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: tokio::park::thread::CachedParkThread::block_on
   5: tokio::runtime::thread_pool::ThreadPool::block_on
   6: tokio::runtime::Runtime::block_on
   7: snarkos::main

**Comment by ljedrz** [comment]
The original issue has been fixed, the second one is caused by launching 2 nodes simultaneously (unrelated).
