### ISSUE TITLE
[Bug] Duplicate sync block error, failed（panicked at 'called `Result::unwrap()` on an `Err` value: Invalid block version）

### ISSUE THREAD

**Issue by 710254135** [AleoHQ/snarkOS#1909]
## 🐛 Bug Report
Unable to synchronize block data:
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid block version', /home/wei/snarkOS/snarkos/ledger/mod.rs:305:81
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(312), ...)', /home/wei/snarkOS/snarkos/ledger/mod.rs:326:22
-------------------------------------------------------------------

Synchronization can never be completed

**Comment by ljedrz** [comment]
Duplicate of https://github.com/AleoHQ/snarkOS/issues/1873.
