### ISSUE TITLE
[Proposal] Add a local development mode to SnarkOS

### ISSUE THREAD

**Issue by facundoolano** [AleoHQ/snarkOS#1914]
There should be a way to run the SnarkOS node in a local development mode, similar to what we've been doing with `aleo node start`.

This will have two benefits:

- It will support local application development against the same code as runs in production.
- It will force us to adjust the node to run in a more environment and node type agnostic manner.

The idea is to eventually remove endpoint definitions from the aleo cli in favor of this local development node mode, removing one of the current sources of duplication and development effort. (we can still support the aleo node start command, only that the implementation will be in SnarkOS)

**Comment by raychu86** [comment]
The intention of the `--dev` flag in the snarkOS cli was to introduce development nodes. I believe we can hook up snarkOS into the Aleo SDK without much issue, however we currently do not have block generation (beacon) logic implemented in snarkOS yet.

**Comment by howardwu** [comment]
> There should be a way to run the SnarkOS node in a local development mode, similar to what we've been doing with `aleo node start`.
> 
> This will have two benefits:
> 
> * It will support local application development against the same code as runs in production.
> * It will force us to adjust the node to run in a more environment and node type agnostic manner.
> 
> The idea is to eventually remove endpoint definitions from the aleo cli in favor of this local development node mode, removing one of the current sources of duplication and development effort. (we can still support the aleo node start command, only that the implementation will be in SnarkOS)

As per the original issue, `aleo node start` has been ported to `snarkOS` and now supports the requested features.
