### ISSUE TITLE
[Bug] Submitting two transactions that try to spend the same record crashes the node

### ISSUE THREAD

**Issue by jrchatruc** [AleoHQ/snarkOS#1916]
## 🐛 Bug Report

If two transactions that try to spend the same record are sent concurrently to a node, the node will crash as both transactions are included in the mempool and the node eventually sees an invalid transaction in the ledger.

```
Error: Serial number '4185732401280497918912021315718374434972622186606026864607670731858726517038field' already exists in the ledger
Main process exited, code=exited, status=1/FAILURE
Failed with result 'exit-code'.
```

## Steps to Reproduce

Concurrently send two transactions spending the same record

## Expected Behavior

The node should not crash, one of the transactions should just be rejected as invalid eventually.

## Your Environment

- snarkOS version: Current `testnet3` branch, commit `19181b1b529cfbc9a5b74ab5bf41fac1bf5cfafe`
- Rust version:
```
$ cargo --version
cargo 1.65.0-nightly (4fd148c47 2022-08-03)
```
- Computer OS: macOS Monterrey `12.5.1`

**Comment by raychu86** [comment]
This should be addressed with https://github.com/AleoHQ/snarkVM/pull/1081

**Comment by raychu86** [comment]
Closed with https://github.com/AleoHQ/snarkVM/pull/1081
