### ISSUE TITLE
[Feature] Endpoint to retrieve all blocks in a given height range

### ISSUE THREAD

**Issue by jrchatruc** [AleoHQ/snarkOS#1920]
## 🚀 Feature

Add an endpoint to get all blocks in a given height range, for instance

```
/testnet3/blocks/?start={start_height}&count={n}
```

## Motivation

An endpoint like this would greatly improve the explorer's block screen, which currently does one http call per block to show the info.

**Comment by raychu86** [comment]
https://github.com/AleoHQ/snarkVM/pull/1068
