### ISSUE TITLE
[Feature] Add a create transfer endpoint 

### ISSUE THREAD

**Issue by facundoolano** [AleoHQ/snarkOS#1924]
## 🚀 Feature

Expose `create_transfer` endpoint on the beacon node that receives the private key of the sender, the recipient, an amount of credits to send and performs the transfer on chain.

## Motivation

This is necessary to implement transfers in the wallet.

**Comment by Linuxpizi** [comment]
the official should not provide, this only can used in private env and local full node, because it is not security and privacy

**Comment by howardwu** [comment]
Agreed, it is not secure or private.
