### ISSUE TITLE
[Bug] request_genesis_block  method crash in prover [sync]

### ISSUE THREAD

**Issue by zxgangandy** [AleoHQ/snarkOS#1926]
## 🐛 Bug Report

pub(super) async fn request_genesis_block<N: Network>(leader_ip: IpAddr) -> Result<Block<N>> {
    info!("Requesting genesis block from {}", leader_ip);
    let block_string = reqwest::get(format!("http://{leader_ip}/testnet3/block/0")).await?.text().await?;
    Block::from_str(&block_string)
}

- the error from the 'Block::from_str' method;

- error logs are: invalid type: null, expected a sequence

(Write your description here)

## Steps to Reproduce

1. Step 1...
2. Step 2...
3. Step 3...

## Expected Behavior

(Write what you expected to happen here)

## Your Environment

- 
- 
-

**Comment by howardwu** [comment]
Closing as this Phase 1 issue was resolved in Phase 2. Thank you for the report.
