### ISSUE TITLE
[Bug] consume or give the fee to the validator when a transaction fails

### ISSUE THREAD

**Issue by facundoolano** [AleoHQ/snarkOS#1927]
## 🐛 Bug Report

To prevent attacks of using invalid transactions, the node should consume the fee even when the transaction fails.
The fee should be variable to allow legitimate higher-paying transactions to win even in the presence of transaction "spam". 
Add unit tests to exercise this scenario.

**Comment by howardwu** [comment]
Agreed, this issue has now been address with the introduction of `Accepted`/`Rejected` transactions via `consensus`. The `fee` is now being consumed and a new `Transaction::Fee` type was introduced to prevent attacks. Closing as resolved.
