### ISSUE TITLE
[Bug] Beacon node and http sync server not in sync

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkOS#1934]
## 🐛 Bug Report

AKA the http sync server is not generating files for new blocks.

From discord reports, it seems the http sync server (`vm.aleo.org`) has stopped updating, so the initial sync phase will panic at block 23767 with no way to recover.

## Steps to Reproduce

Start the node after stopping it for a while or sync from start.

## Expected Behavior

From https://github.com/AleoHQ/snarkOS/blob/19181b1b529cfbc9a5b74ab5bf41fac1bf5cfafe/snarkos/ledger/mod.rs#L291, it seems this phase is using data from the beacon node for network height. This could potentially create data discrepancy if one side is not working correctly.

I'd recommend making another endpoint like `https://vm.aleo.org/testnet3/block/testnet3/height` to only get the height info from one source.

## Your Environment

N/A

**Comment by HarukaMa** [comment]
Looks like it's not "out of sync"; the block 23767 simply doesn't exist on the http sync server.

**Comment by ljedrz** [comment]
I don't think we've seen it happen in a while now, so I'm assuming it's fixed now. Please feel free to reopen if it ever does.
