### ISSUE TITLE
[Feature] Reuse HTTPS connection when syncing the ledger

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkOS#1953]
## 🚀 Feature

Use a proper HTTP connection pool for HTTP syncing phase.

## Motivation

Currently the HTTP syncing code opens 100 concurrent HTTPS connections for syncing, and immediately disconnects after one request is complete. This is a waste of resources as the TCP and TLS handshake takes many round-trips to complete and the syncing code is actually blocking (blocks are added by order, obviously).

EDIT: maybe the most important concern is the server load here as the networking time *could* be negligible when syncing the ledger.

## Implementation

If network performance is a concern, maybe open up to `num_cpus::get()` HTTP connections and do all the requests using existing connections, instead of repeatedly opening new connections.

Only `Ledger::initial_sync_with_network` would be affected.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
If the http syncing will stay and the feature will be accepted. I'm not sure what's the good pattern to implement it in Rust though. `futures::stream::iter` seems good enough for a proper queuing of the incoming block data though.

**Comment by ljedrz** [comment]
It should be simple enough to reuse the connection; I'll look into it tomorrow.
