### ISSUE TITLE
[Docs]how to get miner message。

### ISSUE THREAD

**Issue by 1770697081** [AleoHQ/snarkOS#1986]
Can someone tell me how to run the whole node or mining? After I run the following command for a period of time, I will always brush the screen and print. It looks like mining, but the next day, I found that the process was suspended.

Can you provide a complete tutorial or readme document. Or is there a communication group? This is the first time, thank you.

**Comment by 1770697081** [comment]
i'm sorry。
1、wo run this cmd:#cargo run --release -- miner stats aleo1lwz****,but cause some question.
```
 Running `target/release/snarkos miner stats aleo1lwzkp73pmfc4cve67tczyzcwh0dhlg9h4eqnzc396jpql68dagqskzmxyl`
error: The subcommand 'miner' wasn't recognized
````
2、And please update readme.md。

**Comment by ljedrz** [comment]
Mining is not available during this phase (1st) of the third testnet; it's going to be available during phase 2.
