### ISSUE TITLE
[Bug] snarkOS client has no SIGTERM/SIGINT handlers

### ISSUE THREAD

**Issue by jimpo** [AleoHQ/snarkOS#1996]
## 🐛 Bug Report

snarkOS client does not respond to SIGTERM/SIGKILL when running as the root process in a Docker container. This is because in Linux, a process running with PID 1 will ignore SIGTERM/SIGINT unless a signal handler is installed. This means that running `docker stop` takes longer than necessary because it waits until the process exit timeout before sending SIGKILL. This gives the process no chance for graceful shutdown.

## Steps to Reproduce

1. Run the snarkOS client in a Docker container
2. Run `docker stop -t 60`
3. Twiddle your thumbs for 60 seconds while your container happily chugs along

## Expected Behavior

The snarkOS process should gracefully exit immediately

## Your Environment

- 
- 
-

**Comment by howardwu** [comment]
@ljedrz I lost track of this issue. Did we end up solving it?

**Comment by ljedrz** [comment]
I proposed a PR at one point, but it wasn't merged at the time; as far as I can tell there is still room for improvement here, I can revive this change shortly.

**Comment by howardwu** [comment]
Closing as this issue was handled in the PR above.
