### ISSUE TITLE
[Bug]P2P  is  not stable 

### ISSUE THREAD

**Issue by luckydog8686** [AleoHQ/snarkOS#2012]
## 🐛 Bug Report
When a remote node is not connected, snarkOS  trys to connect it continuously  and doesn't try to connect new nodes. Then the node cannot sync until the node is restarted. 

## Steps to Reproduce

1. pull the latest code and compile
2. run the node and watch the logs
3. after hours or days, Node may lose connections with some nodes and print logs about reconnections , the node stop syncing. 

## Expected Behavior

The node can give up lost connections and find new peers to connect.
The node always syncs up to the latest block.

## Your Environment

ubuntu20

**Comment by ljedrz** [comment]
This issue should no longer be applicable. Please reopen if you encounter it again.
