### ISSUE TITLE
[Bug]where is run-prover.sh?

### ISSUE THREAD

**Issue by aihunter666** [AleoHQ/snarkOS#2019]
where is run-prover.sh?
I can't find it anywhere. It's only run-client.sh
please help me. thanks

**Comment by hanbu97** [comment]
Same problem, or giving some tutarilal on how to run a validator node without run-prover.sh.

**Comment by niklaslong** [comment]
The script can be found in the root directory of the `testnet3` branch: https://github.com/AleoHQ/snarkOS/blob/testnet3/run-prover.sh.

**Comment by aihunter666** [comment]
thanks
