### ISSUE TITLE
[Bug] Checksum mismatch when downloading `combine.prover.c8d8c6d`

### ISSUE THREAD

**Issue by cktkdgh1219** [AleoHQ/snarkOS#2031]
It's my first time using github, so I'm not used to it. Please understand.

  Compiling snarkvm-console v0.9.0 (https://github.com/AleoHQ/snarkVM.git?rev=1f0f2c9#1f0f2c98)
   Compiling rusoto_signature v0.48.0
   Compiling snarkvm-circuit-types v0.9.0 (https://github.com/AleoHQ/snarkVM.git?rev=1f0f2c9#1f0f2c98)
   Compiling snarkvm-circuit v0.9.0 (https://github.com/AleoHQ/snarkVM.git?rev=1f0f2c9#1f0f2c98)
   Compiling snarkvm-compiler v0.9.0 (https://github.com/AleoHQ/snarkVM.git?rev=1f0f2c9#1f0f2c98)
   Compiling snarkvm-rest v0.9.0 (https://github.com/AleoHQ/snarkVM.git?rev=1f0f2c9#1f0f2c98)
   Compiling snarkos-environment v2.0.2 (/filecoin/snarkOS/environment)
   Compiling rocksdb v0.19.0
    Finished release [optimized] target(s) in 2m 15s
     Running `target/release/snarkos --verbosity 2`

         ╦╬╬╬╬╬╦
        ╬╬╬╬╬╬╬╬╬                    ▄▄▄▄        ▄▄▄
       ╬╬╬╬╬╬╬╬╬╬╬                  ▐▓▓▓▓▌       ▓▓▓
      ╬╬╬╬╬╬╬╬╬╬╬╬╬                ▐▓▓▓▓▓▓▌      ▓▓▓     ▄▄▄▄▄▄       ▄▄▄▄▄▄
     ╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬              ▐▓▓▓  ▓▓▓▌     ▓▓▓   ▄▓▓▀▀▀▀▓▓▄   ▐▓▓▓▓▓▓▓▓▌
    ╬╬╬╬╬╬╬╜ ╙╬╬╬╬╬╬╬            ▐▓▓▓▌  ▐▓▓▓▌    ▓▓▓  ▐▓▓▓▄▄▄▄▓▓▓▌ ▐▓▓▓    ▓▓▓▌
   ╬╬╬╬╬╬╣     ╠╬╬╬╬╬╬           █▓▓▓▓▓▓▓▓▓▓█    ▓▓▓  ▐▓▓▀▀▀▀▀▀▀▀▘ ▐▓▓▓    ▓▓▓▌
  ╬╬╬╬╬╬╣       ╠╬╬╬╬╬╬         █▓▓▓▌    ▐▓▓▓█   ▓▓▓   ▀▓▓▄▄▄▄▓▓▀   ▐▓▓▓▓▓▓▓▓▌
 ╬╬╬╬╬╬╣         ╠╬╬╬╬╬╬       ▝▀▀▀▀      ▀▀▀▀▘  ▀▀▀     ▀▀▀▀▀▀       ▀▀▀▀▀▀
╚╬╬╬╬╬╩           ╩╬╬╬╬╩

Welcome to Aleo! We thank you for running a node and supporting privacy.

Your Aleo address is aleo1v0kn4fssg5qrafy8shxwfp2xnm0ama4lzwxl7x4c4jt99z0vrgpsx6hvnr.

Starting a client on Aleo Testnet3.

   Compiling snarkos v2.0.2 (/filecoin/snarkOS)

ATTENTION - "combine.prover.c8d8c6d" does not exist, downloading this file remotely and storing it locally. Please ensure "combine.prover.c8d8c6d" is stored in "/root/.aleo/resources/combine.prover.c8d8c6d".

snarkvm_parameters::testnet3 - Downloading parameters...
snarkvm_parameters::testnet3 - 100.00% complete (0 MB total)
snarkvm_parameters::testnet3 - Download complete
thread 'main' panicked at 'Failed to load proving key: ChecksumMismatch("c8d8c6d01eeb94762c0a761e8586fe6ecd3f4ea580f600abfbc51cb6c4f08924", "e3ebaa16dd9d9b9fc107c42183fb6cf9d22927e1af03dbbdfa0ccc38e4e4ac31")', /root/.cargo/git/checkouts/snarkvm-f1160780ffe17de8/1f0f2c9/parameters/src/testnet3/mod.rs:93:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Finished release [optimized] target(s) in 2m 30s
     Running `target/release/snarkos --verbosity 2`

         ╦╬╬╬╬╬╦
        ╬╬╬╬╬╬╬╬╬                    ▄▄▄▄        ▄▄▄
       ╬╬╬╬╬╬╬╬╬╬╬                  ▐▓▓▓▓▌       ▓▓▓
      ╬╬╬╬╬╬╬╬╬╬╬╬╬                ▐▓▓▓▓▓▓▌      ▓▓▓     ▄▄▄▄▄▄       ▄▄▄▄▄▄
     ╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬              ▐▓▓▓  ▓▓▓▌     ▓▓▓   ▄▓▓▀▀▀▀▓▓▄   ▐▓▓▓▓▓▓▓▓▌
    ╬╬╬╬╬╬╬╜ ╙╬╬╬╬╬╬╬            ▐▓▓▓▌  ▐▓▓▓▌    ▓▓▓  ▐▓▓▓▄▄▄▄▓▓▓▌ ▐▓▓▓    ▓▓▓▌
   ╬╬╬╬╬╬╣     ╠╬╬╬╬╬╬           █▓▓▓▓▓▓▓▓▓▓█    ▓▓▓  ▐▓▓▀▀▀▀▀▀▀▀▘ ▐▓▓▓    ▓▓▓▌
  ╬╬╬╬╬╬╣       ╠╬╬╬╬╬╬         █▓▓▓▌    ▐▓▓▓█   ▓▓▓   ▀▓▓▄▄▄▄▓▓▀   ▐▓▓▓▓▓▓▓▓▌
 ╬╬╬╬╬╬╣         ╠╬╬╬╬╬╬       ▝▀▀▀▀      ▀▀▀▀▘  ▀▀▀     ▀▀▀▀▀▀       ▀▀▀▀▀▀
╚╬╬╬╬╬╩           ╩╬╬╬╬╩

Welcome to Aleo! We thank you for running a node and supporting privacy.

Your Aleo address is aleo1hf33f7h4w2gh307dna3zx88nmmzqwkxx979gnmerc97wy89vxq8s873xgm.

Starting a client on Aleo Testnet3.

ATTENTION - "combine.prover.c8d8c6d" does not exist, downloading this file remotely and storing it locally. Please ensure "combine.prover.c8d8c6d" is stored in "/root/.aleo/resources/combine.prover.c8d8c6d".

snarkvm_parameters::testnet3 - Downloading parameters...
snarkvm_parameters::testnet3 - 100.00% complete (0 MB total)
snarkvm_parameters::testnet3 - Download complete
thread 'main' panicked at 'Failed to load proving key: ChecksumMismatch("c8d8c6d01eeb94762c0a761e8586fe6ecd3f4ea580f600abfbc51cb6c4f08924", "e3ebaa16dd9d9b9fc107c42183fb6cf9d22927e1af03dbbdfa0ccc38e4e4ac31")', /root/.cargo/git/checkouts/snarkvm-f1160780ffe17de8/1f0f2c9/parameters/src/testnet3/mod.rs:93:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

An error occurred while running and it does not run again. What should I do?

**Comment by niklaslong** [comment]
Thank you for reporting this issue. What commit hash are you running? I notice you're compiling snarkVM `0.9.0` the latest we have on `testnet3` branch is `0.9.3` so this may be fixed by updating your local version.

**Comment by cktkdgh1219** [comment]
@niklaslong What do you mean by commit hash version? 
What appears to be the last snarkVM compiled
  Compiling snarkvm-rest v0.9.0 (https://github.com/AleoHQ/snarkVM.git?rev=1f0f2c9#1f0f2c98)
This is it.

**Comment by niklaslong** [comment]
Could you `git log` in your repository root? Your top commit should look something like:
```
commit cf9f4a488802655235b06f0d7d38903c7af5bd5e (HEAD -> testnet3, upstream/testnet3)
Author: Howard Wu <9260812+howardwu@users.noreply.github.com>
Date:   Tue Nov 8 00:27:15 2022 -0800

    Update README
```

**Comment by cktkdgh1219** [comment]
@niklaslong Yes. Execute as root from the time run_client.sh is executed
Is it correct to ask this? Unfortunately, I can't understand English well because I'm not good at English.

**Comment by niklaslong** [comment]
You seem to be running an outdated version of snarkOS. Could you update it? The simplest way to do so, is to remove the repository and reinstall from scratch. Alternatively, you can update through `git` if you are familiar with it.

**Comment by niklaslong** [comment]
Closing this issue for now, feel free to reopen if it persists after running the latest version of snarkOS.
