### ISSUE TITLE
[Bug]Run prover.sh failed! ,after client node running and creating account  is successful.

### ISSUE THREAD

**Issue by erickingxu** [AleoHQ/snarkOS#2032]
When run run-prover.sh , I got a failed as follows:
Welcome to Aleo! We thank you for running a node and supporting privacy.

thread 'main' panicked at 'Failed to bind listener: Os { code: 98, kind: AddrInUse, message: "Address already in use" }. Check if another Aleo node is running', /root/Aleo/snarkOS/node/router/src/lib.rs:159:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by niklaslong** [comment]
Indeed, the script should be made more robust. I only managed to reproduce this when my upstream branch wasn't set (and thus shouldn't happen on a fresh clone). Does this resolve the issue for you?

**Comment by erickingxu** [comment]
I pull new merge as follows, when I run ./run-prover.sh script:
Checking for updates...
Saved working directory and index state WIP on testnet3: bb9cfb6 Merge pull request #2043 from AleoHQ/feat/const-connect
But failed again~

**Comment by niklaslong** [comment]
The error indicates some program is already using the port (4133); perhaps it is indeed already in use but not by snarkOS (you can `lsof -i :4133` on mac, use `netstat` or even `grep` the file descriptors using the process id for `snarkos` on linux)?

**Comment by erickingxu** [comment]
yes, I restart program again it is worked smoothly. thanks,guy

**Comment by nopapername** [comment]
> 
same question
how restart?
