### ISSUE TITLE
[Bug] How can I join aleo's discord 

### ISSUE THREAD

**Issue by readygo67** [AleoHQ/snarkOS#2033]
## 🐛 Bug Report
IT IS NOT A BUG, but I need help to join aleo's discord.

In aleo's discord invitation(shown below), after 10 minutes elapsed, I click the "verify" button, nothing happen. 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/78890754/200563615-7db4f1fb-cace-4c56-922a-5213d76f8860.png">

my discord setting is as below 
<img width="952" alt="image" src="https://user-images.githubusercontent.com/78890754/200563431-f5d52b7f-c534-41ac-b2ad-3067783acba1.png">

I have no idea how to join aleo's discord, any help is appreciated.

**Comment by niklaslong** [comment]
Closing this as it isn't engineering related. We're looking into it.

**Comment by readygo67** [comment]
Please feedback if any progress, thanks.

**Comment by niklaslong** [comment]
If this is still an issue, you can email [viviane@aleo.org](mailto:viviane@aleo.org).
