### ISSUE TITLE
How to reslove:  TRACE Prover solution was below the necessary proof target (1 < 47421)

### ISSUE THREAD

**Issue by tangmengqiu** [AleoHQ/snarkOS#2056]
## 🐛 Bug Report
Prover not work well. 

## Steps to Reproduce
PROVER_PRIVATE_KEY=A***  ./run-prover.sh > /opt/snarkos/miner.log 2>&1 &

## Expected Behavior
Prover works well

## Your Environment
latest
cargo 1.65.0 (4bc8f24d3 2022-10-20)
Ubuntu
- 
- 
-

**Comment by pennchester** [comment]
![image](https://user-images.githubusercontent.com/46217533/201647518-d8db9d24-9926-4f6b-bfa2-f6d38fb3c01c.png)
Same question

**Comment by zvolin** [comment]
Could you share the details about the hardware you're running provers on?

**Comment by ackness** [comment]
![image](https://user-images.githubusercontent.com/19150500/201932655-e8c79cbf-0bab-47de-a7ff-b20c84a5abd4.png)
same. 8c 16g

**Comment by zvolin** [comment]
I'm afraid that there is no bug here, just your hardware might not be strong enough to produce a competitive solutions

**Comment by tangmengqiu** [comment]
> I'm afraid that there is no bug here, just your hardware might not be strong enough to produce a competitive solutions

You are right. Thanks!
