### ISSUE TITLE
private key is not executed

### ISSUE THREAD

**Issue by cktkdgh1219** [AleoHQ/snarkOS#2058]
@niklaslong 
Now, to connect to the beacon, I entered my private key through the `cargo run --release -- start --nodisplay --dev 0 --beacon ` command to run it, but it seems that the private key is not executed.
 
```
      Private Key APrivateKey-----------------------------------------------------GPWH
      View Key AViewKey---------------------------------------------------------rw
      Address aleo1rhg-----------------------------------------------------------p9px

JSON Web Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGVvMXJoZ2R1NzdoZ3lxZDN4amo4dWN1M2pqOXIya3J3ejZtbnp5ZDgwZ25jcjVmeGN3bGg1cnN2enA5cHgiLCJpYXQiOjE2Njg0MTkwMTQsImV4cCI6MTk4Mzc3OTAxNH0.ueaOKtnJzqjRrKNveSUAl_CGGb-RUoxevUj97QKL0xI

🪪 Your Aleo address is aleo1rhgd-----------------------------------------p9px.
```

The message appears, but the private key and address are not mine. The value was treated privately, in case you didn't know. Considering that other devices also output the same key value and address, it is considered a sampling key.

 The command `cargo run --release -- start --nodisplay --dev 1 --prover ` runs normally using my private key, but the beacon does not run, so the normal prover command is connected to 127.0.0.1 4130 this doesn't work

Any solution?

_Originally posted by @cktkdgh1219 in https://github.com/AleoHQ/snarkOS/issues/2040#issuecomment-1313396052_

**Comment by zvolin** [comment]
Please note that adding `--dev` puts you in development mode, this is meant to work locally with the code rather than being a real node in the network.
If you want to make the development beacon using your private key then you can add your private key to the command:
```
cargo run --release -- start --help
...
         --beacon <BEACON>          Specify this as a beacon, with the given account private key for
                                    this node
```

**Comment by niklaslong** [comment]
In addition, we support running clients and provers on testnet. If you'd like to do so, I'd recommend running the node with the provided scripts as documented in the README. Note: `--dev` samples an account from an insecure RNG, which is not fit for use in environments other than development.

**Comment by zvolin** [comment]
I've just tried it and it seems that the private key passed to the `--beacon` isn't used in development mode. For development beacons, a one shot account is sampled every time.
