### ISSUE TITLE
[Bug] `--seed` parameter can't take 256-bit numbers

### ISSUE THREAD

**Issue by elliot-u410** [AleoHQ/snarkOS#2068]
## 🐛 Bug Report

If you're offloading randomness during key generation then you might use `account new --seed X`. However, this X must be a decimal number and trying to give it a 256-bit decimal number produces an error.

```shell
seed=$(head --bytes 32 < /dev/urandom | xxd -p | tr -d '\n' | tr '[:lower:]' '[:upper:]')
snarkos account new --seed "$(echo "obase=10;ibase=16;$seed" | bc | tr -d '\\\n')" 
error: Invalid value "38868010450269069756484274649022187108349082664538872491798902858296683054657" for '--seed <SEED>': number too large to fit in target type
```

Ideally `--seed` should just take arbitrary hex-encoded data instead.

Using a smaller seed space works but loses a great deal of security.

**Comment by zvolin** [comment]
Thanks for the report :) indeed, we are using 64bit number for this argument. It should be fairly simple to add/modify a switch to take 32 bytes.
I can look into this a bit later, in the meantime if someone wants to contribute this sounds like a great first issue

**Comment by elliot-u410** [comment]
Thank you! I'll confess this fix is still lacking in one area: it's still expecting the seed as an integer. It's actually rather hard to come up with a random *integer* from 32 bytes of entropy (see my antics in the script above). It would be better to just pass the hex in directly.
