### ISSUE TITLE
Prover solution was below the necessary proof target

### ISSUE THREAD

**Issue by Krysme** [AleoHQ/snarkOS#2069]
## 🐛 Bug Report

Prover solution was below the necessary proof target

## Steps to Reproduce

execute run-prover.sh and then input the private key
## Expected Behavior
The node runs normally

![image](https://user-images.githubusercontent.com/11013684/202076857-dbed5e9c-5800-4d5e-bfc7-95b367457422.png)

## Your Environment
OS: Ubuntu 20.04.2 LTS
CPU: 2 X AMD EPYC 7601 32-Core Processor (128 phisical thread in total)
Memory: 1 TB

I'm totally aware of issue #2056, but I believe this machine should be powerful enough to generate proofs.

**Comment by zvolin** [comment]
Indeed. While the cpu utilization could definitely be better on our side I think there is something else causing this. Will need to investigate more. Thanks for the report

**Comment by raychu86** [comment]
Though I only have a small snippet of your logs, I believe this should be normal.

A prover solution's target is randomly sampled with `u64::MAX / hash_to_u64(commitment)`. With a proof target of 70000, there is  a 0.001428571% chance of generating a valid solution on each iteration. 

Effectively, this means you should be sampling ~70000 solutions that are insufficient before finding a valid one. (Each insufficient solution will output a `Prover solution was below the necessary proof target ...` message)

**Comment by ljedrz** [comment]
Closing, as this log no longer exists in the codebase; please feel free to reopen if you disagree.
