### ISSUE TITLE
[Docs] Describe which end of the verbosity scale is "more" and which is "less"

### ISSUE THREAD

**Issue by elliot-u410** [AleoHQ/snarkOS#2077]
## 📚 Documentation

Currently the verbosity help says you can choose between 4 options: 0-3. However, it's not stated which side of that scale leads to the *most* verbose logs and which side leads to the *least* verbose. A simple note could solve the issue.

**Comment by niklaslong** [comment]
Thanks for bringing this up. If not specified, we use a total order on the natural numbers, i.e. 0 < 1 < 2 < 3; the higher on the scale the more granular the logs.

**Comment by elliot-u410** [comment]
Thanks! I was able to ascertain that by reading the source code. Did you add this clarification to the help message?

**Comment by niklaslong** [comment]
The way we specify verbosity is both intuitive (as explained above) and rooted in convention. In future, it may be coherent to tighten up our logging, in which case more precise documentation on what specific tracing levels are activated per level would be a "nice to have", but we're not yet in a position to do so. SnarkOS is under heavy developement and as such, we have to prioritise the most critical issues at this time. I hope that makes sense? Thanks again!
