### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by luckydog8686** [AleoHQ/snarkOS#2095]
## 🐛 Bug Report

prover must connect to beacon. In fact node should have the ability to relay  the proof and does not have to connect the beacon directly.
## Steps to Reproduce
run provers and block all bencon ips in firewalls and connect some other nodes which can connect  beacons directly. 

## Expected Behavior
provers does not have to connect beacons directly and nodes can relay the proof produced by provers. 

## Your Environment

- 
- testnet3 git commit:  ea36997d4873a365192e9dc1e75d128599254a9e
- 
- rustc 1.65.0 (897e37553 2022-11-02)
- 
ubuntu20.04

**Comment by howardwu** [comment]
The current requirement is for the prover to connect to validators, not beacons. As of the `V4` fork this week, you are now able to run a validator as well. I will preemptively close this PR since the issue has been addressed in `V4`.
