### ISSUE TITLE
[Bug] `--logfile` does not create missing file on open

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#2098]
## 🐛 Bug Report

snarkOS is unable to create a log file if it does not exist.

![Screen Shot 2022-11-27 at 3 05 08 PM](https://user-images.githubusercontent.com/9260812/204164558-22b47e37-56cc-4eea-8ade-a0059d3b6d34.png)

## Steps to Reproduce

```
snarkos start --logfile /var/log/snarkOS/beacon.log
```

## Expected Behavior

It should create the file if it does not exist.

## Your Environment

- `testnet3` branch, latest commit

**Comment by zvolin** [comment]
It's most likely because some of parent directories doesn't exist (I'm looking at you `/var/log/snarkOS/`)
