### ISSUE TITLE
[Bug] REST server not running for prover

### ISSUE THREAD

**Issue by elliot-u410** [AleoHQ/snarkOS#2120]
## 🐛 Bug Report

Running a prover has the following log entry early after startup:
```
🌐 Starting the REST server at 0.0.0.0:3033.
```

However, any attempt to connect to that fails:

```
curl localhost:3033/
curl: (56) Recv failure: Connection reset by peer
```

I'm using version https://github.com/AleoHQ/snarkOS/commit/bf9cc9d61cef5893be3a9f62ada6fbfe1ef9c99a

**Comment by howardwu** [comment]
Ah, good catch. This is a mistaken log as clients and provers don't run REST servers.
