### ISSUE TITLE
[Feature] Add more useful sub commands

### ISSUE THREAD

**Issue by Xiechengqi** [AleoHQ/snarkOS#2128]
## 🚀 Feature

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/26536442/205278039-bcec2242-f3e3-4e5c-9001-47d490ba89e0.png">

Too few interactive commands available, causing a lot of confusion for deployment

**Comment by howardwu** [comment]
Can you share which command you would like to have?

The full steps to deploy a node are in the `README`. If the `README` handles the question here, feel free to close the issue.
