### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by salil177** [AleoHQ/snarkOS#2140]
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
aleo-prover: unrecognized service
Your Aleo Prover Node was not installed correctly, please reinstall.

**Comment by salil177** [comment]
aleo-prover: unrecognized service

**Comment by howardwu** [comment]
This appears to be third party software. snarkOS does not offer a service install process.
