### ISSUE TITLE
Unify the `Connecting to '{peer_ip}'...` message in `Router::handshake`

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#2149]
Unify the `Connecting to '{peer_ip}'...` message in `Router::handshake`.

_Originally posted by @howardwu in https://github.com/AleoHQ/snarkOS/pull/2108#pullrequestreview-1203846755_

**Comment by ljedrz** [comment]
Done in https://github.com/AleoHQ/snarkOS/pull/2221.
