### ISSUE TITLE
[Bug] failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`

### ISSUE THREAD

**Issue by zukia54** [AleoHQ/snarkOS#2199]
When install the snarkOS, the error appeared.
Need help ~~

error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`

Caused by:
  process didn't exit successfully: `C:\Project\Github\snarkOS\target\release\build\librocksdb-sys-7df220bd82af918c\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.60.1\src/lib.rs:2172:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `snarkos v2.0.2 (C:\Project\Github\snarkOS)`, intermediate artifacts can be found at `C:\Project\Github\snarkOS\target`

**Comment by ljedrz** [comment]
As the error states:
```
Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\admin.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.60.1\src/lib.rs:2172:31
```
You need to install `clang` (part of LLVM) and have it available in your `PATH`. This is not a snarkOS-specific issue.

related: https://github.com/rust-rocksdb/rust-rocksdb/issues/155
