### ISSUE TITLE
Hash rate performance feedback mandatory! [Feature]

### ISSUE THREAD

**Issue by B0-B** [AleoHQ/snarkOS#2212]
## Motivation
There is no possibility to check performance yet, so why should anyone mine this especially with current market and electricity prices if there is no feedback?

**Comment by ljedrz** [comment]
I'm not sure about the plans for this feature, but you might be able to use what one of the contributors proposed in a PR: https://github.com/AleoHQ/snarkOS/pull/2133.

**Comment by howardwu** [comment]
The performance of each prover is listed on the leaderboard:
https://www.aleo.network/leaderboard
