### ISSUE TITLE
[Proposal] Store the nonce of transitions on chain

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkOS#2287]
## 💥 Proposal

Currently the nonce for transitions are not stored on chain. However, it's needed to decrypt the private non-record inputs and outputs. Moreover, the `Transaction::execute()` function is not exposing the nonce, so almost all nonce are forever lost; those ciphertexts are not decryptable anymore. (There is no way to get tsk and tvk without the nonce.)

Considering the nonce for records are stored on chain, are there any complications that's preventing nonce for transitions being stored on chain as well?

**Comment by howardwu** [comment]
It is possible to decrypt private inputs and outputs with the existing on-chain data. You'll need to use the `decrypt_symmetric` operation, with the arguments in https://github.com/AleoHQ/snarkVM/blob/testnet3/synthesizer/src/block/transition/mod.rs#L196

**Comment by HarukaMa** [comment]
How to derive `tsk` and `tvk` without the nonce though? as it seems:

https://github.com/AleoHQ/snarkVM/blob/9e059261b2bb119e0df019bdb46c56aabfd53d3f/console/program/src/request/sign.rs#L60

https://github.com/AleoHQ/snarkVM/blob/9e059261b2bb119e0df019bdb46c56aabfd53d3f/console/program/src/request/sign.rs#L67

you'll need the nonce value to get them?

AFAIK only tpk is stored on chain right now.

**Comment by HarukaMa** [comment]
Just realized this issue actually belongs to snarkVM repo. You might want to transfer this issue to there.
