### ISSUE TITLE
[Bug] Beacon breaks down when add an invalid transaction

### ISSUE THREAD

**Issue by ghostant-1017** [AleoHQ/snarkOS#2305]
## 🐛 Bug Report

Beacon breaks down when add an invalid transaction to block.
The transaction will increment on chain mapping, which will cause the overflow.

thread 'tokio-runtime-worker' panicked at 'Integer addition failed on: 255u8 and 255u8', /root/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/snarkvm-console-network-environment-0.9.13/src/environment.rs:62:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
<img width="944" alt="image" src="https://user-images.githubusercontent.com/53888545/228138954-3837d179-a6fd-46ee-9d6f-3fda16c3907c.png">

## Steps to Reproduce
1.Depoy program like this
// The 'test' program.

program test.aleo {
    mapping ids: u64 => u8;

    transition set_id(id: u64)  {
        return () then finalize(id);
    }

    finalize set_id(id: u64) {
        // This will overflow when more than two same game_id exists;
        increment(ids, id, 255u8);
    }
}
2. call set_id twice

## Expected Behavior
Beacon should catch the overflow and drop the transaction

## Your Environment
snarkOS: 8cfa1657746bcdc372207f788f093b3060aac350
rustc 1.68.1 (8460ca823 2023-03-20)

**Comment by ghostant-1017** [comment]
Restart node won't help

**Comment by liolikus** [comment]
Seems that you need to close this issue.
