### ISSUE TITLE
[Bug] When program with imports  has deployed on chain, Beacon can't reboot 

### ISSUE THREAD

**Issue by ghostant-1017** [AleoHQ/snarkOS#2306]
## 🐛 Bug Report
When program with imports  has deployed on chain, Beacon can't reboot 
<img width="945" alt="image" src="https://user-images.githubusercontent.com/53888545/228442014-9f46734c-8b13-42cc-875d-8a5082d7b641.png">

## Steps to Reproduce
Deploy program with imports and reboot the node

## Your Environment

snarkOS: 8cfa1657746bcdc372207f788f093b3060aac350

**Comment by ghostant-1017** [comment]
We may need to topological sorting for all programs when add program to Process

**Comment by howardwu** [comment]
+1 on this. Thanks for catching this @ghostant-1017. I've notified the snarkVM team to look into this now. I'll try to get a fix up soon.

**Comment by raychu86** [comment]
Thanks for finding this issue! I've addressed it in a snarkVM PR here - https://github.com/AleoHQ/snarkVM/pull/1682
