### ISSUE TITLE
[Docs] testnet or devnet RPC endpoints? 

### ISSUE THREAD

**Issue by naddika** [AleoHQ/snarkOS#2419]
I've asked here and discord - no reply so far.

Does Aleo have any testnet or devent RPC endpoints?

**Comment by naddika** [comment]
@howardwu up

**Comment by ghost** [comment]
@naddika - I saw your question in /Welcome and already addressed it, [here](https://github.com/AleoHQ/welcome/issues/175). 

That said, if you'd like to discuss further or have additional questions, feel free to reach out to the Tech Ops team via techops@aleo.org.

**Comment by raychu86** [comment]
There are publicly available endpoints for Testnet and Mainnet. You can find some of the documentation [here](https://docs.leo-lang.org/testnet/getting_started/overview#query-the-network).
