### ISSUE TITLE
[Bug] Is the secret key generated during the first test inconsistent with the public key generated during the first test?

### ISSUE THREAD

**Issue by yushui468** [AleoHQ/snarkOS#2437]
## Your Environment

- 
- 
- 
snarkOS  2.0

**Comment by niklaslong** [comment]
Could you clarify what you mean by first test? Also can you give us an example of such an inconsistency and the steps we can take to reproduce the issue?

**Comment by raychu86** [comment]
This can be closed until more context is given.
