### ISSUE TITLE
[Bug] Deploy program file parse bug

### ISSUE THREAD

**Issue by AlexZhao6666** [AleoHQ/snarkOS#2447]
![1686883973707](https://github.com/AleoHQ/snarkOS/assets/136443781/3953b5d8-2f84-4ed2-95f7-6b6bf68cbb83)
## 🐛 Bug Report

when i test program deploy,i found a issue. when i use "BHP256::hash(info.title)",then deploy my program.will get error:" Failed to parse string. Remaining invalid string is: "hash.bhp256 r0.title into r1;    cast self.caller r1 r0 into r2 as Proposal.record;
    output r2 as Proposal.record;"

## Steps to Reproduce
this is the main.leo
// The `program` scope defines the data types, functions, and state associated with the `vote` program.
program vote.aleo {
  // 提案  
  struct ProposalInfo {
    title: field,
    content:field,
    proposer:address,
  }

  // 提案record
  record Proposal {
    owner: address,
    id:field,
    info:ProposalInfo
  }

  record Ticket{
    owner: address,
    proposal_id: field,
  }

  mapping proposals: field => ProposalInfo;
 
  mapping tickets:field => u64;
  mapping agree_tickets:field =>u64;
  mapping disagree_tickets:field => u64;

  // 发起提案
  transition create_proposal (info: ProposalInfo) ->  Proposal{
    // 判断程序调用者跟发起人是否同一个
    assert_eq(self.caller, info.proposer);

    // 保存提案信息
    // 根据title生成唯一id
    let id:field = BHP256::hash(info.title);
    return Proposal{
        owner: self.caller,
        id,
        info
    } then finalize(id);
  }
  finalize create_proposal (id:field) {
    Mapping::set(tickets,id,0u64);
  }
}

deploy command:

./snarkos developer deploy vote.aleo --private-key APrivateKey1zkp8CZNn3yeCseEtxuxxxxxxxxxxxxxxxPWH --query "http://localhost:3030" --path "vote/build/" --broadcast "http://localhost:3030/testnet3/transaction/broadcast" --fee 1000001169000 --record  "{  owner: aleo1rhgduxxxxxxxxxxxxxxx.private,  microcredits: 93750000000000u64.private,  _nonce: 4584221379804783317330395146930760519734799446305091160163494666308250813255group.public}"

## Expected Behavior
can deploy program success

## Your Environment

- 
snarkos 2.1.1
- 
rust 1.70.0
- 
macos 12.4

**Comment by AlexZhao6666** [comment]
after my replace "BHP256::hash(info.title)" to "1field",the deploy is success, It looks like there is a problem when parsing "::"

**Comment by howardwu** [comment]
The syntax has recently changed as per https://github.com/AleoHQ/snarkVM/pull/1647.

The Leo team (cc: @collinc97 @d0cd ) will be releasing an updated version of Leo in the next 1-2 weeks with the updated syntax.

To fix your program, you can append `as field;` to the end of that statement.

**Comment by AlexZhao6666** [comment]
> The syntax has recently changed as per [AleoHQ/snarkVM#1647](https://github.com/AleoHQ/snarkVM/pull/1647).
> 
> The Leo team (cc: @collinc97 @d0cd ) will be releasing an updated version of Leo in the next 1-2 weeks with the updated syntax.
> 
> To fix your program, you can append `as field;` to the end of that statement.

ok ! Looking forward to the new version
