### ISSUE TITLE
[Feature] Expose public mapping names, keys, and values

### ISSUE THREAD

**Issue by fulltimemike** [AleoHQ/snarkOS#2467]
## 🚀 Feature

Mapping names, keys, and values should be output in the block data, or an api endpoint that retrieves all mappings' update data based on a given block height.

## Motivation

As an Aleo developer, I would like to know the history of my program’s mapping key-value pairs. This will allow me to show users of my programs their history, usage, and current public data.

Currently, in order to figure out the history of a given mapping key-value pair, finalize functions have to be re-executed with the public inputs information obtained in the block data. For transactions with a finalize component within Aleo block data, the known data are:
* Program name
* Function name
* (Encrypted) inputs
* (Encrypted) outputs
* Finalize component inputs

Separately, for a given transaction but not a given transition, these finalize data are known: 
* mapping function type (e.g. update_key_value)
* Mapping id (field)
* Index
* key_id (field)
* value_id (field)

With all these data, and given that a program’s instructions are known, in order to find the value of a mapping at any given block (up to the current block), the functions has to be executed and mapping value updated every time a given program function is called. Note that the index must be used if there are multiple mappings updated in a given transition.

If the finalize data additionally included the mapping name, the key literal value, the value literal value, then we could construct a history of a mapping’s usage and updates. Alternatively, if the Aleo api exposed an endpoint to retrieve a mapping's entire history could also provide this information. The endpoint should take in a program id, because the mapping id may not necessarily be known as the mapping could have been removed.

See below for current finalize data:
```
"finalize": [
              {
                  "type": "update_key_value",
                  "mapping_id": "1983797953180567811979143201159699323489553565864862741629395500585975099993field",
                  "index": 0,
                  "key_id": "6734840842853071513047894160775850205244595944922363331996471212787090015555field",
                  "value_id": "8071618983338753384953810423877238125756048099417006199822619927987465059053field"
              }
          ]
```

And example data for a transition with a finalize component:
```
"id": "some_id",
                          "program": "finalize_example.aleo",
                          "function": "sample",
                          "inputs": [
                              {
                                  "type": "private",
                                  "id": "4field",
                                  "value": "ciphertext1e8kyf7zy0mely0"
                              },
                              {
                                  "type": "private",
                                  "id": "2390458754field",
                                  "value": "ciphertext1018924359875"
                              }
                          ],
                          "outputs": [],
                          "finalize": [
                              "293837field",
                              "5u8"
                          ]
```

## Implementation

When the mapping id, key id, and value id are output to the block data, the mapping name, key literal value, and value literal value should also be output to the block data. Alternatively, an endpoint to retrieve all history of a program's mappings could be exposed.

**Comment by raychu86** [comment]
Adding `key`, `value`, and `mapping_name` can be done, however there is a big state-space consideration. Doing so will greatly bloat the chain (especially as the stored objects/structs get larger and more complex).

In our case, it shouldn't be up to the ledger to bear the burden of tracking the history of each application, especially if it can be reconstructed via re-execution. If developers would like to track their history, they can simply iterate through the Ledger transactions relevant to their program, execute the finalize portions and store it independently.

Other chains also do not have this "lookback" ability without having to perform re-execution or special tracking outside of the chain itself. 

For now, we have endpoints for people to query the list of mappings for each program and the current state of mapping data via https://github.com/AleoHQ/snarkOS/pull/2461, however I'm not sure how much value there is tracking program mapping history on-chain.

Closing this issue now, but feel free to reopen if there's a compelling angle I'm not seeing.
