### ISSUE TITLE
[bug]zsnarkOs execute error not found program 

### ISSUE THREAD

**Issue by TuSoict** [AleoHQ/snarkOS#2470]
## 🐛 Bug Report

snarkos developer execute alway return : Program <program_id> not found 

## Steps to Reproduce

step1: deploy program. Get record after that 
step 2: execute function with cmd :
snarkos developer execute "${APPNAME}.aleo" "main" "1u32" "5u32" --private-key "${PRIVATEKEY}" --query "https://vm.aleo.org/api" --broadcast "https://vm.aleo.org/api/testnet3/transaction/broadcast" --fee 1000 --record "${RECORD}"

==> Return: Program helloworld_16azmq.aleo not found

## Expected Behavior
execute successfully 

## Your Environment
 snarkOS Version: latest
<img width="712" alt="image" src="https://github.com/AleoHQ/snarkOS/assets/25472126/235cf42a-2a12-42de-aedc-020552653d27">

**Comment by raychu86** [comment]
This issue should be resolved with this PR: https://github.com/AleoHQ/snarkOS/pull/2474.

The underlying problem was fixed here - https://github.com/AleoHQ/snarkVM/pull/1719

**Comment by TuSoict** [comment]
> This issue should be resolved with this PR: #2474.
> 
> The underlying problem was fixed here - [AleoHQ/snarkVM#1719](https://github.com/AleoHQ/snarkVM/pull/1719)

Thanks 
I just tried it again. also get error 
what I need to do next ? 
Do I must update anything ?

**Comment by TuSoict** [comment]
it works in Bump snarkVM to v0.12.6  
many thanks
