### ISSUE TITLE
[Bug] Can't execute any function of program on testnet3

### ISSUE THREAD

**Issue by qbitshero** [AleoHQ/snarkOS#2476]
## 🐛 Bug Report
I can't execute any function these 2 days, and it always return the error info " Program gtt_token.aleo not found"

## Steps to Reproduce
1. I deploy my program successfully as follows:
snarkos developer deploy gtt_token.aleo --private-key xxx--query "https://vm.aleo.org/api" --path "/root/src/gtt_token/build" --broadcast "https://vm.aleo.org/api/testnet3/transaction/broadcast" --fee 250000 --record "
{
  owner: aleo1xxx.private,
  microcredits: 50000000u64.private,
  _nonce: 8225214062985977638992326551654349514126354354477466147823339948410212765178group.public
}"

✅ Successfully broadcast deployment at1xfcxhkrxlfrpd5t6kwps54hdllt2hz0p72afer7e4duja9rg2u9qlmsw2r ('gtt_token.aleo') to https://vm.aleo.org/api/testnet3/transaction/broadcast.
at1xfcxhkrxlfrpd5t6kwps54hdllt2hz0p72afer7e4duja9rg2u9qlmsw2r

2. I check the program on Aleo Explorer https://www.aleo.network/transactions

3. I can't execute any function like this:
snarkos developer execute "gtt_token.aleo" "mint_public" "xxx" "10000000000u64" --private-key "xxx" --query "https://vm.aleo.org/api" --broadcast "https://vm.aleo.org/api/testnet3/transaction/broadcast" --fee 1000000 --record "
{
  owner: aleo1xxx.private,
  microcredits: 34002000u64.private,
  _nonce: 5704583795260376734776552208989038294896605109076968391469615776530433175132group.public
}"

📦 Creating execution transaction for 'gtt_token.aleo/mint_public'...

⚠️  Program gtt_token.aleo not found

4. But as you see, the Program gtt_token.aleo does exist on  Aleo Explorer.

## Expected Behavior
We can execute function normally.

## Your Environment

code version:
commit a7cf1b4cb4dab5e66dee6f7b68ab2981af0c2690 (HEAD -> testnet3, tag: v2.1.3, origin/testnet3, origin/HEAD)

rust version:
rustc 1.70.0 (90c541806 2023-05-31)

OS:
ubuntu

**Comment by howardwu** [comment]
It looks like `gtt_token.aleo` was only deployed 45 minutes ago to the network.
https://www.aleo.network/programs/gtt_token.aleo

Can you confirm this is still an issue?

**Comment by qbitshero** [comment]
It still fails now.
So, how long need I wait for ?

**Comment by qbitshero** [comment]
> It looks like `gtt_token.aleo` was only deployed 45 minutes ago to the network. https://www.aleo.network/programs/gtt_token.aleo
> 
> Can you confirm this is still an issue?

**Comment by qbitshero** [comment]
> It looks like `gtt_token.aleo` was only deployed 45 minutes ago to the network. https://www.aleo.network/programs/gtt_token.aleo
> 
> Can you confirm this is still an issue?

It still fails now.
So, how long need I wait for ?

**Comment by qbitshero** [comment]
It's the same bug with #2470

**Comment by qbitshero** [comment]
It's the same bug with #2470
