### ISSUE TITLE
[Bug] tx was reported as successful, but it actually failed.

### ISSUE THREAD

**Issue by liolikus** [AleoHQ/snarkOS#2488]
## 🐛 Bug Report

After `snarkos developer execute` Client showed me successful execution:
✅ Created execution transaction for '←[1mleo_nft_coder_no_wl_v1.aleo/mint←[0m'
✅ Successfully broadcast execution at1tj2feetdrq6fpgt985cuzvt6tz5p6anzr9f37e4vjykaea3gqyys695tmz ('←[1mleo_nft_coder_no_wl_v1.aleo/mint←[0m') to https://vm.aleo.org/pi/testnet3/transaction/broadcast.

But actually, tx did not appear in Explorer and was not executed.

`snarkos developer execute "leo_nft_coder_no_wl_v1.aleo" mint "{data1: 126855061660407994179721545304200474467u128, data2: 29115523947316814u128}"  0scalar --private-key "${PRIVATEKEY}" --query "https://vm.aleo.org/api" --broadcast "https://vm.aleo.org/api/testnet3/transaction/broadcast" --record "{ owner: aleo1xvlh6eyf5lgfv2z5za47j6qkh3uv5e0ga6gdzg5l4rssheymxsqqsnkgc4.private, microcredits: 27000000u64.private, _nonce: 3462626207595022122535373027983738527074846652060707362236842540799823150706group.public }"`

![image](https://github.com/AleoHQ/snarkOS/assets/85246338/46bfeee6-a939-499e-ad1f-06787a3cc591)

## Steps to Reproduce
Program: 
https://explorer.hamp.app/program?id=leo_nft_coder_no_wl_v1.aleo
https://explorer.hamp.app/program?id=coder_nft.aleo
any of it with a `mint` function

## Expected Behavior
I believe that if tx fails, the `snarkOS` should not show me the successful execution

## Your Environment
snarkOS Version `latest`
Rust Version `rustc 1.69.0 (84c898d65 2023-04-16)`
Computer OS `Win 10, VSC`

**Comment by duonghb53** [comment]
I also similar error panic when call a transition but snarkOS return transaction success and return tx. But I can't query tx on API

**Comment by web3zhangxianxing** [comment]
Similar error with Aleo transfer
Latest SnarkOS validator 
OS ubuntu 20.04
rustc 1.70.0 (90c541806 2023-05-31)

**Comment by GeassV** [comment]
Similar error with Aleo transfer
Latest SnarkOS validator
OS ubuntu 20.04
rustc 1.70.0 (90c541806 2023-05-31)

**Comment by LouisWT** [comment]
Similar error with Aleo transfer
Latest SnarkOS validator
OS macOS 13.4.1 
rustc 1.67.1 (d5a82bbd2 2023-02-07)

**Comment by GeassV** [comment]
> Similar error with Aleo transfer Latest SnarkOS validator OS ubuntu 20.04 rustc 1.70.0 (90c541806 2023-05-31)

the problem seems fixed with the latest version
