### ISSUE TITLE
[Bug] Scan will throw an error if scanned blocks contain a rejected transaction

### ISSUE THREAD

**Issue by pa-long** [AleoHQ/snarkOS#2528]
## 🐛 Bug Report
Command `snarkos developer scan` will throw an error if scanned blocks contain a rejected transaction.

## Steps to Reproduce

```bash
$ snarkos developer scan --endpoint https://vm.aleo.org/api --view-key AViewKey1hKNmqi83PpwjCTSSUCZT2rX3p3jcktNXzJZnk6rSqq4b --start 126012 --end 126013

Scanning 1 blocks for records (0.00% complete)...⚠️  Failed to read JSON: The "transitions" field is missing at line 698 column 1

```

Block 126013 contains the following transaction :
https://explorer.hamp.app/transaction?id=at1p3cm5qh6nxvwce9xrjqtqerpex54yhg9a8yd0v8kk7cu88r2lsysvyj0ms

## Fix proposals

- Add Rejected object support.
- Also, maybe `snarkos developer scan` should return the list of other records even if it encounters an error when parsing a specific transaction.

## Environment

- snarkOS v2.1.4

**Comment by raychu86** [comment]
The snarkOS v2.1.4 release is a bit out of date. In the meantime, before we update the release, installing `snarkOS` from the `testnet3` branch should address your current issue. Here are instructions for how to do that - https://github.com/AleoHQ/snarkOS/#22-installation.
