### ISSUE TITLE
[Bug] Failed to execute transaction but the fee record was consumed.

### ISSUE THREAD

**Issue by qbitshero** [AleoHQ/snarkOS#2544]
## 🐛 Bug Report

snarkos developer execute login_token.aleo create_user aleo18pfln645uyxsg5x7qq6pc4wca8gegkfgk83j9e89vllvlr8cccpq97l6sj 80000000u64 1u32  --private-key APrivateKey1zkp5Y4Ytn8mLaim2frzYJb5Ykv3SaTJxGuamByUyYYjf7Vb --query https://vm.aleo.org/api  --broadcast https://vm.aleo.org/api/testnet3/transaction/broadcast  --fee 30000 --record "{
  owner: aleo1s6axzuxkxz8ksxdzqpnvktglraf7k3mayt05lhx652vc5zw53gqs326sjn.private,
  microcredits: 50000000u64.private,
  _nonce: 7225816455519762967251178821077424510980221082157366912423366761854998709406group.public
}"

✅  Created execution transaction for 'login_token.aleo/create_user'
✅  Successfully broadcast execution at1adaanayd00yphpwd3sju08k7gh395lu8z7zldradhxpqgvjlwuxq6a4hek ('login_token.aleo/create_user') to https://vm.aleo.org/api/testnet3/transaction/broadcast.
at1adaanayd00yphpwd3sju08k7gh395lu8z7zldradhxpqgvjlwuxq6a4hek

But I could not find the transaction. 
Below was my test program's output. And I could not find it on explorer, too.
PS: sorry, I found the failure cause. But my fee record was lost.

INFO:root:request transaction: https://vm.aleo.org/api/testnet3/transaction/at1adaanayd00yphpwd3sju08k7gh395lu8z7zldradhxpqgvjlwuxq6a4hek
ERROR:root:Failed to get transaction at1adaanayd00yphpwd3sju08k7gh395lu8z7zldradhxpqgvjlwuxq6a4hek
ERROR:root:Response status: 500

The important is, the fee record was consumed. When I retry the operation, the result is following:

✅  Created execution transaction for 'login_token.aleo/create_user'
⚠️  ❌  Failed to broadcast execution 'login_token.aleo/create_user' to https://vm.aleo.org/api/testnet3/transaction/broadcast: (status code 500: "Something went wrong: Input ID '5028273612952064362526264097466310561165833438995000632823931682460855385036field' already exists in the ledger")

## Expected Behavior
When the transaction fails, the fee record should not be consumed.

## Your Environment

snarkOS Version:
commit 92106d623ce434a712ba802971d9d88a05c0fa85 (HEAD -> testnet3, tag: v2.1.4, origin/testnet3, origin/HEAD)
Author: Howard Wu <9260812+howardwu@users.noreply.github.com>
Date:   Thu Jun 29 13:52:06 2023 -0700

    chore(snarkos): bump version for new release

Rust Version:
rustc 1.70.0 (90c541806 2023-05-31)

Computer OS
ubuntu

**Comment by d0cd** [comment]
I see some rejected transactions here: https://explorer.hamp.app/program?id=login_token.aleo
Can you confirm that you attempted to execute a different transition?

**Comment by qbitshero** [comment]
> I see some rejected transactions here: https://explorer.hamp.app/program?id=login_token.aleo Can you confirm that you attempted to execute a different transition?

Yes, I found the failure cause. But my fee record was lost. If it is a feature, it will be dangerous to use fee record, especially when the amount is large.

**Comment by howardwu** [comment]
Is this related to the issue you opened a few weeks ago?
https://github.com/AleoHQ/snarkOS/issues/2477

Just as before, the fee record is not lost. If the transaction is rejected, the fee is still consumed. This is the same for every L1, as it is a DOS protection mechanism.

**Comment by qbitshero** [comment]
> Is this related to the issue you opened a few weeks ago? #2477
> 
> Just as before, the fee record is not lost. If the transaction is rejected, the fee is still consumed. This is the same for every L1, as it is a DOS protection mechanism.

Yes, I understand the feature if the remaining fee is not lost. The problem is different as #2477, in which I can find the transaction but not the fee in its output value. But now, I can't find the whole transaction. And it is not UI problem, I can't find it because the transaction id is invalid due to rejection. But how can I know the correct transaction id which consumed the fee ?

**Comment by qbitshero** [comment]
I found the fee record, but it is too difficult.
First, I found the block height on Haruka's Aleo Explorer.
Then I get the block by height, and search the transaction in the block.

**Comment by qbitshero** [comment]
Based on experts's comment, it is not a bug.  But it is not convenient for developer to find the remaining fee record when the transaction failed.

**Comment by howardwu** [comment]
We will look to make this UX better, thanks for the feedback.
