### ISSUE TITLE
Question about how to call the GPU for proofs

### ISSUE THREAD

**Issue by johnnychen8188** [AleoHQ/snarkOS#2708]
## 📚 Documentation

Hello community technicians, how do I use the official code for GPU calls, the documentation tells me that GPU is optional, so how do I choose to call it? Right now the default is to use the CPU for proofing and there is no call to the GPU to do the work, can anyone assist with an answer? Thanks.

**Comment by Amhaarec** [comment]
The same question

**Comment by OuIChien** [comment]
I have the same question

**Comment by raychu86** [comment]
The GPU impl can be used by manually updating the default snarkVM features used to include "cuda". Note that this will only work if you have a supported GPU with a compatible CUDA toolkit version.

An example - https://github.com/AleoNet/snarkOS/pull/2130
