### ISSUE TITLE
[Bug] scan fails

### ISSUE THREAD

**Issue by steliyannedev** [AleoHQ/snarkOS#2727]
## 🐛 Bug Report

unable to run snarkos develop scan command

## Steps to Reproduce

Running following `snarkos developer scan --endpoint https://vm.aleo.org/api --view-key <view_key> --start 0 --end 126013`
yields error
```
Scanning 126013 blocks for records (0.00% complete)...⚠️  Failed to read JSON: Failed to parse string. Parsing Error: VerboseError { errors: [("ar1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqgu0n07", Nom(OneOf)), ("ar1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqgu0n07", Nom(Many1))] } at line 437 column 3
```

## Expected Behavior

scan network for records

## Your Environment

-  v2.1.7
-  rustc 1.72.0
- MacBook - MacOS 13.4.1

**Comment by howardwu** [comment]
Related to #2743

**Comment by raychu86** [comment]
This should be resolved if you update your `--endpoint flag` to use `https://api.explorer.aleo.org/v1`

For example:

`--endpoint "https://api.explorer.aleo.org/v1"`

**Comment by steliyannedev** [comment]
@raychu86 nope, still getting the error
```
snarkos developer scan -p <priv-key> --last 50 --endpoint "https://api.explorer.aleo.org/v1"

Scanning 50 blocks for records (0.00% complete)...⚠️  Failed to read JSON: Failed to parse string. Parsing Error: VerboseError { errors: [("ar10h3jxq0s7dlv2lxam3fldrls5dk2f8z43nhsqs62dah7huqwfy8qtyvhj2", Nom(OneOf)), ("ar10h3jxq0s7dlv2lxam3fldrls5dk2f8z43nhsqs62dah7huqwfy8qtyvhj2", Nom(Many1))] } at line 842 column 3
```

**Comment by zklim** [comment]
> @raychu86 nope, still getting the error
> 
> ```
> snarkos developer scan -p <priv-key> --last 50 --endpoint "https://api.explorer.aleo.org/v1"
> 
> Scanning 50 blocks for records (0.00% complete)...⚠️  Failed to read JSON: Failed to parse string. Parsing Error: VerboseError { errors: [("ar10h3jxq0s7dlv2lxam3fldrls5dk2f8z43nhsqs62dah7huqwfy8qtyvhj2", Nom(OneOf)), ("ar10h3jxq0s7dlv2lxam3fldrls5dk2f8z43nhsqs62dah7huqwfy8qtyvhj2", Nom(Many1))] } at line 842 column 3
> ```

having same issue too
