### ISSUE TITLE
node/narwhal & sync dependency Error: statusCode=404

### ISSUE THREAD

**Issue by DylanCkawalec** [AleoHQ/snarkOS#2743]
## 🐛 Bug Report

SnarkOS compiles without crashing, but I suspect it causes issues later during the deployment of programs. I consistently encounter errors when using the 'snarkos developer deploy' command.

After updating SnarkOS, my dependencies are throwing a status 404 error, as shown below:

<img width="227" alt="Screenshot 2023-10-08 at 9 51 11 PM" src="https://github.com/AleoHQ/snarkOS/assets/43707795/b077006a-da81-4728-9b4a-471b4151ae0c">

## Steps to Reproduce

Errors occur when I run the deploy and execute instructions. After deploying a program that compiles successfully along with its associated Aleo instructions, I encounter the following errors:

```
📦 Creating deployment transaction for 'poems1peyra.aleo'...

⚠️  Failed to parse string. Parsing Error: VerboseError { errors: [("program_id: credits.aleo,\n  function_name: transfer_public,\n  arguments: [\n    aleo1g9th4mdhtc88eceqvcz8d70jwx48c88vmnh0xa2jnsdc00jx0q9scxmau6,\n    aleo1peyraee245wza0cc6822jrpr3m4ywq85s6979nypppxmtwsqmcyqg8g7ap,\n    50000000u64\n  ]\n}", Nom(Tag))] }
```

## Unexpected Behavior

When I request credits from the faucet, I am unable to find a record cipher. Instead, I receive a list of arguments and a single group in the tpk field. I attempted to combine them in the original order "owner, microcredits, _nonce", but this approach only yields the error shown below:

<img width="1405" alt="Screenshot 2023-10-08 at 10 01 03 PM" src="https://github.com/AleoHQ/snarkOS/assets/43707795/2e67b3f9-89a7-4c61-98bf-0363e42965b2">

## Your Environment

- **SnarkOS Version:** v2.1.7
- **Rust Version:** rustc 1.73.0; rustc 1.75.0-nightly
- **Computer OS:** MacOS / RELEASE_ARM64_T6020 arm64

**Comment by howardwu** [comment]
@raychu86 we need to change this to https://api.explorer.aleo.org/v1/testnet3

**Comment by howardwu** [comment]
@DylanCkawalec you're welcome to open a PR as well. It should be just a URL change.

**Comment by DylanCkawalec** [comment]
@howardwu  
After changing the broadcast api, 

```
📦 Creating execution transaction for 'poems1peyra.aleo/interpretations'...

⚠️  Something went wrong: Missing program for ID poems1peyra.aleo
```

do you know what is causing this? 

## continued
I've rebuilt the program from scratch, and was able to execute the `leo run interpretations` on my program's only transition. After changing the parameters to include https://api.explorer.aleo.org/v1/testnet3 in the --broadcast, the program file is not registering that I've build the prover and verifier files, along with the .aleo and .avm in /build

**Comment by raychu86** [comment]
This should be resolved if you update your `--query` flag to use `https://api.explorer.aleo.org/v1`

for example:

`--query "https://api.explorer.aleo.org/v1"`

**Comment by DylanCkawalec** [comment]
@raychu86  Hi thank you for response :) 
I found a continued error after this issue was closed. 

<img width="735" alt="Screenshot 2023-10-09 at 7 23 03 PM" src="https://github.com/AleoHQ/snarkOS/assets/43707795/2cfe6a89-bca6-4ba1-84da-c379789eb75c">

After two deployments, the https://vm.aleo.org/api/testnet3/transaction/broadcast  works, but the txid will not show up on the ledger. 

While https://api.explorer.aleo.org/v1/testnet3/transaction/broadcast cannot parse some kind of JSON somewhere. 

Back and forth, the first can execute without problem but the txid is missing, while the second link fails to parse the 'snarkos developer execute' and 'aleo execute'
<img width="739" alt="Screenshot 2023-10-09 at 7 30 53 PM" src="https://github.com/AleoHQ/snarkOS/assets/43707795/885dde58-2482-44cd-824d-0395bc1d0d36">


txid that was executed successfully, but the execution does not show : https://vm.aleo.org/api/testnet3/transaction/at1wthl26mkhzrd760xkd9fgykgw70psmylgm0v9q82qmwx7udwgg8q2h23n0
