### ISSUE TITLE
SnarkOS developer scan / deploy / execute doesn't work

### ISSUE THREAD

**Issue by zklim** [AleoHQ/snarkOS#2755]
## 🐛 Bug Report

snarkos developer scan / deploy / execute commands all giving errors

## Steps to Reproduce

Run command `snarkos developer deploy "${APPNAME}.aleo" --private-key "${PRIVATEKEY}" --query "https://api.explorer.aleo.org/v1" --path "./${APPNAME}/build/" --broadcast "https://api.explorer.aleo.org/v1/testnet3/transaction/broadcast" --fee 1000000 --record "${RECORD}"`

Result:
<img width="618" alt="Screenshot 2023-10-12 at 3 53 22 PM" src="https://github.com/AleoHQ/snarkOS/assets/53001910/a3428c9b-11bd-44cc-8e2c-d81ec6e1b734">

Run command `snarkos developer deploy "${APPNAME}.aleo" --private-key "${PRIVATEKEY}" --query "https://apiv2.aleo.network" --path "./${APPNAME}/build/" --broadcast "https://apiv2.aleo.network/testnet3/transaction/broadcast" --fee 1000000 --record "${RECORD}"`

`snarkos developer scan` and `snarkos developer execute` have similar errors too.

Result:
<img width="729" alt="Screenshot 2023-10-12 at 3 52 35 PM" src="https://github.com/AleoHQ/snarkOS/assets/53001910/f5782123-463c-4b5b-ae14-fb65e00f4b76">

## Expected Behavior

Deploy program onchain.

## Your Environment

- snarkOS Version: 2.1.7
- Rust Version: 1.26.0
- Computer OS: macOS Sonoma Version 14.0

**Comment by zklim** [comment]
execute error:
<img width="1308" alt="Screenshot 2023-10-12 at 5 11 50 PM" src="https://github.com/AleoHQ/snarkOS/assets/53001910/05daba61-dcaf-4f8f-b9ab-9e28883a9d03">

scan error:
<img width="1312" alt="Screenshot 2023-10-12 at 5 10 34 PM" src="https://github.com/AleoHQ/snarkOS/assets/53001910/8e55da23-07c1-4a3a-b2e8-6baa83c09d76">

**Comment by HarukaMa** [comment]
"invalid state path version" and failing to parse the new mapping grammar both indicates you are using old snarkOS from the previous network.

**Comment by zklim** [comment]
> "invalid state path version" and failing to parse the new mapping grammar both indicates you are using old snarkOS from the previous network.

I'm using snarkos v2.1.7

<img width="308" alt="Screenshot 2023-10-12 at 11 10 13 PM" src="https://github.com/AleoHQ/snarkOS/assets/53001910/3f1dc329-d44b-4562-b023-36248446329c">

**Comment by HarukaMa** [comment]
the version that supports the current network is not yet tagged; you will need to install from `testnet3` branch manually.

**Comment by zklim** [comment]
> the version that supports the current network is not yet tagged; you will need to install from `testnet3` branch manually.

Scan and execute work now! But having parsing error on <PROGRAM_ID> for deploy, I tried added double quotes and without. Do you know why?
<img width="950" alt="Screenshot 2023-10-13 at 1 25 18 AM" src="https://github.com/AleoHQ/snarkOS/assets/53001910/ea735a8a-bac4-437e-8284-d7dec295af0a">

*Edit: Ok, I was being dumb, it has to fill with suffix ".aleo". Cool everything works now!
