### ISSUE TITLE
https://vm.aleo.org/api request error

### ISSUE THREAD

**Issue by marco-storswift** [AleoHQ/snarkOS#2844]
## 🐛 Bug Report

when I run 
snarkos developer execute credits.aleo bond_public aleo1XXXX  50000000u64 --private-key "${PRIVATEKEY}" --query "https://vm.aleo.org/api" --broadcast "https://vm.aleo.org/api/testnet3/transaction/broadcast"
alway got the error
⚠️  <!DOCTYPE html>
        <html>
          <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <meta charset="utf-8">
                <title>Application Error</title>
                <style media="screen">
                  html,body,iframe {
                        margin: 0;
                        padding: 0;
                  }
                  html,body {
                        height: 100%;
                        overflow: hidden;
                  }
                  iframe {
                        width: 100%;
                        height: 100%;
                        border: 0;
                  }
                </style>
          </head>
          <body>
                <iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
          </body>
        </html>

## Expected Behavior
when I change to my rpc node every things is ok. 

## Your Environment

- 
2.2.4
- 
- rustc 1.75.0-nightly (49691b1f7 2023-10-16)
- 
mac

**Comment by howardwu** [comment]
Closing as this issue should be resolved now using `api.explorer.aleo.org`
