### ISSUE TITLE
[Bug] Leader withholding certificate halts the network

### ISSUE THREAD

**Issue by vicsn** [AleoHQ/snarkOS#2846]
## 🐛 Bug Report

When a malicious node withholds certificates when they are the leader + never shares certificates via PrimaryPing, they cause race conditions.

## Steps to Reproduce

Start `devnet.sh` on https://github.com/AleoHQ/snarkOS/tree/vicsn/fix/stress_test_2 and watch the magic, we tested different scenario's:
- (1) commit 0aff1f214, network starts from scratch
  - block production halts, `previous round 111 has not reached quorum`
- (2) commit 47954fc7c, network starts from scratch
  - block production continues but the malicious node does not advance its round and keeps resending `DEBUG Resending batch proposal for round 7 to peer` 
- (3) commit d55344988, network starts from scratch
  - block production of the 4th targeted honest node halts. For incoming transmissions node 4 prints `global state root not found`, and because node 4 is `Unable to fetch batch certificate` from the new leader it `did not elect a leader`. Interestingly, when letting the network run for a while, it is possible for the 4th node to rejoin the network briefly, after which it splits again.
  
Temporary halting of a single node still persists when rebased on [592bbd1](https://github.com/AleoHQ/snarkOS/commit/592bbd149e10c94a5338aa0c33cefe025bd618bd) 

[issue_1.zip](https://github.com/AleoHQ/snarkOS/files/13358104/issue_1.zip)
[issue_2.zip](https://github.com/AleoHQ/snarkOS/files/13358105/issue_2.zip)
[issue_3.zip](https://github.com/AleoHQ/snarkOS/files/13382511/issue_4.zip)

**Comment by ghostant-1017** [comment]
@vicsn 
Set `is_gateway_mode` false will disable all the nodes PrimaryPing. Is this your purpose?
https://github.com/AleoHQ/snarkOS/commit/0aff1f21407d547ea62223144f6e06491d6d6e05#diff-f82e0c9ecc0d4ff1e73050db6da1dc5909f4f8c5afc98d3effd254a440f079e3L314

Did you forget to change this back? Other nodes should not disable PrimaryPing.

**Comment by vicsn** [comment]
> @vicsn Set `is_gateway_mode` false will disable all the nodes PrimaryPing. Is this your purpose? [0aff1f2#diff-f82e0c9ecc0d4ff1e73050db6da1dc5909f4f8c5afc98d3effd254a440f079e3L314](https://github.com/AleoHQ/snarkOS/commit/0aff1f21407d547ea62223144f6e06491d6d6e05#diff-f82e0c9ecc0d4ff1e73050db6da1dc5909f4f8c5afc98d3effd254a440f079e3L314)
> 
> Did you forget to change this back? Other nodes should not disable PrimaryPing.

Thank you for the catch, I played around with this during testing, but the final attack works without halting PrimaryPing for all nodes.

**Comment by vicsn** [comment]
Closing as it should be fixed now, will make sure we have a test for this.
