### ISSUE TITLE
thread 'main' panicked at cli/src/commands/start.rs:447:22: internal error:  [Bug]

### ISSUE THREAD

**Issue by Escapeler** [AleoHQ/snarkOS#2893]
## 🐛 Bug Report

After run ./run-client.sh  

## Log Erorr

```
thread 'main' panicked at cli/src/commands/start.rs:447:22:
internal error: entered unreachable code: The number of cores is insufficient
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Checking for updates...
Saved working directory and index state WIP on testnet3: 21ff0b3 Merge pull request #2877 from AleoHQ/dependabot/cargo/openssl-0.10.60
Exiting...
````

## Expected Behavior

 Pending 30 minutes

## Your Environment

- snarkOS Version 2.2.5
- stable-x86_64-unknown-linux-gnu version 12
- Ubuntu 22.04 LTS
img width="499" alt="Screenshot 2023-12-04 230624" src="https://github.com/AleoHQ/snarkOS/assets/77755744/c68b04f1-f183-4768-bd55-13b3a030da6a"

**Comment by elderhammer** [comment]
Please specify your operating system.
I guess you are running a virtual machine, and the virtual machine has less than 4 cores.
Please use a device with at least 4 cores and above.

**Comment by Escapeler** [comment]
hi i used ubuntu 22.04 LTS , 16gb ram with 6 cores

**Comment by ljedrz** [comment]
Closing the issue; we just prohibit nodes that don't fulfill the core count requirements as a policy.
