### ISSUE TITLE
[Bug] Global state root not found

### ISSUE THREAD

**Issue by supriya-u410** [AleoHQ/snarkOS#2911]
## 🐛 Bug Report

Snarkos is trying to do fee verification for the invalid prover solution transactions and errors with `Fee verification failed: global state root not found`. 

## Steps to Reproduce

git commit:               `4896a1200a4605d1de6fe6cb53e1efa9ccdb6152`
Sanrkos Command: `snarkos start --nodisplay --verbosity 1  --private-key-file private.key --validator --validators ${local.peers}`

## Expected Behavior

Ignoring unconfirmed transaction since it is invalid prover solution

###  Error Logs
```
2023-12-11T07:39:40.661637Z  WARN Failed to add unconfirmed solution 'puzzle1748a7tsl9..' to the memory pool - Invalid unconfirmed solution 'puzzle1748a7tsl9..': Invalid prover solution 'puzzle1748a7tsl9ahgvu54gr32wuygx7zhlfrd8hascu5k5p43323ygn770qky4qwlfggsc7yjpd2n7paqqsr56dw' for the current epoch.
2023-12-11T07:39:41.538010Z  WARN Failed to add unconfirmed transaction 'at1jwkwhx9lvrays..' to the memory pool - Invalid unconfirmed transaction 'at1jwkwhx9lvrays..': Fee verification failed: global state root not found
```

## Your Environment

- snarkOS Version: `4896a1200a4605d1de6fe6cb53e1efa9ccdb6152` on testnet3 branch

- Rust Version
```
rustup 1.26.0 (5af9b9484 2023-04-05)
cargo 1.74.1 (ecb9851af 2023-10-18)
rustc 1.74.1 (a28077b28 2023-12-04)
```

-  Computer OS
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

**Comment by elderhammer** [comment]
I'm afraid you misunderstood: the invalid prover solution is not included in the unconfirmed transaction

**Comment by HarukaMa** [comment]
Those 2 errors are actually 2 different errors - prover solutions are *not* transactions. Also I'm not sure what's the "bug" here - the node *is supposed* to verify incoming prover solutions and transactions, and those invalid ones will be ignored by the node.

**Comment by supriya-u410** [comment]
Thank you for the responses. Agreed on the invalid prover solutions not being included but I see `Fee verification failed: global state root not found` for invalid transactions. I am trying to understand Should the node be persisting the state root info? or should it verify fee for invalid transactions?

**Comment by HarukaMa** [comment]
The "global state root" is the root of block hash merkle tree and indicates the reference point of the transaction. It is tracked by nodes.

> should it verify fee for invalid transactions?

You can't tell if the transaction is valid if you don't verify the fee - this error indicates the invalid fee transition caused the transaction to be invalid.
