### ISSUE TITLE
[Feature] Improve node startup time?

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkOS#2917]
## 🚀 Feature

The client node currently takes way too long to start - I'm measuring a 4-minute loading time with zero output to indicate what the node is doing.

## Motivation

Restarting the node is becoming PITA with the longer startup time. Especially important for service providers as well.

## Implementation

Dunno TBH, haven't profiled it.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Not sure.

**Comment by ljedrz** [comment]
I'll bring https://github.com/AleoHQ/snarkVM/pull/1606 up to date, it should speed it up.

**Comment by ljedrz** [comment]
I just tested it with a fully synced client node, and indeed, it speeds things up.
- baseline (testnet3): 119.45s
- with the linked snarkVM PR: 41.75s (-65%)

**Comment by HarukaMa** [comment]
I've confirmed that PR significantly speeds up the startup time, and it scales especially well with high core counts.

The remaining feature request would be to provide some feedback on what the node is trying to do - even with verbosity 3 there is only a "Starting a client node" message.

**Comment by HarukaMa** [comment]
From https://github.com/AleoHQ/snarkOS/pull/2903#issuecomment-1857601811:

Sometimes the following panic happens and the node stops syncing:

```
thread 'tokio-runtime-worker' panicked at 'assertion failed: self.database.atomic_batch.lock().is_empty()', /home/mrx/snarkVM/ledger/store/src/helpers/rocksdb/internal/map.rs:111:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-12-15T09:19:18.114699Z  WARN snarkos_node::client::router: Disconnecting from '...' - task 70531 panicked  
```

then:

```
2023-12-15T09:19:20.478289Z  WARN snarkos_node_sync::block_sync: The next block (969045) is invalid - Cannot start an atomic batch write operation while another one is already in progress.
```

If this is not caused by that PR, is it possible that this is introduced by the snarkVM PR instead?

**Comment by ljedrz** [comment]
The startup speed-up one? I don't think so, it's most likely a separate new issue.

**Comment by HarukaMa** [comment]
strange, lemme try to isolate this then. I'm getting another strange panic right now:

```
thread 'tokio-runtime-worker' panicked at 'assertion failed: previous_atomic_depth != 0', /home/mrx/snarkVM/ledger/store/src/helpers/rocksdb/internal/map.rs:217:9                                                note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'll try to revert some commits to see which one caused this.

**Comment by ljedrz** [comment]
>The remaining feature request would be to provide some feedback on what the node is trying to do - even with verbosity 3 there is only a "Starting a client node" message.

Done.

**Comment by HarukaMa** [comment]
closing as the snarkvm pr is closed
