### ISSUE TITLE
[Bug] Stopping the node would still sometimes leads to corrupted storage

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkOS#2944]
## 🐛 Bug Report

Something like
```
2023-12-22T17:58:07.627209Z  WARN snarkos_node_sync::block_sync: The next block (1021492) is invalid - Failed to speculate on transactions - Failed to post-ratify - Next height must be sequential
```
after restarting the node. Fortunately I'm testing the storage location PRs so I have other copies, but considering syncing is rather slow right now this would be a pain if I have to restart from snapshots.

## Steps to Reproduce

Restart node when advancing blocks? not entirely sure

## Expected Behavior

This should not happen.

## Your Environment

- testnet3 + custom storage location
- 
-

**Comment by ghostant-1017** [comment]
Related to https://github.com/AleoHQ/snarkVM/issues/2218

**Comment by ljedrz** [comment]
I think this issue can be closed in favor of https://github.com/AleoHQ/snarkOS/issues/2974; please feel free to reopen if it's distinct enough.
