### ISSUE TITLE
[Bug] Deployment Failure Due to Method Call with Record Parameter from Another Program

### ISSUE THREAD

**Issue by snowtigersoft** [AleoHQ/snarkOS#3020]
## 🐛 Bug Report

I encountered an error when deploying the following Leo program on snarkOS. The program is designed to execute a private credit transfer using the `credits.aleo/transfer_private` function. However, upon deployment, the snarkOS node logs displayed an error related to the synthesis of the circuit for the transfer transition. The error message specifically mentions a failure in executing the instruction call `credits.aleo/transfer_private` and indicates an "Illegal operation: Record::encrypt() randomizer does not correspond to the record nonce." This suggests an issue with the handling of record encryption or nonce alignment in the `credits.aleo/transfer_private` function. The Leo program appears to be correctly written and should not result in such an error.
```rust
// The 'js8xxlq9d' program.
import credits.aleo;

program js8xxlq9d.aleo {
    transition transfer(credit: credits.aleo/credits, c1: u64, c2: u64, r: [address; 10]) {
        let (x1, y1) : (credits, credits) = credits.aleo/transfer_private(credit, r[0u8], c1);
        let (x2, y2) : (credits, credits) = credits.aleo/transfer_private(y1, r[0u8], c2);
    }
}
```

Aleo instruction:
```aleo
import credits.aleo;
program js8xxlq9d.aleo;

function transfer:
    input r0 as credits.aleo/credits.record;
    input r1 as u64.private;
    input r2 as u64.private;
    input r3 as [address; 10u32].private;
    call credits.aleo/transfer_private r0 r3[0u32] r1 into r4 r5;
    call credits.aleo/transfer_private r5 r3[0u32] r2 into r6 r7;
```

## Steps to Reproduce

1.  Write the above Leo program that includes a transition calling the `credits.aleo/transfer_private` function.

2. Deploy the program on a snarkOS node.

3. Observe the error in the node logs during deployment.

### Error Message
The error message received is as follows:
```bash
2024-01-20T07:29:35.002717Z  WARN Failed to add unconfirmed transaction 'at1hg67632nu3h0l..' to the memory pool - Invalid unconfirmed transaction 'at1hg67632nu3h0l..': Deployment verification failed - Failed to synthesize the circuit for 'transfer': Failed to execute instruction (call credits.aleo/transfer_private r0 r3[0u32] r1 into r4 r5;): Illegal operation: Record::encrypt() randomizer does not correspond to the record nonce.
```

## Expected Behavior

The expected behavior is the successful deployment of the Leo program without encountering synthesis errors. The `credits.aleo/transfer_private` function should handle record encryption and nonce alignment correctly, allowing for seamless execution of private credit transfers.

## Your Environment

- snarkOd: v2.2.7 (build from the latest code)
- cargo 1.73.0 (9c4383fb5 2023-08-26)
- MacOS 14.2.1

**Comment by raychu86** [comment]
Closing this issue as it should be addressed by https://github.com/AleoHQ/snarkVM/pull/2321.
