### ISSUE TITLE
Shutdown during CDN sync can corrupt block store

### ISSUE THREAD

**Issue by kyle-u410** [AleoHQ/snarkOS#3027]
## 🐛 Bug Report

Once the node is initialized then shutdown seems to work correctly. However when performing catchup from CDN, there is no waiting for the CDN process to stop. This is more common with recent snapshots than when CDN syncing from genesis.

The [CDN does check a shutdown flag](https://github.com/AleoHQ/snarkOS/blob/109acbbdde94cb99d6645b99165a36ac963fdee7/node/cdn/src/blocks.rs#L158), but it does not correctly implement shutdown. Additionally the code should:
- Check at the point where the store is being modified, not where next set of buffered blocks are to be fetched.
- Wait for store modification to complete instead of a [3 second delay](https://github.com/AleoHQ/snarkOS/blob/109acbbdde94cb99d6645b99165a36ac963fdee7/node/src/traits.rs#L74) and then hard stop.

## Steps to Reproduce

1. Start `snarkos` in `--client` mode using a recent snapshot.
2. Wait until CDN sync is under way.
3. Send `SIGINT` to `snarkos` to trigger shutdown.
4. Restart `snarkos` and see block failure messages.

## Expected Behavior

There is a way to safely shutdown the `snarkos` process at any point without causing corruption.

## Your Environment

- https://github.com/AleoHQ/snarkOS/commit/2f9f0b5ee4ac7fdba272fca808d0ef26dc026b70
- rustc 1.75.0 (82e1608df 2023-12-21)
- 22.04.1-Ubuntu

**Comment by ljedrz** [comment]
This is fixed with https://github.com/AleoHQ/snarkOS/pull/3017.

**Comment by ljedrz** [comment]
Since the fixing PR has been merged, I'm closing this issue; please feel free to reopen if it happens again, though.

**Comment by kyle-u410** [comment]
Thanks!
