### ISSUE TITLE
Build ubuntu [Bug]

### ISSUE THREAD

**Issue by kvernet** [AleoHQ/snarkOS#3028]
## 🐛 Bug Report

The ./build_ubuntu.sh script produces the following error.
![Screenshot from 2024-01-22 21-08-00](https://github.com/AleoHQ/snarkOS/assets/53263986/e5412c24-5356-42bf-b6d3-e7be46327bce)

## Steps to Reproduce

Following the instructions in the README file.

## Expected Behavior

I expected that the compilation succeeds before running cargo install --path .

## Your Environment

Rust Version : rustc 1.75.0 (82e1608df 2023-12-21)
Computer OS : Ubuntu 22.04

**Comment by nomadnft69** [comment]
i have the same issue any fixes?

**Comment by joske** [comment]
reproduced. Looking into this.

**Comment by joske** [comment]
duplicate of #3023, closing this one.
