### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by nomadnft69** [AleoHQ/snarkOS#3030]
## Your Environment

- 
- 
- 
issue when 

trying to isstall node.

For more information about this error, try `rustc --explain E0308`.
error: could not compile `snarkvm-ledger-store` (lib) due to previous error
error: failed to compile `snarkos v2.2.7 (/root/snarkOS)`, intermediate artifacts can be found at `/root/snarkOS/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
root@vmi1617775:~/snarkOS# snarkos account new

**Comment by joske** [comment]
another dup of #3023
