### ISSUE TITLE
[Bug] Key permission check is too strict

### ISSUE THREAD

**Issue by HarukaMa** [AleoHQ/snarkOS#3038]
## 🐛 Bug Report

I'm calling this a bug as the logic is... strange.

### 1. The private key file

`go-rwx` is good, but the current code forces it to be `600`. `400` would fail the check, which is not reasonable. `x` shouldn't really matter here (although it shouldn't be there in the first place).

### 2. The folder that the key file resides in

Why?

## Steps to Reproduce

Run the node with private key file, with *and* without thinking too much about the permission. Most likely you will still hit the check no.2.

## Expected Behavior

`go-rwx` on the key file itself should be more than enough. You have other problems if the file content could be leaked with that permission.

## Your Environment

- 
- 
- 

## Notes

If the folder doesn't have sticky bit set, it's possible the key file could be deleted by others, but the key content, provided that the correct file permission is set, should be safe.

NCC report E009544 is not public, so I don't know the rationale behind the folder permission thing. I've never seen such requirements before though.

**Comment by joske** [comment]
Well, the rationale is to be similar to ssh. The `.ssh` folder has to have 0700 permissions, private key 0600 and public keys 0644 or it won't work. 

On the file, `x` doesn't make any sense, it's not executable (well, it really shouldn't be). Arguably 0400 would also be fine (but why would you take away write permission from yourself).

I'm still inclined to close this, as the permissions we require seem correct to me.

**Comment by HarukaMa** [comment]
Guess I'll just comment out the check for my own nodes as I'm putting the key to `~` and don't want to change the permission just for the node.
