### ISSUE TITLE
CDN range check

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#3043]
@ljedrz can you confirm that the interfaces do not have any changes for the block height?

I see that the tests needed to be updated to reflect new range changes. This will cause breakages downstream for the Explorer, faucet, and all developers using the CDN to date.

_Originally posted by @howardwu in https://github.com/AleoHQ/snarkOS/issues/3017#issuecomment-1913922168_

**Comment by ljedrz** [comment]
The 2 test cases that used to start at `0` were updated to `1`, so the only change I anticipate at 1st glance is at the very first range and when called from the node, but I will double-check.

**Comment by ljedrz** [comment]
You're right, the initial implementation was node-centric and would skip the genesis block, which is not a given outside of an existing `Ledger`; I filed a fix and changed one of the aforementioned 2 tests back to its previous form, while leaving the other one unchanged, just to make sure that the starting height of `1` - which applies to all fresh nodes - also works as expected.
