### ISSUE TITLE
[Bug] error: could not compile `hoot` (lib) due to 6 previous errors

### ISSUE THREAD

**Issue by jkdi** [AleoHQ/snarkOS#3047]
| ------------------------ `types::Private` declared as crate-private
...
19 | pub trait Method: Private {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak crate-private trait

error[E0445]: crate-private trait `types::Private` in public interface
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hoot-0.1.2/src/types.rs:42:1
   |
7  | pub(crate) trait Private {
   | ------------------------ `types::Private` declared as crate-private
...
42 | pub trait BodyType: Private {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak crate-private trait

error[E0446]: crate-private type `Writer<'_, '_>` in public interface
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hoot-0.1.2/src/header.rs:60:1
   |
60 | / pub fn check_and_output_header(
61 | |     mut w: Writer,
62 | |     version: HttpVersion,
63 | |     name: &str,
64 | |     bytes: &[u8],
65 | |     trailer: bool,
66 | | ) -> Result<()> {
   | |_______________^ can't leak crate-private type
   |
  ::: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hoot-0.1.2/src/out.rs:42:1
   |
42 |   pub(crate) struct Writer<'b, 'a> {
   |   -------------------------------- `Writer<'_, '_>` declared as crate-private

error[E0446]: private type `CallState` in public interface
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hoot-0.1.2/src/body.rs:10:1
    |
10  | / pub fn do_read_body<'a, 'b>(
11  | |     state: &mut CallState,
12  | |     src: &'a [u8],
13  | |     dst: &'b mut [u8],
14  | | ) -> Result<BodyPart<'b>> {
    | |_________________________^ can't leak private type
    |
   ::: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hoot-0.1.2/src/lib.rs:106:1
    |
106 |   pub(crate) struct CallState {
    |   --------------------------- `CallState` declared as private

Some errors have detailed explanations: E0445, E0446.
For more information about an error, try `rustc --explain E0445`.
error: could not compile `hoot` (lib) due to 6 previous errors
warning: build failed, waiting for other jobs to finish...

**Comment by joske** [comment]
Is this during snarkOS compilation? I can not reproduce this. Did you run `cargo update` manually?

**Comment by jkdi** [comment]
this is after ./run-prover.sh

**Comment by jkdi** [comment]
it's ubuntu 22.04

**Comment by joske** [comment]
can not reproduce (macOS, but should not matter), try `git reset --hard` followed by `cargo clean`, then try again.

**Comment by ljedrz** [comment]
`hoot`? Where did it come from? I don't see it anywhere in the snarkOS lockfile.

**Comment by jkdi** [comment]
> can not reproduce (macOS, but should not matter), try `git reset --hard` followed by `cargo clean`, then try again.

ok, now it works... thx!

**Comment by joske** [comment]
@jkdi best not to run `cargo update` as then you pull in untested dependencies.
