### ISSUE TITLE
Expected type did not match the received type

### ISSUE THREAD

**Issue by Whales1992** [AleoHQ/snarkOS#3053]
## 🐛 Bug Report

There is a return type error that is preventing the application from building 

## Steps to Reproduce

sudo /home/ubuntu/.cargo/bin/cargo install --path .

## Expected Behavior

It is supposed to run smoothly and I will then have access to "snarkos account new" but that did not happen, instead I got the above error.

## Your Environment

- git clone https://github.com/AleoHQ/snarkOS.git --depth 1 which should be pointing to the latest release I assume
- rustc 1.72.1 (d5c2e9c34 2023-09-13)
- Ubuntu 22

Note: I have attached a link to screenshot of the error.
https://photos.app.goo.gl/RoLNHRsJ4wdqATXm9

**Comment by BeckerFelix** [comment]
Same issue here, on `1d942fdc3924b401f1381f73624301b139df3067`

stacktrace of `sudo ./build_ubuntu.sh`:
```bash
   Compiling snarkos v2.2.7 (/home/tom/snarkOS_aleo_node)
error[E0308]: mismatched types
   --> node/rest/src/lib.rs:115:54
    |
115 |                 .error_handler(|error| Response::new(error.to_string()))
    |                                        ------------- ^^^^^^^^^^^^^^^^^ expected `Body`, found `String`
    |                                        |
    |                                        arguments to this function are incorrect
    |
note: associated function defined here
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-1.0.0/src/response.rs:253:12
    |
253 |     pub fn new(body: T) -> Response<T> {
    |            ^^^
help: call `Into::into` on this expression to convert `std::string::String` into `Body`
    |
115 |                 .error_handler(|error| Response::new(error.to_string().into()))
    |                                                                       +++++++
```

**Comment by BeckerFelix** [comment]
will be fixed with https://github.com/AleoHQ/snarkOS/pull/3056

**Comment by ljedrz** [comment]
The current fix is the second commit in https://github.com/AleoHQ/snarkOS/pull/3050.

**Comment by ljedrz** [comment]
Fixed with https://github.com/AleoHQ/snarkOS/pull/3050.
