### ISSUE TITLE
Whats the issue?

### ISSUE THREAD

**Issue by idontusehax1** [AleoHQ/snarkOS#3055]
https://github.com/AleoHQ/snarkOS/blob/1d942fdc3924b401f1381f73624301b139df3067/node/rest/src/lib.rs#L115
![image](https://github.com/AleoHQ/snarkOS/assets/114235868/cd153067-19a6-41cb-ac14-0a0e7a7934a4)

**Comment by BeckerFelix** [comment]
duplicate of https://github.com/AleoHQ/snarkOS/issues/3053

**Comment by demoso** [comment]
me too 
![image](https://github.com/AleoHQ/snarkOS/assets/29779275/bbe741c8-99f2-45ad-bd57-c7c8ea9e9f21)

**Comment by demoso** [comment]
Linux iZrj94x9iunw7yki5u7tioZ 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ljedrz** [comment]
Closing as duplicate.
