### ISSUE TITLE
[Bug] ./run-client.sh fail to compile

### ISSUE THREAD

**Issue by Taito-1009** [AleoHQ/snarkOS#3068]
## 🐛 Bug Report

I have been able to do the full installation process (all the steps until cargo install --locked --path ."
Trying to run "./run-client.sh" it keeps failing (same bug message than what was fixed in the build_ubuntu.sh command : https://github.com/AleoHQ/snarkOS/pull/3050

error message : 
 Compiling snarkos-node-rest v2.2.7 (/root/snarkOS/node/rest)
error[E0308]: mismatched types
   --> node/rest/src/lib.rs:115:54
    |
115 |                 .error_handler(|error| Response::new(error.to_string()))
    |                                        ------------- ^^^^^^^^^^^^^^^^^ exp                                                                                                                                                             ected `Body`, found `String`
    |                                        |
    |                                        arguments to this function are inco                                                                                                                                                             rrect

## Steps to Reproduce

git clone https://github.com/AleoHQ/snarkOS.git --depth 1
cd snarkOS
./build_ubuntu.sh
cargo install --locked --path .
./run-client.sh --> NOT COMPILING

## Expected Behavior

The command ./run-client.sh is supposed to compile without errors

## Your Environment

snarkos v2.2.7
rust 1.72.1
Ubuntu 20.04 (64 Bit)

**Comment by ljedrz** [comment]
This is already fixed in `testnet3`; please update your branch and run `cargo clean`.
