### ISSUE TITLE
[Bug] ./run-prover.sh breaks compilation when checking for updates 

### ISSUE THREAD

**Issue by kenrickl** [AleoHQ/snarkOS#3070]
## 🐛 Bug Report

"./run-prover.sh" fails to compile.

I have been able to do the full installation process until "./run-prover.sh".

**The first error happens at "Updating crates.io index"**
error: package `clap_builder v4.5.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.1
Either upgrade to rustc 1.74 or newer, or use
cargo update -p clap_builder@4.5.0 --precise ver
where `ver` is the latest version of `clap_builder` supporting rustc 1.72.1

looking into rustc versions, it seems that ~/snarkOS/rust-toolchain defines 1.72.1. Manually changing this to 1.74 allows to re-run "./run-prover.sh" and go beyond this error. However...

**The second error happens at "Compiling snarkos-node-rest v2.2.7"**
error[E0308]: mismatched types
   --> node/rest/src/lib.rs:115:54
    |
115 |                 .error_handler(|error| Response::new(error.to_string()))
    |                                        ------------- ^^^^^^^^^^^^^^^^^ expected `Body`, found `String`
    |                                        |
    |                                        arguments to this function are incorrect

looking back at the ~/snarkOS/rust-toolchain file, it is back to 1.72.1.
the error seems similar to #3068.

## Steps to Reproduce

git clone https://github.com/AleoHQ/snarkOS.git --depth 1
cd snarkOS
./build_ubuntu.sh
cargo install --locked --path .
./run-prover.sh --> first error
manually change rust-toolchain file to 1.74
./run-prover.sh --> second error

## Expected Behavior

The command ./run-prover.sh is supposed to compile without errors

## Your Environment

snarkos v2.2.7
rust 1.72.1
Ubuntu 22.04, fresh install.

**Comment by SeloSlav** [comment]
I'm also getting the same error. I've been trying to run one of these prover nodes for a week now. Came from a twitter thread.

I get 

.run-prover.sh: line 36: cargo: command not found
Saved working directory and index state WIP on testnet3: 937150e Merge pull request #3050 from eqlabs/fix/ubuntu-script

**Comment by ljedrz** [comment]
> `clap_builder v4.5.0`

You seem to be below https://github.com/AleoHQ/snarkOS/commit/937150eae125bd4d7c4b196d82acfe8f3390a035; do `cargo clean`, `git pull` and retry.

**Comment by kenrickl** [comment]
thanks for the suggestion.

after `cargo clean` then `git pull`, I am on testnet3 branch. However, still getting the rustc 1.74 error:

package `clap_lex v0.7.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.1

**Comment by ljedrz** [comment]
How are you building snarkOS?

**Comment by kenrickl** [comment]
I'm building using `./build_ubuntu.sh`.

then `cargo install --locked --path .`

**Comment by ljedrz** [comment]
Two points:
- `build_ubuntu` already performs installation (with `--locked`), so there is no need to run any further commands for that
- I just performed `cargo install --locked --path .` locally and there were no issues; as expected, because `--locked` ensures that the same lockfile is used as the one in the repo, and that one has all the matching dependencies

Make sure that your branch is in fact `testnet3` and that the latest commit is https://github.com/AleoHQ/snarkOS/commit/937150eae125bd4d7c4b196d82acfe8f3390a035.

**Comment by kenrickl** [comment]
I'm re-running now with an explicit `git checkout 937150e`.

the issue does not happen while running `./build_ubuntu.sh` or `cargo install --locked --path .`, these can build successfully. In the last re-run, I skipped the `cargo install` as it is indeed within `build_ubuntu`.

The issue occurs when running the `./run-prover.sh`, output:
`Checking for update` -> confirms no local changes to save
`Updating crates.io index` and immediately the error:
`error: package 'clap_lex v0.7.0' cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.1
Either upgrade to rustc 1.74 or newer, or use
cargo update -p clap_lex@0.7.0 --precise ver
where 'ver' is the latest version of 'clap_lex' supporting rustc 1.72.1`

Could you confirm which rustc version should be used in building? Both `Cargo.toml` and `rust-toolchain` in `testnet3` branch point to 1.72.1. If that is true, I'm wondering why it tries to install `clap_lex v0.7.0`...

**Comment by ljedrz** [comment]
For now the `1.72.1` version is sufficient.

Ok, so the issue is not initial compilation, but running; the update loop in that script seems too aggressive, I'll propose that it is adjusted. For now you can work around it by deleting everything in that script from line 38 down.

**Comment by kenrickl** [comment]
thanks, that makes sense. I also find that `clap_lex v0.7.0` is updated ~5hrs ago, so that's probably why. Will try again with a fresh clone and feedback in a min.

**Comment by kenrickl** [comment]
thanks, removing everything down from line 38 did it!
