### ISSUE TITLE
I accidentally did not save the private key

### ISSUE THREAD

**Issue by earnbuzz** [AleoHQ/snarkOS#3125]
## Implementation

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
I accidentally did not save the private key. How can I get the private key?

**Comment by Viktor110** [comment]
> ## 🚀 Feature
> 
> 
> 
> 
> 
> 
> 
> ## Motivation
> 
> 
> 
> 
> 
> 
> 
> ## Implementation
> 
> 
> 
> 
> 
> 
> 
> **Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
> 
> I accidentally did not save the private key. How can I get the private key?

**Comment by niklaslong** [comment]
I don't think this is something we can solve for at the moment. We could consider storing generated accounts but this isn't in scope for snarkOS. Closing for now.
