### ISSUE TITLE
This PR adjusts the placement of blocking tasks in the `primary` module based on how long the blocking operations can take, so that we avoid blocking the async executor.

### ISSUE THREAD

**Issue by Viktor110** [AleoHQ/snarkOS#3128]
This PR adjusts the placement of blocking tasks in the `primary` module based on how long the blocking operations can take, so that we avoid blocking the async executor.

_最初由 @ljedrz 在 https://github.com/AleoHQ/snarkOS/pull/3121 发布_

**Comment by ljedrz** [comment]
Since its test-only code,, there is no need for an associated issue, especially one with identical contents.

edit: it's another PR (non-test code), but this issue doesn't provide added value.
