### ISSUE TITLE
[Bug]  unable to connect '45.55.201.80:4130'

### ISSUE THREAD

**Issue by zisheng6** [AleoHQ/snarkOS#3138]
我按教程进行了配置 但是无法同步节点  端口我也已经打开，依旧不行

**Comment by joske** [comment]
Please write in English, I can only read the wǒ in the beginnging 😅

**Comment by wybiacx** [comment]
I have also encountered the corresponding problem, after running the prover node according to the official tutorial, the following problem occurs:

![image](https://github.com/AleoHQ/snarkOS/assets/24806554/9df96563-32c0-4924-a9ec-d5ad9690bd91)


Is this normal, please? I have this problem on other machines as well.

**Comment by AnsonCode** [comment]
same as you .

![image](https://github.com/AleoHQ/snarkOS/assets/20960032/1638e135-86aa-4ca8-81ae-447a02e69150)
![image](https://github.com/AleoHQ/snarkOS/assets/20960032/cfeb2b38-7648-4640-93ba-ba9504aebe00)

**Comment by AnsonCode** [comment]
can't reach this server.

```
ping 34.150.221.166
PING 34.150.221.166 (34.150.221.166) 56(84) bytes of data.
hang...
```

**Comment by AnsonCode** [comment]
Switch to testnet3 branch,run `./run-prover.sh`, still reporting an error.


![image](https://github.com/AleoHQ/snarkOS/assets/20960032/74abc7ed-dcb9-4dfa-a6ba-fb837b9e0c6c)

**Comment by AnsonCode** [comment]
> Switch to testnet3 branch,run `./run-prover.sh`, still reporting an error.
> 
> ![image](https://private-user-images.githubusercontent.com/20960032/318162710-74abc7ed-dcb9-4dfa-a6ba-fb837b9e0c6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Njg2MTYsIm5iZiI6MTcxMTc2ODMxNiwicGF0aCI6Ii8yMDk2MDAzMi8zMTgxNjI3MTAtNzRhYmM3ZWQtZGNiOS00ZGZhLWE2YmEtZmI4MzdiOWUwYzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDAzMTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOGU2YmFiMzI2OTYzZjkxZjIyYTIyYTAyNmNmZjM5NDZmYmNlNWY5NWNkOTBjYWEwNGRkZTQzZGE3N2VmMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x4oAOCXiSFaEgSbFcxkrjKbSfnDI68TuW1QcTUke6aM)


The following error was reported during the execution of the script, but it later worked properly.

`./run-prover.sh`

![image](https://github.com/AleoHQ/snarkOS/assets/20960032/9e847cd6-2d41-4e53-9ecc-352afa3af504)

**Comment by raychu86** [comment]
Closing this issue as the networks have been updated. If you are still experiencing a problem, feel free to open another issue.
