### ISSUE TITLE
Add limits on program struct definitions

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#3141]
There was a dummy program written which sized up to 50MBs by leveraging the struct construction.

Following this discussion, the decision was made to reduce the number of structs that can be defined in a program, and to bound any other constructs of a program so that the size of a program is inherently restricted.

@vicsn and @d0cd will be responsible with implementing a PR to contain this.

_Originally posted by @howardwu in https://github.com/AleoHQ/snarkOS/issues/3124#issuecomment-1974921008_

**Comment by vicsn** [comment]
I did not do a full analysis of all potential ways in which program sizes can be bloated - and suggest we just impose a limit on the total number of characters of the program so that we don't have to spend a week of engineering days analysing different attack vectors.

**Comment by vicsn** [comment]
@miazn I recall some time ago you looked into programs being deployed on testnet3, would it be possible to get an estimate about the maximum number of structs and closures used, as well as the maximum number of characters? Or do you have a link to some of these biggest programs?

**Comment by miazn** [comment]
@vicsn Yes, I can look into this-- by closures you mean explictly when something is called using `closure`? https://developer.aleo.org/aleo/language/#closure

I dont have this info on hand and it may take a day or two to get, if that's alright
