### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by gouravghosh02** [AleoHQ/snarkOS#3176]
## Your Environment

- 
- 
- 
![Screenshot_2024-03-18-17-52-17-883_com.yandex.browser.jpg](https://github.com/AleoHQ/snarkOS/assets/88235006/726c3116-1afb-4dad-a2bd-f2e0119bf218)

Bridge Pending problem
Transaction Hash:

0x0bc0a62833a04e81fc15363ca2098ba229cad31431d39e455ab1e1aa4ac2ee30 

Aleo address - aleo152p4q762mcvjtjzgqlcgpfym8dm6ghlsrjrmv04uaw9tz0q7hvqs424lrz
Metamask address- 0x3814bc997f9d863976959fb71581d5de52def287
Solve issu

**Comment by ljedrz** [comment]
Can you please elaborate?

**Comment by ljedrz** [comment]
Closing the issue due to inactivity and lack of further information.

**Comment by gouravghosh02** [comment]
Currently point update issu facing
