### ISSUE TITLE
[Bug] Expire or persist Batch Proposals

### ISSUE THREAD

**Issue by vicsn** [AleoHQ/snarkOS#3197]
## 🐛 Bug Report

We should make sure all validators have consistent views of Batch Proposals. As such we should either expire or persist Batch Proposals. 

## Steps to reproduce:
1. validator A sends Batch Proposal to validator B
2. validator A restarts
3. validator A sends a new Batch proposal to validator B
4. valdiator B disconnects from validator A with "Malicious peer - proposed another batch for the same round"

## Other concerns
We should have tests in place for this, and we should also check and test whether we are expiring/persisting certificates correctly.

## Your Environment

snarkOS commit: 1e445b56358010c9f754ee03d11ff3547b6d439a

**Comment by raychu86** [comment]
We have an existing Issue for this https://github.com/AleoHQ/snarkOS/issues/3171
