### ISSUE TITLE
[Feature] Need a way to NOT change REST port number when --dev parameter is specified

### ISSUE THREAD

**Issue by robwafle** [AleoHQ/snarkOS#3220]
## 🚀 Feature

Need a way to NOT change REST port number when --dev parameter is specified

## Motivation

This will allow clients to be in a load balancer similar to a production environment where the load balancer points to all 30 clients (e.g. 3 clients for each of the 10 validators). We need development testing environments to match production as closely as possible, and without this we can't have a dev environment that closely resembles production.

## Implementation

Hopefully, this is only logic to parse the parameter and one if statement wrapping a small amount of logic that actually doesn't happen in production networks.   (when --dev parameter is NOT specified )

I believe the +dev on this line is part of what would have to be made conditional:
https://github.com/AleoHQ/snarkOS/blob/mainnet-staging/cli/src/commands/start.rs#L328

**Comment by vicsn** [comment]
See for a similar or the same issue: https://github.com/AleoHQ/snarkOS/pull/3189

**Comment by raychu86** [comment]
Should be resolved with https://github.com/AleoNet/snarkOS/pull/3271
