### ISSUE TITLE
aleo.tools is not available

### ISSUE THREAD

**Issue by alexanderblv** [AleoHQ/snarkOS#3230]
![image](https://github.com/AleoHQ/snarkOS/assets/137616408/8e58d640-c65e-4c57-b10a-fc17fda0dd11)

https://aleo.tools/ unavailable for a long time. I think there's something wrong here.

**Comment by iamalwaysuncomfortable** [comment]
Thank you for bringing this our attention, this is being addressed now.

**Comment by alexanderblv** [comment]
> Thank you for bringing this our attention, this is being addressed now.

I am glad to try, please contact me if you need help!
