### ISSUE TITLE
[Bug] Give a proper error message when developer execute fails

### ISSUE THREAD

**Issue by vicsn** [AleoHQ/snarkOS#3286]
## Steps to Reproduce

1. Start a snarkOS network with network 1
2. Call snarkos developer execute with any other network (e.g. the default 0)
3. It returns an empty non-descriptive error: :warning:

## Expected Behavior

The returned error message should be clear.
Please also investigate other potential errors.

**Comment by joske** [comment]
@vicsn @raychu86 I fixed this, but I can't assign myself
