### ISSUE TITLE
[Proposal] Feature Request: support custom IP in param

### ISSUE THREAD

**Issue by lz1998** [AleoHQ/snarkOS#3338]
## 💥 Proposal

I am using a server without a public IP, and I use frpc to bind port from my server. Can I specify my public IP?

**Comment by niklaslong** [comment]
You can specify them using these options (only `--node` is important if you're not running a validator): 
https://github.com/AleoNet/snarkOS/blob/mainnet-staging/cli/src/commands/start.rs#L96-L101

As for the rest server, you can set it using `--rest`: https://github.com/AleoNet/snarkOS/blob/mainnet-staging/cli/src/commands/start.rs#L112-L114
