### ISSUE TITLE
[Docs]How to run prover with CUDA gpu, the doc says it's OPTIONAL

### ISSUE THREAD

**Issue by stark-sim** [AleoHQ/snarkOS#3411]
## 📚 Documentation

https://github.com/AleoNet/snarkOS?tab=readme-ov-file#21-requirements

I've used --help to check **run-prover.sh**, saw nothing about gpu.

**Comment by raychu86** [comment]
Relevant issue - https://github.com/AleoNet/snarkOS/issues/2708#issuecomment-2486867830
