### ISSUE TITLE
[Feature] Add --version command to built binary

### ISSUE THREAD

**Issue by dylanschultzie** [AleoHQ/snarkOS#3447]
## 🚀 Feature

Add `--version` to `snarkos` such that we can see what tag and git commit hash was used to build the binary. 

Other networks version:

near:

```
$ neard -V
neard (release 2.3.1) (build 2.3.1) (rustc 1.81.0) (protocol 72) (db 40)
features: [default, json_rpc, rosetta_rpc]
```

solana:

```
$ solana --version
solana-cli 1.18.25 (src:92ddaa20; feat:3241752014, client:Agave)
```

cosmoshub:

```
$ gaiad version
release/v21.x-7c0c4cbb7b26c48b235f60532223a74f4f68b830
```

## Motivation

This helps debug issues with builds to ensure binary is correct (doing `sha256sum snarkos`, as an example, isn't a good stand-in). It also helps automations to confirm the new build is the correct output.

## Implementation

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by mnguyen-io** [comment]
+1 please. Our automated build verification process would very much appreciate this feature.

**Comment by kim201212** [comment]
+1
I think this is a very necessary feature as we need to check the version of the built binary.

**Comment by ljedrz** [comment]
I'm on it :+1:.
