### ISSUE TITLE
[Feature] Thread and task logging

### ISSUE THREAD

**Issue by raychu86** [AleoHQ/snarkOS#376]
## 🚀 Feature

snarkOS needs additional metric logging. The node spins up many tasks/threads without much management/tracking. 

## Motivation

snarkOS currently has very limit benchmarking and logging, especially in the `network` component of the node. In order to effectively reason about the performance of the node, we need more accurate logging and analytics of the underlying operations of the node. 

## Implementation

Each task/thread can be named by a builder in the executors (i.e. tokio or async-std) and have state/progress logged to an output file. Analytics can be run externally on the log files similar to gain insight into what needs to be updated in the system.

See https://perf.rust-lang.org/ for an example metrics page.

**Comment by damons** [comment]
We've added a lot of logging improvements, but they don't go down to the thread-specific level.  

Should we close this issue out?

**Comment by ljedrz** [comment]
We're already keeping track of all our threads and tasks and close all of them when they are no longer needed; the only extra thread (other than `tokio`'s threadpool) right now (`1.3.7`) is the miner thread.
We could add task info for logging, as the logs can always be improved, but the situation is no longer limited or inaccurate.

**Comment by damons** [comment]
I'd like to see us improve our overall logging to make it more concise, meaningful, and structured; however, I believe this particular issue as described here has been resolved.  Like you said, there's always room for improvement, and I'll create new issues to track specific improvements we should make to our logging.
