### ISSUE TITLE
[Proposal] Restructure peer handling

### ISSUE THREAD

**Issue by raychu86** [AleoHQ/snarkOS#377]
## 💥 Proposal

The peer handling of the snarkOS network should be overhauled. Currently the node stores peer IPs as identifiers, whereas we could go a Kademlia-like DHT approach with NodeIDs. This could help establish a connection protocol that avoids cliques among nodes, which is dangerous to a decentralized network. 

Additionally, handshakes could be updated to further enforce versioning and validate that other nodes have the agreed upon set of parameters.

**Comment by damons** [comment]
No longer relevant in the current design.

**Comment by damons** [comment]
Not needed for stabilization effort.
