### ISSUE TITLE
[Feature] Add functionality to snarkOS toolkit 

### ISSUE THREAD

**Issue by raychu86** [AleoHQ/snarkOS#393]
## 🚀 Feature

snarkOS-toolkit needs Account View Key support, transaction generation, and message signing functionality.

## Motivation

snarkOS toolkit a currently feature limited and only supports Account generation. `toolkit` should be the how external modules and projects run Aleo related operations, such as transaction generation, message signing, and Account View Key support.

#### Account View Key
Add implementation of account view key in wasm module.

#### Transaction generation:
Migrate transaction generation logic from the `rpc` into `toolkit` and then have the `rpc` utilize the `toolkit` implementation.

#### Message signing:
Implement message signing with Account keys.

**Comment by damons** [comment]
Looks like we need to close this out and track new features in AleoHQ/aleo, right?

**Comment by ljedrz** [comment]
Transaction generation logic is still in `snarkos-rpc`, so this issue is not fully resolved yet.
