### ISSUE TITLE
[Docs] clarifications for getblockhash RPC

### ISSUE THREAD

**Issue by kellpossible** [AleoHQ/snarkOS#437]
## 📚 Documentation

https://github.com/AleoHQ/snarkOS/blob/master/rpc/documentation/public_endpoints/getblockhash.md

Mentions the `block_height` argument as being a `string`, but isn't it an integer? Perhaps also the range of valid inputs should also be specified, and what will happen when entering something invalid, or beyond the range of what is available.

Also, the argument has a name, but in the request it doesn't. Is it possible to add the name in the request? My first attempt was to try using it as a query parameter, which ends up in the query URL, but this appears to be incorrect.

**Comment by kellpossible** [comment]
Also [getblockcount](https://developer.aleo.org/autogen/testnet/public_endpoints/getblockcount), shouldn't it be returning a number? It would also be good to specify how big the numbers can be? 32 bit unsigned integer? Bigger?

**Comment by raychu86** [comment]
Good catch. The `block_height` parameter in `getblockhash` and the return value of `getblockcount` are indeed numbers (u32). We'll update the docs.

Regarding the request not needing a parameter name, I can take a look at making it optional/having functionality for both.
