### ISSUE TITLE
[Proposal] Split snarkos-rpc into several crates, or make features optional

### ISSUE THREAD

**Issue by kellpossible** [AleoHQ/snarkOS#438]
## 💥 Proposal

Someone using `snarkos-rpc` for the client portion, doesn't want to pull in all the server dependencies, and vice versa.

Also it would be nice if the `rpc_types` were in a separate crate so people who want to implement their own custom RPC client or server can still re-use them and be sure that their types are matching without needing to pull in a whole bunch of unneeded dependencies. This could be solved with features too I guess.

**Comment by ljedrz** [comment]
This is still desirable and will be pursued in the near future.

**Comment by ljedrz** [comment]
Not applicable to testnet3.
