### ISSUE TITLE
[Proposal] Make rocksdb an optional (disabled by default) dependency for snarkos-errors

### ISSUE THREAD

**Issue by kellpossible** [AleoHQ/snarkOS#452]
## 💥 Proposal

I'm using `snarkos-algorithms` crate which depends on `snarkos-errors`. It takes forever to compile because it includes `librocksdb` as a dependency. This is a very heavy dependency to pull in which isn't getting used. It should be optional.

**Comment by kellpossible** [comment]
looks like it is already an optional feature! Not sure how I missed that

**Comment by kellpossible** [comment]
It looks like https://docs.rs/crate/snarkos-algorithms/1.1.4/source/Cargo.toml.orig might be the culprit for me in this situation, it's enabling the default feature of `snarkos-errors`. Perhaps not all of the default features need to be enabled?

**Comment by kellpossible** [comment]
It would be nice if it could be disabled by default, and not so aggressively enabled by other snarkos crates. Currently I have to disable a bunch of default features in other crates, and then I'm assuming go fishing for enabling features like "snarkos-algorithms/pedersen-parallel" to enable better performance.

**Comment by kellpossible** [comment]
Somehow librocksdb has snuck its way into my dependencies again via snarkOS libraries, it's really difficult to figure out which features might be causing it and from which crate. This is a real pain point in Rust for me.

**Comment by ljedrz** [comment]
This is no longer applicable, as snarkVM (which currently houses what used to be `snarkos-algorithms`) no longer depends on `rocksdb`; `snarkos-consensus` no longer depends on `rocksdb` by default either.
