### ISSUE TITLE
[Feature] Toolkit Signatures using Account View Key and Account Address.

### ISSUE THREAD

**Issue by raychu86** [AleoHQ/snarkOS#471]
## 🚀 Feature

The current toolkit signatures currently use the `Account Private Key` to sign and `Signature Public Key` to verify Schnorr signatures. 

We need to add to functionality to sign messages with the `Account View Key` and verify the signatures with the `Account Address`. 

## Motivation

The motivation of this feature is to allow users to sign messages that can be verified with a user's public address.

## Implementation

The `Account View Key` and `Account Address` are a `Group EncrytionScheme` private and public key-pair. The `GroupEncryption` parameters share the same sized `generator_powers` field, however the `GroupEncryption` scheme is missing a salt field. 

A possible solution is to just add an additional salt field that will only be used for message signing. The `GroupEncryption` scheme will then also implement the `SignatureScheme` and call into the Schnorr signature algorithms directly. This will not require parameter generation (address derivation will remain unchanged), because we are just adding an additional 32 bytes of randomness to the end of the current `EncryptionScheme` parameters.

**Comment by ljedrz** [comment]
I think this issue needs to be transferred to `AleoHQ/aleo`, but I'm not sure if that repo is configured to obtain issue transfers from snarkOS - at least I don't have that option under `Transfer issue`.
