### ISSUE TITLE
[Refactor] Deprecate `network/src/external/message/hash.rs`

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#512]
## 🐛 Bug Report

In networking, each `MessageName` is constructed as a `HASH96` struct, which is generated by the `fixed_hash!` macro.

The problem is that no message names are ever hashed, nor should they be hashed in this architecture. In practice, hashing a message name is not a design requirement, nor is it possible on such a small target size.

## Proposed Change

We should remove `network/src/external/message/hash.rs` and replace `HASH96` in `MessageName` with a byte array or string of the message name.

**Comment by ljedrz** [comment]
For maximum network efficiency a numeric identifier that could be based just on the `enum` variant position would be the best solution; do you think that we could use a single `u8` instead of bytes or a string?

**Comment by ljedrz** [comment]
The proposed change is available at [this commit](https://github.com/AleoHQ/snarkOS/pull/550/commits/d38dc077175992b71345109bb34d8269ce3a38fb); it reduces complexity and lowers header size from 16B to 5B.

**Comment by ljedrz** [comment]
This issue can now be closed; `HASH96` was removed in https://github.com/AleoHQ/snarkOS/pull/550.

**Comment by ljedrz** [comment]
As mentioned before, this issue is no longer applicable.
