### ISSUE TITLE
[Feature] Test `Version` and `Verack` messages

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#515]
## 🚀 Feature

Add tests for checking `Version` and `Verack` messages.

#### Canonical Case
1. Spin up two test node servers.
2. Server A send a `Version` message to server B.
3. Server B receives a `Version` message from server A.
4. Server B sends a `Verack` message to server A.
5. Server A receives `Verack` message from server B.

#### Handshake Case
1. Spin up two test node servers.
2. Server A send a `Version` message to server B.
3. Server B receives a `Version` message from server A.
4. Server B sends a `Verack` and new `Version` message to server A.
5. Server A receives both `Verack` and new `Version` message from server B.
6. Server A sends a `Verack` back to server B.
7. Server B receives a `Verack` from server A.

**Comment by ljedrz** [comment]
In the refactoring branch the handshake case is already tested on both sides (initiator/responder). As for the canonical case, it doesn't seem that a `Version` message triggers a `Verack` response in the current network, and neither is it specified to do so in [the documentation](https://github.com/AleoHQ/snarkOS/blob/master/network/documentation/network_messages/verack.md); should this be changed?
