### ISSUE TITLE
[Feature] Test `Block`, `GetBlock`, and `SyncBlock` messages

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#516]
## 🚀 Feature

Add tests for checking `Block`, `GetBlock`, and `SyncBlock` messages.

### Discovered New Block

When a node server discovers a new block, they propagate the new block in a `Block` message.

#### Canonical Case

1. Spin up two test node servers.
2. Server A discovers a new block.
3. Server A sends a `Block` message to server B.
4. Server B receives `Block` message from server A.

#### Duplicate Case

1. Spin up two test node servers.
2. Server A discovers a new block.
3. Server A sends a `Block` message to server B.
4. Server B receives `Block` message from server A.
5. Server B sends back the `Block` message to server A.
6. Server A receives `Block` message from server B.
7. Server A drops the `Block` message.

### Fetch Existing Block

When a node server requests an existing block, send the existing block in a `SyncBlock` message.

#### Canonical Case

1. Spin up two test node servers.
2. Server A send a `GetBlock` message to server B.
3. Server B receives a `GetBlock` message from server A.
4. Server B sends a `SyncBlock` message to server A.
5. Server A receives `SyncBlock` message from server B.

**Comment by niklaslong** [comment]
Quick update on this: the canonical cases are being tested in the network refactor branch following the reintroduction of block sync (both initiator/responder sides + two full nodes).
