### ISSUE TITLE
[Feature] Test `GetPeers` and `Peers` messages

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#518]
## 🚀 Feature

Add tests for checking `GetPeers` and `Peers` messages.

#### Canonical Case
1. Spin up two test node servers.
2. Server A send a `GetPeers` message to server B.
3. Server B receives a `GetPeers` message from server A.
4. Server B sends a `Peers` message to server A.
5. Server A receives `Peers` message from server B.

**Comment by ljedrz** [comment]
https://github.com/AleoHQ/snarkOS/pull/594 furthers the goal of being able to quickly set up multiple test nodes, which is desirable for this test case.
