### ISSUE TITLE
[Feature] Test `GetSync`, `Sync`, `GetBlock`, and `SyncBlock` messages

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#519]
## 🚀 Feature

Add tests for checking `GetSync`, `Sync`, `GetBlock`, and `SyncBlock` messages.

#### Canonical Case

When a node server attempts to sync its blocks with another node server, it uses a sync protocol to request blocks.

1. Spin up two test node servers.
2. Server A send a `GetSync` message to server B.
3. Server B receives a `GetSync` message from server A.
4. Server B sends a `Sync` message to server A.
5. Server A receives `Sync` message from server B.
6. Server A send a `GetBlock` message to server B.
7. Server B receives a `GetBlock` message from server A.
8. Server B sends a `SyncBlock` message to server A.
9. Server A receives `SyncBlock` message from server B.

**Comment by niklaslong** [comment]
Quick update: this is tested in the network refactor branch.
