### ISSUE TITLE
[Bug] v1.3.2 not working on windows 

### ISSUE THREAD

**Issue by rgolovat** [AleoHQ/snarkOS#704]
## 🐛 Bug Report

v1.3.2 not working on windows
![snarkos 1 3 2](https://user-images.githubusercontent.com/7772784/115858297-6df71d00-a437-11eb-9624-7156a205dac4.png)

(Write your description here)

## Steps to Reproduce

1. Pull last code 
2. Build 
3. run snarkos 

## Expected Behavior

Start of the node

(Write what you expected to happen here)

## Your Environment
Windows 2016 server

**Comment by ljedrz** [comment]
How was `snarkOS` built? Was it in release mode (`cargo build --release`)? It might fail to run in the `cargo`-default debug mode.

**Comment by rgolovat** [comment]
> How was `snarkOS` built? Was it in release mode (`cargo build --release`)? It might fail to run in the `cargo`-default debug mode.

rebuild resolved an issue thanks.

Can you please also advise. Explorer shows only 3 only nodes. Is that possible that I'm not connected to the correct host with my node and miner?

**Comment by ljedrz** [comment]
The nodes are pre-configured to connect to the default Aleo bootstrappers, and those should provide the node with addresses of further peers. We are currently working on fine-tuning the bootstrapper nodes so that the right shape of the network is formed.
