### ISSUE TITLE
Docker image build failed

### ISSUE THREAD

**Issue by Avadon** [AleoHQ/snarkOS#706]
## 🐛 Bug Report

Docker image build failed with an error: "error[E0658]: `match` is not allowed in a `const fn`".

Full log:

<details>
  <summary>Click to expand!</summary>
  
Step 1/6 : FROM rust:1.45
 ---> 53f7516d0379
Step 2/6 : RUN apt-get update  && apt-get install -y    build-essential    clang    gcc    libssl-dev    make    pkg-config    xz-utils
 ---> Using cache
 ---> 140bd414b1f5
Step 3/6 : WORKDIR /usr/src/snarkOS
 ---> Using cache
 ---> 20dcbe8fbf67
Step 4/6 : COPY . .
 ---> Using cache
 ---> 984e2a933f6e
Step 5/6 : RUN cargo build --release
 ---> Running in 2bee4195f0e3
    Updating crates.io index
 Downloading crates ...
  Downloaded ansi_term v0.12.1
  Downloaded futures-sink v0.3.14
  Downloaded hyper v0.14.5
  Downloaded number_prefix v0.3.0
  Downloaded jsonrpc-client-transports v17.0.0
  Downloaded hyper v0.13.10
  Downloaded multipart v0.17.1
  Downloaded cfg-if v0.1.10
  Downloaded safemem v0.3.3
  Downloaded blake2 v0.9.1
  Downloaded mio v0.7.11
  Downloaded foreign-types v0.3.2
  Downloaded flate2 v1.0.20
  Downloaded dirs-sys v0.3.5
  Downloaded futures-io v0.3.14
  Downloaded futures-task v0.3.14
  Downloaded getrandom v0.1.16
  Downloaded futures v0.1.31
  Downloaded h2 v0.3.2
  Downloaded httparse v1.4.0
  Downloaded hex v0.4.3
  Downloaded http-body v0.4.1
  Downloaded http-body v0.3.1
  Downloaded h2 v0.2.7
  Downloaded lazycell v1.3.0
  Downloaded indexmap v1.6.2
  Downloaded dirs v3.0.1
  Downloaded derive_more v0.99.13
  Downloaded crypto-mac v0.8.0
  Downloaded net2 v0.2.37
  Downloaded cc v1.0.67
  Downloaded capnp v0.14.1
  Downloaded openssl-probe v0.1.2
  Downloaded openssl v0.10.33
  Downloaded proc-macro-error v1.0.4
  Downloaded proc-macro2 v1.0.26
  Downloaded prometheus v0.12.0
  Downloaded pin-project-lite v0.1.12
  Downloaded proc-macro-crate v0.1.5
  Downloaded pin-project-lite v0.2.6
  Downloaded regex v1.4.5
  Downloaded semver v0.9.0
  Downloaded self_update v0.26.0
  Downloaded anyhow v1.0.40
  Downloaded procfs v0.9.1
  Downloaded bincode v1.3.3
  Downloaded base58 v0.1.0
  Downloaded ansi_term v0.11.0
  Downloaded bindgen v0.57.0
  Downloaded byteorder v1.4.3
  Downloaded bzip2 v0.3.3
  Downloaded bech32 v0.6.0
  Downloaded aead v0.3.2
  Downloaded rustc_version v0.2.3
  Downloaded regex-automata v0.1.9
  Downloaded capnpc v0.14.3
  Downloaded colored v2.0.0
  Downloaded buf_redux v0.8.4
  Downloaded pin-project-internal v1.0.7
  Downloaded peeking_take_while v0.1.2
  Downloaded parking_lot v0.11.1
  Downloaded openssl-sys v0.9.61
  Downloaded console v0.14.1
  Downloaded chacha20 v0.5.0
  Downloaded crc32fast v1.2.1
  Downloaded crossbeam-channel v0.5.1
  Downloaded crossbeam-epoch v0.9.3
  Downloaded clap v2.33.3
  Downloaded derivative v2.2.0
  Downloaded curl v0.4.36
  Downloaded foreign-types-shared v0.1.1
  Downloaded fxhash v0.2.1
  Downloaded futures-macro v0.3.14
  Downloaded indicatif v0.15.0
  Downloaded form_urlencoded v1.0.1
  Downloaded num-integer v0.1.44
  Downloaded semver v0.11.0
  Downloaded block-buffer v0.9.0
  Downloaded memchr v2.3.4
  Downloaded parking_lot_core v0.8.3
  Downloaded rand_core v0.5.1
  Downloaded once_cell v1.7.2
  Downloaded bitflags v1.2.1
  Downloaded autocfg v1.0.1
  Downloaded rayon v1.5.0
  Downloaded bytes v1.0.1
  Downloaded cexpr v0.4.0
  Downloaded futures v0.3.14
  Downloaded bumpalo v3.6.1
  Downloaded matchers v0.0.1
  Downloaded jsonrpc-core v17.0.0
  Downloaded idna v0.2.3
  Downloaded input_buffer v0.4.0
  Downloaded idna v0.1.5
  Downloaded block-cipher v0.8.0
  Downloaded jobserver v0.1.21
  Downloaded percent-encoding v2.1.0
  Downloaded pest v2.1.3
  Downloaded remove_dir_all v0.5.3
  Downloaded quote v1.0.9
  Downloaded rand v0.8.3
  Downloaded ryu v1.0.5
  Downloaded fnv v1.0.7
  Downloaded digest v0.9.0
  Downloaded base64 v0.13.0
  Downloaded getrandom v0.2.2
  Downloaded glob v0.3.0
  Downloaded chrono v0.4.19
  Downloaded atty v0.2.14
  Downloaded adler v1.0.2
  Downloaded proc-macro-nested v0.1.7
  Downloaded proc-macro-hack v0.5.19
  Downloaded libloading v0.7.0
  Downloaded rustc-hash v1.1.0
  Downloaded serde_derive v1.0.125
  Downloaded globset v0.4.6
  Downloaded convert_case v0.4.0
  Downloaded num_cpus v1.13.0
  Downloaded http v0.2.4
  Downloaded hashbrown v0.9.1
  Downloaded itertools v0.10.0
  Downloaded quick-error v1.2.3
  Downloaded miniz_oxide v0.4.4
  Downloaded rocksdb v0.16.0
  Downloaded lazy_static v1.4.0
  Downloaded headers v0.3.4
  Downloaded matches v0.1.8
  Downloaded itoa v0.4.7
  Downloaded generic-array v0.14.4
  Downloaded instant v0.1.9
  Downloaded jsonrpc-core-client v17.0.0
  Downloaded ipnet v2.3.0
  Downloaded futures-core v0.3.14
  Downloaded num-traits v0.2.14
  Downloaded jsonrpc-derive v17.0.0
  Downloaded jsonrpc-http-server v17.0.0
  Downloaded aho-corasick v0.7.15
  Downloaded serde_json v1.0.64
  Downloaded httpdate v0.3.2
  Downloaded headers-core v0.2.0
  Downloaded log v0.4.14
  Downloaded mime v0.3.16
  Downloaded libc v0.2.93
  Downloaded memoffset v0.6.3
  Downloaded jsonrpc-server-utils v17.0.0
  Downloaded serde_urlencoded v0.7.0
  Downloaded mio v0.6.23
  Downloaded lock_api v0.4.3
  Downloaded bstr v0.2.15
  Downloaded cpuid-bool v0.1.2
  Downloaded cpuid-bool v0.2.0
  Downloaded crossbeam-deque v0.8.0
  Downloaded bytes v0.5.6
  Downloaded pin-utils v0.1.0
  Downloaded jsonrpc-pubsub v17.0.0
  Downloaded futures-util v0.3.14
  Downloaded sharded-slab v0.1.1
  Downloaded futures-channel v0.3.14
  Downloaded snarkvm-objects v0.2.2
  Downloaded snarkvm-dpc v0.2.2
  Downloaded snarkvm-r1cs v0.2.2
  Downloaded slab v0.4.2
  Downloaded shlex v0.1.1
  Downloaded curve25519-dalek v3.1.0
  Downloaded stream-cipher v0.7.1
  Downloaded terminal_size v0.1.16
  Downloaded subtle v2.4.0
  Downloaded socket2 v0.3.19
  Downloaded snarkvm-profiler v0.2.2
  Downloaded cfg-if v1.0.0
  Downloaded native-tls v0.2.7
  Downloaded socket2 v0.4.0
  Downloaded snarkvm-marlin v0.2.2
  Downloaded nom v5.1.2
  Downloaded crossbeam-utils v0.8.3
  Downloaded clang-sys v1.2.0
  Downloaded chacha20poly1305 v0.6.0
  Downloaded textwrap v0.11.0
  Downloaded tinyvec v1.2.0
  Downloaded percent-encoding v1.0.1
  Downloaded proc-macro-error-attr v1.0.4
  Downloaded time v0.1.43
  Downloaded ppv-lite86 v0.2.10
  Downloaded hyper-tls v0.5.0
  Downloaded either v1.6.1
  Downloaded sha2 v0.9.3
  Downloaded strsim v0.8.0
  Downloaded bzip2-sys v0.1.10+1.0.8
  Downloaded tokio-native-tls v0.3.0
  Downloaded tokio-stream v0.1.5
  Downloaded tower-service v0.3.1
  Downloaded tokio-util v0.6.6
  Downloaded toml v0.5.8
  Downloaded poly1305 v0.6.2
  Downloaded quick-xml v0.20.0
  Downloaded rand v0.7.3
  Downloaded rayon-core v1.9.0
  Downloaded rustc_version v0.3.3
  Downloaded tracing-futures v0.2.5
  Downloaded tracing-serde v0.1.2
  Downloaded tracing v0.1.25
  Downloaded rand_chacha v0.2.2
  Downloaded tracing-subscriber v0.2.17
  Downloaded unicode-normalization v0.1.17
  Downloaded universal-hash v0.4.0
  Downloaded vec_map v0.8.2
  Downloaded unicase v2.6.0
  Downloaded twoway v0.1.8
  Downloaded futures-executor v0.3.14
  Downloaded tungstenite v0.12.0
  Downloaded warp v0.3.1
  Downloaded unicode-xid v0.2.1
  Downloaded version_check v0.9.3
  Downloaded ucd-trie v0.1.3
  Downloaded wasm-bindgen-macro v0.2.73
  Downloaded wasm-bindgen-backend v0.2.73
  Downloaded want v0.3.0
  Downloaded serde v1.0.125
  Downloaded wasm-bindgen v0.2.73
  Downloaded x25519-dalek v1.1.1
  Downloaded zeroize_derive v1.0.1
  Downloaded iovec v0.1.4
  Downloaded wasm-bindgen-shared v0.2.73
  Downloaded wasm-bindgen-macro-support v0.2.73
  Downloaded semver-parser v0.10.2
  Downloaded semver-parser v0.7.0
  Downloaded scopeguard v1.1.0
  Downloaded scoped-tls v1.0.0
  Downloaded rand_core v0.6.2
  Downloaded try-lock v0.2.3
  Downloaded utf-8 v0.7.6
  Downloaded typenum v1.13.0
  Downloaded tracing-log v0.1.2
  Downloaded reqwest v0.11.3
  Downloaded rand_xorshift v0.3.0
  Downloaded snarkvm-fields v0.2.2
  Downloaded snarkvm-derives v0.2.2
  Downloaded mime_guess v2.0.3
  Downloaded protobuf v2.22.1
  Downloaded thread_local v1.1.3
  Downloaded rand_chacha v0.3.0
  Downloaded zeroize v1.2.0
  Downloaded snarkvm-curves v0.2.2
  Downloaded smallvec v1.6.1
  Downloaded sha-1 v0.9.4
  Downloaded opaque-debug v0.3.0
  Downloaded pin-project v1.0.7
  Downloaded tokio v0.2.25
  Downloaded snarkvm-posw v0.2.2
  Downloaded snarkvm-polycommit v0.2.2
  Downloaded tempfile v3.2.0
  Downloaded snarkvm-utilities v0.2.2
  Downloaded tinyvec_macros v0.1.0
  Downloaded tokio v1.5.0
  Downloaded thiserror-impl v1.0.24
  Downloaded thiserror v1.0.24
  Downloaded syn v1.0.69
  Downloaded zip v0.5.12
  Downloaded unicode-bidi v0.3.5
  Downloaded tokio-macros v1.1.0
  Downloaded unicode-width v0.1.8
  Downloaded url v2.2.1
  Downloaded snarkvm-algorithms v0.2.2
  Downloaded tracing-core v0.1.17
  Downloaded pkg-config v0.3.19
  Downloaded tokio-util v0.3.1
  Downloaded tokio-tungstenite v0.13.0
  Downloaded synstructure v0.12.4
  Downloaded snarkvm-gadgets v0.2.2
  Downloaded url v1.7.2
  Downloaded regex-syntax v0.6.23
  Downloaded snow v0.7.2
  Downloaded libz-sys v1.1.2
  Downloaded encoding_rs v0.8.28
  Downloaded sodiumoxide v0.2.6
  Downloaded curl-sys v0.4.42+curl-7.76.0
  Downloaded libsodium-sys v0.2.6
  Downloaded snarkvm-parameters v0.2.2
  Downloaded librocksdb-sys v6.17.3
   Compiling libc v0.2.93
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.26
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.69
   Compiling autocfg v1.0.1
   Compiling version_check v0.9.3
   Compiling lazy_static v1.4.0
   Compiling memchr v2.3.4
   Compiling serde_derive v1.0.125
   Compiling log v0.4.14
   Compiling serde v1.0.125
   Compiling pkg-config v0.3.19
   Compiling typenum v1.13.0
   Compiling scopeguard v1.1.0
   Compiling smallvec v1.6.1
   Compiling ppv-lite86 v0.2.10
   Compiling getrandom v0.2.2
   Compiling byteorder v1.4.3
   Compiling pin-project-lite v0.2.6
   Compiling itoa v0.4.7
   Compiling hashbrown v0.9.1
   Compiling futures-core v0.3.14
   Compiling proc-macro-hack v0.5.19
   Compiling slab v0.4.2
   Compiling bytes v1.0.1
   Compiling fnv v1.0.7
   Compiling futures-sink v0.3.14
   Compiling proc-macro-nested v0.1.7
   Compiling opaque-debug v0.3.0
   Compiling bitflags v1.2.1
   Compiling subtle v2.4.0
   Compiling cpuid-bool v0.1.2
   Compiling pin-utils v0.1.0
   Compiling futures-task v0.3.14
   Compiling futures-io v0.3.14
   Compiling futures v0.1.31
   Compiling ryu v1.0.5
   Compiling regex-syntax v0.6.23
   Compiling rayon-core v1.9.0
   Compiling either v1.6.1
   Compiling matches v0.1.8
   Compiling serde_json v1.0.64
   Compiling tinyvec_macros v0.1.0
   Compiling openssl-probe v0.1.2
   Compiling getrandom v0.1.16
   Compiling once_cell v1.7.2
   Compiling httparse v1.4.0
   Compiling snarkvm-profiler v0.2.2
   Compiling ucd-trie v0.1.3
   Compiling hex v0.4.3
   Compiling glob v0.3.0
   Compiling curl v0.4.36
   Compiling percent-encoding v2.1.0
   Compiling try-lock v0.2.3
   Compiling tower-service v0.3.1
   Compiling crc32fast v1.2.1
   Compiling httpdate v0.3.2
   Compiling anyhow v1.0.40
   Compiling bindgen v0.57.0
   Compiling cfg-if v0.1.10
   Compiling base64 v0.13.0
   Compiling adler v1.0.2
   Compiling mime v0.3.16
   Compiling peeking_take_while v0.1.2
   Compiling rustc-hash v1.1.0
   Compiling lazycell v1.3.0
   Compiling shlex v0.1.1
   Compiling bytes v0.5.6
   Compiling wasm-bindgen-shared v0.2.73
   Compiling foreign-types-shared v0.1.1
   Compiling openssl v0.10.33
   Compiling semver-parser v0.7.0
   Compiling remove_dir_all v0.5.3
   Compiling pin-project-lite v0.1.12
   Compiling protobuf v2.22.1
   Compiling base58 v0.1.0
   Compiling utf-8 v0.7.6
   Compiling bech32 v0.6.0
   Compiling safemem v0.3.3
   Compiling bumpalo v3.6.1
   Compiling native-tls v0.2.7
   Compiling cpuid-bool v0.2.0
   Compiling prometheus v0.12.0
   Compiling unicode-width v0.1.8
   Compiling quick-error v1.2.3
   Compiling scoped-tls v1.0.0
   Compiling convert_case v0.4.0
   Compiling percent-encoding v1.0.1
   Compiling encoding_rs v0.8.28
   Compiling wasm-bindgen v0.2.73
   Compiling snarkos-profiler v1.3.1 (/usr/src/snarkOS/profiler)
   Compiling capnp v0.14.1
   Compiling number_prefix v0.3.0
   Compiling ipnet v2.3.0
   Compiling self_update v0.26.0
   Compiling vec_map v0.8.2
   Compiling ansi_term v0.11.0
   Compiling strsim v0.8.0
   Compiling ansi_term v0.12.1
   Compiling instant v0.1.9
   Compiling libloading v0.7.0
   Compiling lock_api v0.4.3
   Compiling tracing-core v0.1.17
   Compiling sharded-slab v0.1.1
   Compiling futures-channel v0.3.14
   Compiling unicode-bidi v0.3.5
   Compiling tinyvec v1.2.0
   Compiling itertools v0.10.0
   Compiling fxhash v0.2.1
   Compiling pest v2.1.3
   Compiling thread_local v1.1.3
   Compiling http v0.2.4
   Compiling input_buffer v0.4.0
   Compiling form_urlencoded v1.0.1
   Compiling foreign-types v0.3.2
   Compiling semver v0.9.0
   Compiling textwrap v0.11.0
   Compiling generic-array v0.14.4
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling nom v5.1.2
   Compiling unicase v2.6.0
   Compiling rustc_version v0.2.3
   Compiling tracing v0.1.25
   Compiling want v0.3.0
   Compiling tracing-log v0.1.2
   Compiling capnpc v0.14.3
   Compiling aho-corasick v0.7.15
   Compiling twoway v0.1.8
   Compiling buf_redux v0.8.4
   Compiling bstr v0.2.15
   Compiling quick-xml v0.20.0
   Compiling indexmap v1.6.2
   Compiling crossbeam-utils v0.8.3
   Compiling memoffset v0.6.3
   Compiling rayon v1.5.0
   Compiling tokio v1.5.0
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling miniz_oxide v0.4.4
   Compiling clang-sys v1.2.0
   Compiling regex-automata v0.1.9
   Compiling quote v1.0.9
   Compiling unicode-normalization v0.1.17
   Compiling semver-parser v0.10.2
   Compiling jobserver v0.1.21
   Compiling num_cpus v1.13.0
   Compiling parking_lot_core v0.8.3
   Compiling socket2 v0.4.0
   Compiling time v0.1.43
   Compiling mio v0.7.11
   Compiling net2 v0.2.37
error[E0658]: `match` is not allowed in a `const fn`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/socket2-0.4.0/src/lib.rs:156:9
    |
156 | /         match address {
157 | |             SocketAddr::V4(_) => Domain::IPV4,
158 | |             SocketAddr::V6(_) => Domain::IPV6,
159 | |         }
    | |_________^
    |
    = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information

   Compiling iovec v0.1.4
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `socket2`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

</details>

## Steps to Reproduce

Try to run "docker-compose run app" with docker-compose.yml provided by default.

## Expected Behavior

Docker image builds successfully

## Your Environment

- snarkOS Version: 1.3.1
- Rust version: 1.45
- Debian 10
- CPU: 2x Intel Xeon E5-2650

**Comment by Avadon** [comment]
It seems like updating to rust 1.51.0 solves the issue (at least image builds correctly and container starts).

**Comment by ljedrz** [comment]
Indeed, `match` in `const fn` contexts [was enabled in Rust 1.46](https://github.com/rust-lang/rust/blob/relnotes-1.52.0/RELEASES.md#language-6).

**Comment by Avadon** [comment]
Docker image with 1.51.0 seems to work stable. Added pr - https://github.com/AleoHQ/snarkOS/pull/709
