### ISSUE TITLE
[Bug] Bootnodes appear down

### ISSUE THREAD

**Issue by e-gons** [AleoHQ/snarkOS#711]
## 🐛 Bug Report

Several miners in the Discord #snarkos channel are having issues syncing to the blockchain. Syncing is difficult to achieve and happens sporadically. Changing IP addresses appears to help for short periods of time. Details below.

## Steps to Reproduce

1. Install snarkos from source code
2. Instantiate miner using `snarkos --is-miner <aleo address> --connect <list of IP addresses>`. The list of IP addresses can be found here for [miner](https://api.nodes.guru/aleo.sh) and[ node](https://api.nodes.guru/aleo_node.sh).
3. Check status using `curl -s --data-binary '{"jsonrpc": "2.0", "id":"documentation", "method": "getnodeinfo", "params": [] }' -H 'content-type: application/json' http://$1:3030/ | jq '.result?'`

## Expected Behavior

Expected to see "is_minder" and "is_syncing" return `true`. Instead "is_syncing" returns false while "is_miner" returns true. Block height is at 10k after 48 hours of running.

## Your Environment

- snarkos  1.3.2
- rust 1.5.1
- macOS Big Sur 11.4

The same issue occurs on a different, more powerful machine whose block height is 22k after 48 hours:
- snarkos 1.3.2
- rust 1.5.1
- debian 10 (buster)

**Comment by ljedrz** [comment]
Block sync is currently done in batches (so it can be done against multiple "providers", as opposed to just one), and the node changes its status to `Syncing` only when it is currently processing a batch of sync blocks. As for the bootnodes, we're working on ironing out some corner cases where they could get stuck (e.g. https://github.com/AleoHQ/snarkOS/pull/713).

**Comment by howardwu** [comment]
#715
