### ISSUE TITLE
[Bug] Underflow bug in `remaining_sync_blocks` counter

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#716]
## 🐛 Bug Report

![Screen Shot 2021-04-27 at 12 45 43 AM](https://user-images.githubusercontent.com/9260812/116204809-f7d20f00-a6f1-11eb-9c0d-eabeb62bbfa3.png)

**Comment by ljedrz** [comment]
Fixed by https://github.com/AleoHQ/snarkOS/pull/715.
