### ISSUE TITLE
[Bug] Too many open files error

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#726]
## 🐛 Bug Report

Too many open files error, see screenshot:
![Screen Shot 2021-05-02 at 1 05 49 PM](https://user-images.githubusercontent.com/9260812/116826100-367b2580-ab47-11eb-9eac-1f4de70f5168.png)

## Steps to Reproduce

1. Start up snarkOS as a standard client node: `cargo run --release`
2. Wait a few hours for the error to appear

## Your Environment

- snarkOS 1.3.3
- Rust 1.51
- macOS

**Comment by damons** [comment]
No longer needed for Stabilize Testnet1 per conversation.
