### ISSUE TITLE
Network Physical and Topological Architecture for devnet

### ISSUE THREAD

**Issue by damons** [AleoHQ/snarkOS#751]
Purposes of devnet:
* Run latest tested commits from developer feature/fix branches 
* Does not affect testnet
* Is allowed to be less stable than testnet
* Provides a testing ground for isolating miner, bootstrap, and RPC nodes
* Provides metrics for network/P2P behaviors in advance

To do this, we need to spec out the following:
* The physical machine requirements to run each node profile (i.e., miner, bootstrap, and RPC)
* The addresses of individual nodes
* Routes
* TCP/IP filtering and firewall details
* Services available on each machine (i.e., ssh, RPC, Protocol, Monitors, Log Servers)

**Comment by damons** [comment]
The deliverable for this issue is a markdown document containing the details requested in the description.

**Comment by ljedrz** [comment]
Should we close this issue now that there's a devnet or are there still some features that need to be implemented? We might want to have a checklist if that's the case.

**Comment by damons** [comment]
We need to document devnet and our standard network architecture.  Assigning to Fabiano.

**Comment by ljedrz** [comment]
@zosorock should we keep this issue open?
