### ISSUE TITLE
Log Management for devnet

### ISSUE THREAD

**Issue by damons** [AleoHQ/snarkOS#752]
Currently, Aleo nodes are being run on disparate cloud servers in multiple regions with different levels of access and control.  Developers who are implementing P2P block synchronization, consensus, etc., are often isolated from nodes running under different profiles, and when there are problems or bugs, it is helpful for Aleo engineers to have access to the logs.

Logs can grow in size and quickly become unmanageable. Also, controlling who has access to the logs is important.  For devnet we need to utilize the logging infrastructure options that are available in the cloud which enable consolidation, access control, rotation, storage and archiving, and searching.

This public issue is the space for us to make recommendations to others who want to run snarkOS nodes and manage their logs.  We will mirror and implement the processes documented here internally on our devnet infrastructure.

**Comment by ljedrz** [comment]
@zosorock do we already have this feature? I don't need it right now, just cleaning up open issues.

**Comment by ljedrz** [comment]
Closing the issue due to inactivity. I also know that we have some log management setup in place.
