### ISSUE TITLE
[Bug] Couldn't connect to bootnode 

### ISSUE THREAD

**Issue by wang5561207** [AleoHQ/snarkOS#770]
ay 19 23:02:18.504  WARN Couldn't connect to bootnode 138.197.232.178:4131: Io(Custom { kind: UnexpectedEof, error: "early eof" })
May 19 23:02:18.542  WARN Couldn't connect to bootnode 64.225.91.42:4131: Io(Custom { kind: UnexpectedEof, error: "early eof" })
May 19 23:02:18.544  WARN Couldn't connect to bootnode 64.225.91.43:4131: Io(Custom { kind: UnexpectedEof, error: "early eof" })

**Comment by ljedrz** [comment]
Please update your node to `1.3.4` and retry.

**Comment by wang5561207** [comment]
Thank you very much! It's wroking!

**Comment by wang5561207** [comment]
Thank you very much! It's wroking!

**Comment by wang5561207** [comment]
Thank you very much! It's wroking!
