### ISSUE TITLE
[Bug] Unable to get block locator hashes from storage

### ISSUE THREAD

**Issue by ljedrz** [AleoHQ/snarkOS#780]
## 🐛 Bug Report

The node might report the following error:
```
ERROR: Unable to get block locator hashes from storage
```
Which makes it unable to perform a block sync with its peers.

**Comment by raychu86** [comment]
Likely an issue with the line `block_locator_hashes.push(self.get_block_hash(index)?);` in the `get_block_locator_hashes` method. Somehow the entry in the `COL_BLOCK_LOCATOR` for the given block number is missing.

**Comment by damons** [comment]
My miner has hit this.

**Comment by ljedrz** [comment]
>Somehow the entry in the COL_BLOCK_LOCATOR for the given block number is missing.
Yes, because the `Ledger::decommit_latest_block` method currently doesn't update the `KEY_BEST_BLOCK_NUMBER` value.

**Comment by ljedrz** [comment]
`KEY_BEST_BLOCK_NUMBER` is not typically used to obtain the block height, but it's used to set it up during node's startup.

**Comment by ljedrz** [comment]
This issue doesn't appear to occur anymore; after encountering many forks and having done thorough testing around it, I think it can safely be closed.
