### ISSUE TITLE
[Bug] A node might receive pre-existing blocks when attempting to sync

### ISSUE THREAD

**Issue by ljedrz** [AleoHQ/snarkOS#783]
This can keep happening in a loop, making a node unable to catch up with the chain.

**Comment by ljedrz** [comment]
It appears that this issue happens when a node is on a fork and hasn't detected it yet; the node encounters greater chain lengths and asks for sync blocks, sending its locator hashes; however, these hashes are unknown to the recipient of the request, and so it only provides very old blocks right after the genesis block.

**Comment by Protryon** [comment]
I've encountered that it's commonly caused not by my node being on a fork, but by peer count dropping (usually due to peer attrition from ping spikes and accumulated failures = permaban), and then I think, resulting in the node being connected to a fork.

**Comment by ljedrz** [comment]
But essentially the root cause is also that a node is attempting to sync with a fork and the sync request results in returning the very initial blocks, resulting in logs reporting duplicates? Or should it be registered as an additional issue?

**Comment by ljedrz** [comment]
https://github.com/AleoHQ/snarkOS/pull/809 makes us not ask for duplicates anymore and I haven't noticed `0..64` batches when testing it, but it doesn't solve the entire issue yet, as duplicate hashes can still be proposed by peers.

**Comment by ljedrz** [comment]
Update: the `lockless` branch added known hash filtering, so #809 just improves the granularity of intervals between requested block hashes now.

**Comment by ljedrz** [comment]
This is fixed now; https://github.com/AleoHQ/snarkOS/issues/870 is related, but it's a separate issue.
