### ISSUE TITLE
[Bug] Local address incorrect

### ISSUE THREAD

**Issue by howardwu** [AleoHQ/snarkOS#788]
## 🐛 Bug Report

@ljedrz has mentioned the following:
> note: some of these bootnodes seem to be disconnecting from my node pretty often with an EOF, which suggests that they might be registered under 2 (or more) network interfaces; I checked them with the getnodeinfo RPC and noticed that their listening_addr has the 0.0.0.0 IP, which could be causing this - in order to avoid it, all the bootnodes should be launched with a specified --ip X parameter, where X is not 0.0.0.0, but the corresponding bootnode address in the TESTNET_BOOTNODES list.

We should investigate whether the local address is being improperly set for each node. We should have self-discovery mechanisms already in the networking stack.

**Comment by Protryon** [comment]
Oh, the EOF I think is from when 3 failures have accumulated, and the IP is basically banned. Every 15 seconds, the node will go through and disconnect it forcefully, which results in an EOF failure on the other side. I'll open a PR in a bit that adds the local logic I used in my little test fork, which invalidates failures after 15 minutes.
