### ISSUE TITLE
[Feature] Expire failure counts

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#799]
Right now, we track failure counts for a peer until our node is restarted. This results in an effective perma-ban for any spotty-networked-nodes. We should add a 15 minute expiry time to a given failure, or similar.

We should also not count failures for simple disconnections, timeouts, and tiny-part/partial sync failures.

**Comment by ljedrz** [comment]
Indeed; initially, the disconnected peers would go to storage, but now that they are kept in memory, the failure counter needs to be reset upon a disconnect or a connection.

**Comment by Protryon** [comment]
If we reset on connections it becomes moot, so I think a expiry timer instead is a good move @ljedrz

**Comment by ljedrz** [comment]
Fair, not all the nodes would immediately receive another connection in the meantime and since connections are created quickly, it could be abused :+1:.

**Comment by ljedrz** [comment]
This functionality is already in place.
