### ISSUE TITLE
Storage operations can block async worker threads

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#801]
At the moment, we disconnect any peer on the judgement cycle that runs every 15 seconds, if the peers last measured RTT (round trip time) is greater than 1500 ms.

Some latencies are measured between 4000 and 10000 seconds as a result, even over localhost <-> localhost peer connections.

I speculated that the cause is sync IO blocking tokio worker threads when calling RocksDB. RocksDB does offlay IO to worker threads, but I think for durability, it blocks the caller, and reads still need to wait for data return anyways.

I've prototyped a `std::thread` actor for RocksDB calls that seems to significantly reduce, but not fully resolve the problem. I suspect that the high-cpu operations during syncing also blocks tokio workers, even when storage is out-of-line, further investigation required. Also, peers having the same issue make this hard to test on testnet, as this issue reciprocates.

**Comment by ljedrz** [comment]
> high-cpu operations during syncing also blocks tokio workers

Yes, and I think we need to identify them and delegate them to blocking threads (via `task::spawn_blocking`) so that they don't stop the executor.

**Comment by Protryon** [comment]
> > high-cpu operations during syncing also blocks tokio workers
> 
> Yes, and I think we need to identify them and delegate them to blocking-friendly threads (via `task::spawn_blocking`) so that they don't stop the executor.

FYI, in my current local tests, my `std::thread` actor has not had any latency spikes above 40ms, versus before it was several thousand.

**Comment by Protryon** [comment]
Yeah, I get it a worse in my `fastsync` branch, it piles the load and also just syncs faster, but I also see it in existing nodes.

**Comment by ljedrz** [comment]
Changed the description, as high pings no longer cause disconnects at this moment.

**Comment by ljedrz** [comment]
Closing for the aforementioned reason.
