### ISSUE TITLE
[Feature] Don't provide unroutable addresses in peer lists

### ISSUE THREAD

**Issue by ljedrz** [AleoHQ/snarkOS#817]
The current peer-sharing mechanism only checks that we don't provide a peer with its own address among the addresses we're connected to; we can do better than this, though, including:
- excluding bootnodes (peers are generally going to know the same ones)
- excluding addresses that connected to us (as opposed to us being the initiator; potentially unroutable)
- filtering for addresses that we would verify to be routable

This could be related to https://github.com/AleoHQ/snarkOS/issues/802, as the network crawler would know a lot of peers and be able to produce great peer lists.

**Comment by niklaslong** [comment]
Closed by #927.
