### ISSUE TITLE
[Feature] Improve the availability of bootnodes

### ISSUE THREAD

**Issue by ljedrz** [AleoHQ/snarkOS#818]
Due to all the nodes maintaining persistent connections, the default list of bootnodes that all the nodes attempt to connect to at first can quickly exhaust their connection limits, regardless of how generous they are. There are several ways in which we can improve this situation:
- making the bootnodes "thin" and their connections short-lived, i.e. removing their sync capabilities and instead making them laser-focused on just providing lists of peers; that would make them capable of handling huge numbers of connections, making us able to have fewer bootnodes in total; such bootnodes could also serve as network crawlers (see https://github.com/AleoHQ/snarkOS/issues/802) and actively improve the "shape" of the network by providing "smart" peer lists
- making the connections of bootnodes short-lived (though not as short as in the first point), e.g. disconnecting from peers after e.g. 5 minutes; that time should allow the new peers to learn about other potential peers and possibly form long-lived connections with them instead of the bootnodes
- reduce the number of bootnodes that the nodes attempt to connect to in a single attempt; this could make the initial wait time a bit longer, but would be likely to reduce the strain on all the bootnodes by giving nodes the chance to learn about other peers and connect to them instead of all the bootnodes; this would work best if paired with https://github.com/AleoHQ/snarkOS/issues/817

**Comment by niklaslong** [comment]
Closed by #878.
