### ISSUE TITLE
[Proposal] Remove snow, use TLS or don't encrypt at all

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#819]
## 💥 Proposal

At the moment, we use `snow`, which depends on `libsodium`, a C++ dependency. Frankly, I'm not sure we need encryption at all:
* we don't authenticate identity, so MITM is still trivial even with `snow`
* we don't trust peers anyways
* no sensitive data goes over the network because we don't trust

If we *really* want encryption, lets use mutually-unauthenticated-TLS. Ditto, kind of pointless though.

**Comment by ljedrz** [comment]
Closing, as it's no longer applicable to testnet2.
