### ISSUE TITLE
Identify Orphan Rate

### ISSUE THREAD

**Issue by damons** [AleoHQ/snarkOS#826]
## 💥 Epic:  Orphan Rate Metrics

In order to debug and tune our consensus system, we need to add to snarkOS a metric which identifies the rate at which orphan chains are created.  Let's add any issues here required to specify, analyze, and optimize snarkOS' orphan rate.

**Comment by unordered-set** [comment]
Looks like it can be closed? https://github.com/AleoHQ/snarkOS/commit/adff259961d3ebd6c8ccf1460743623267c5161f

**Comment by ljedrz** [comment]
Closing, as the metric is in place; note: the duplicate blocks caught by the block cache currently overlaps with that metric, so it might appear as `0` or be very low until some block repropagation changes are in place.
