### ISSUE TITLE
[Bug] The `queues.outbound` metric seems to grow with time

### ISSUE THREAD

**Issue by ljedrz** [AleoHQ/snarkOS#869]
We should check if it gets decremented correctly.

**Comment by niklaslong** [comment]
I've observed this whilst building the crawler bootnodes as well.

**Comment by sadroeck** [comment]
This would probably be your culprit:
```rust
    /// returns true if disconnected, false if not connected anymore
    pub async fn disconnect(&self) -> bool {
-->        metrics::increment_gauge!(queues::OUTBOUND, 1.0);
        self.sender.send(PeerAction::Disconnect).await.is_ok()
    }
```

**Comment by sadroeck** [comment]
This would probably be your culprit:

```rust
impl PeerHandle {
...
    /// returns true if disconnected, false if not connected anymore
    pub async fn disconnect(&self) -> bool {
        metrics::increment_gauge!(queues::OUTBOUND, 1.0);
        self.sender.send(PeerAction::Disconnect).await.is_ok()
    }
}
```

Keeping track of queue population should be conditional on actually submitting a message onto the queue.
Additionally, we should drain the channel on `Drop` to ensure we reduce metric by the same amount.

**Comment by ljedrz** [comment]
Fixed by #920.

**Comment by ljedrz** [comment]
I've noticed that a long-running node might still retain some small value in this metric; needs further investigation to ensure that it's correct.

**Comment by ljedrz** [comment]
Fixed by https://github.com/AleoHQ/snarkOS/pull/999.
