### ISSUE TITLE
[Bug] RPC API returns error "missing block number value give"

### ISSUE THREAD

**Issue by e-nikolov** [AleoHQ/snarkOS#872]
## 🐛 Bug Report

I noticed that some of the aleo testnet bootnodes (159.89.152.247) return errors for some RPC calls (`decoderawtransaction`, `gettransactioninfo`).

## Steps to Reproduce

 For example block  `02a02e776311768341d8794ca5d34646c44378770dffa5b6053304e29e093cbc` has 2 transactions - `4e0cf21dfc3aa15fec8387e7b2a8f75b3ed8233d1957089d9f43152d6d7005ca` and `4c16b17ef620e483a94cff58165bcc4c91b60368bd63c4ccd8b923df38d73f9b`

Calling gettransactioninfo for `4c16b17ef620e483a94cff58165bcc4c91b60368bd63c4ccd8b923df38d73f9b` works fine, but calling it for `4e0cf21dfc3aa15fec8387e7b2a8f75b3ed8233d1957089d9f43152d6d7005ca` returns an error:

```
curl --request POST \
  --url http://159.89.152.247:3030/ \
  --header 'content-type: application/json' \
  --data '{"jsonrpc": "2.0","id":"documentation","method": "gettransactioninfo","params": ["4e0cf21dfc3aa15fec8387e7b2a8f75b3ed8233d1957089d9f43152d6d7005ca"]}'
```
```
{"jsonrpc":"2.0","error":{"code":0,"message":"missing block number value give"},"id":"documentation"}
```

I looked a bit into the snarkos code and `gettransactioninfo` internally calls the function behind `decoderawtransaction` and both of those RPC calls return the same error in some cases, so the issues are probably related.

From looking at the existing issues, https://github.com/AleoHQ/snarkOS/issues/863 and https://github.com/AleoHQ/snarkOS/issues/861 are possibly causing this.

## Your Environment

Whatever is running on bootnode 159.89.152.247

**Comment by ljedrz** [comment]
I'ts fixed in https://github.com/AleoHQ/snarkOS/pull/875/commits/e1139d2e2ffb95c32dfb7ea541e57891bd10620e (part of the upcoming https://github.com/AleoHQ/snarkOS/pull/875).

**Comment by e-nikolov** [comment]
Any idea why the full error message isn't being returned? Looking at the code the full message is
"missing block number value given block hash {}"
but I only receive
"missing block number value give"

**Comment by ljedrz** [comment]
Fixed by https://github.com/AleoHQ/snarkOS/pull/875.

**Comment by e-nikolov** [comment]
@ljedrz Do you have any idea when this fix will be deployed to the testnet nodes?

**Comment by ljedrz** [comment]
The node with this IP has already been updated, and the RPC now returns a nice response, the `block_number` is `null` now.

**Comment by e-nikolov** [comment]
Thanks a lot for your help! 

So are those transactions with "block_number": null  canonical or are they from a fork? They are still returned by the "getblock" RPC call, so it seems that they are canonical.

I am working on the aleo block explorer and I'm trying to figure out if those transactions should be shown in the explorer or not.

**Comment by ljedrz** [comment]
The `getblock` RPC only returns a block number when it's a canon block, as only they have the notion of a number within the chain. This means anything returning `null` is a side-chain block, at least to the node's knowledge (as it's still technically possible that it is on a fork and will later revert and recognize that block as canon, at which point it would return a block number).

**Comment by e-nikolov** [comment]
I meant that `getblock` shows block "02a02e776311768341d8794ca5d34646c44378770dffa5b6053304e29e093cbc" at height 283099 with having 2 transactions - "4e0cf21dfc3aa15fec8387e7b2a8f75b3ed8233d1957089d9f43152d6d7005ca" and "4c16b17ef620e483a94cff58165bcc4c91b60368bd63c4ccd8b923df38d73f9b". So the block itself seems to be canonical, but when I call `gettransactioninfo` with those 2 transactions I get inconsistent results: 

- "4c16b17ef620e483a94cff58165bcc4c91b60368bd63c4ccd8b923df38d73f9b" returns "block_number": 283099
- "4e0cf21dfc3aa15fec8387e7b2a8f75b3ed8233d1957089d9f43152d6d7005ca" returns "block_number": null

**Comment by ljedrz** [comment]
This is issue https://github.com/AleoHQ/snarkOS/issues/863, which is already fixed. I'm preparing an option for the users to run the storage validator that can fix this.
