### ISSUE TITLE
[Bug] RPC calls to decoderawtransaction sometimes incorrectly returns "Parse error"

### ISSUE THREAD

**Issue by e-nikolov** [AleoHQ/snarkOS#873]
## Steps to Reproduce

I tested this from several different machines on different networks performing the decoderawtransaction RPC call to the 159.89.152.247 bootnode using the raw transaction bytes from tx `4c16b17ef620e483a94cff58165bcc4c91b60368bd63c4ccd8b923df38d73f9b` from block `02a02e776311768341d8794ca5d34646c44378770dffa5b6053304e29e093cbc`

```
curl -X POST -H "Content-Type:application/json" -H "Access-Control-Allow-Origin:*" --data '{"jsonrpc":"2.0","id":1,"method":"decoderawtransaction","params":["011aa6a6aea0e96b76640ad8de6dd353f3c3750bca674a1ad7845f0c0c01028804af1cc0ef1aabe6914d4820968b97a2b7f8321d477ca1069ab54f2a6517b380af74ab22519ff9f87f6f895e35cf052c3d9d6263a497e3b75a37fe8704941500b2ba836a59e2feb34426ffcfa02135557efbba3a690872009f75c45f01ed320bc2bb22060927eddac34ef5c814da5e48b827ae8a8e082ec4e7a229ab76aa1c12b058934993bcd2666d45bce96ffb2b96c33a8b7548022d401f2b8fe28366bf0c84f313ea49db0e697c0c17e590a818a35d218bf710c984008d1c1d02834b124ef839763d51350b5bc4e950baa790a300f2a808b9e14c7d2aa1246489d3b21a7d594472bb18ed25a40c2028533eeb635764ab1681d63b7b13649cb8d889edbce6b022b061bb5c2894f21ff489083a26936f4edcb2a320f892ae3a8853ac7fcd21ca4b8ebb0dec6a69f1c002ee57d34100405ef3180386225884b7b7104fb86abcd36d4fdfdb599b9ce005fc84f097d213f7dc0c91b77acf0d9b2f190858cd2e1070cb9d714aa789271f8a0e9c04153329e7d252d3b4a9a718b3f7b190c372256fc3b586db404087c3bd76cc0054f2e4009e9ca970eeb8636b0d4a2e50c524b7c61020f2141e06eb96f39ffeb5412081cd56e48af67232dbaee743002df2e6b018bc74e0a7e6bed0cb376e73525e6be48dec756d271dbe6bc5128f36f8401c98996da550813eb1a7a8043b59310e747c8001ad124a3105b615a62c51e05e14427e2e97ff78e0dc3f122845fc729e465a941b2b458d05a2ead0a4bb763646ea992dc5bab7099b46e1f1fb07294e24b9a7cc06802e0ff7ffffffff0160cc62ec0b9d22bf13008acd830acbb0af856e572ac0bd828b7fea36bd4cd30268a315fe0650dedf8679232b4a4b0a62b3b96e2505974173c8a1d40714f65800143313c89b98eb34115977687d4fa6abcb83a6b42f528c98e0444abb3d46630028b647131db2e3b426e24c231de5555a08abaa20c40a666b18907d5e4936940108994a010d3477b8447153ed5432c36b46b3bc33956c2b6140be7288ebc99baf02831502ac73122b703d8a9766eb7c906b4475b543552c44c4dd62361cde441a09172499a769b96ee0654bad920a5358499359428d74c8fda89b7382e3a1144c0f1fd0840f49be2f1ef05dbfde929104d32a460936d32d1277d020daef8cd5870405535039b9c5fcfbbab32c301b0ef50f5178be366220d92bae102b756715b003be8a8fb05baab97a8d119d329f4c783cc3b6fae68d6749e82caae0f81112e4018752e74c3b34528c1f4bbaf3f247b252927c472fe360c917f2e70fc5247554091df83fa1c56f9e2228c9daf3c3b8d94aeecd7e5f36a728ffd4ecc3f20b39dc0e4e0008bfc0cbde6d6419115e7fcea24aa8dd7361bad5b1663d9cb0d34f9cafee127a036f1a529cee07667cd5fb4efcdb17fee27589ec967dcffb8724344b7809f74d04740a795d5776e0375a014d813fb41d54d2c61042e2b842b27a139f3d85b1a70f16356725dd00bec9eaba671dcbd754991e3626a2bb798611d06c6a85a4ea2912b95b1358079f49d41e5744b4ca546c56a28afd52af66925e352393693bca3b0dc40aa0a67f433229a96628586e7a71635693c92c15c20ad50a788e1ff8c9fb007c3551a5c0eaf213065d0016af4fef2e0724359481df993fabbb69e26e9d62048c11bbfd29584f4984dfd58b26ba756bca5c964904c0bd33487a2a67f3592d0c8700"]}' "http://159.89.152.247:3030"
```

Machine 1 - was my PC on my home network in Amsterdam. When I execute the above request, about 90% of the time I get back 
```
{"jsonrpc":"2.0","error":{"code":-32700,"message":"Parse error"},"id":null}
```

Machine 2 - was a colleague of mine's home PC also in Amsterdam. When he runs the above request, it works fine about half the time and returns the decoded transaction correctly, but the other 50% of the time it also returns a Parse error.

Machine 3 & 4 - cloud droplets on digital ocean - one based in amsterdam and one in the US. The request succeeds most of the time.

## Expected Behavior

I would expect that the request consistently succeeds or if it fails, it should not be with a Parse error.

The `decoderawtransaction` RPC endpoint is the only one that exhibits this behaviour. I suspect it has something to do with the large size of the input compared to the other endpoints. The Parse error suggests that the input isn't fully received before the endpoint starts parsing it. The issue is possibly only visible from me and my colleague's home networks because the issue is made worse by our home networks and the big distance to the bootnode, which I assume is located in the US, while we are in Europe.

**Comment by ljedrz** [comment]
Interesting; I am able reproduce it from time to time.

**Comment by ljedrz** [comment]
Update: the error is now `"Couldn't parse the RPC body"`, indicating a failure at a later stage than expected; will investigate further.

**Comment by ljedrz** [comment]
I tried to reproduce this today, but haven't been able to; @e-nikolov have you encountered this issue recently?

**Comment by e-nikolov** [comment]
I haven't been involved with this project in the past few months, so I have no idea if it's still happening.

**Comment by ljedrz** [comment]
Closing the issue, as I'm pretty sure it no longer occurs, and surely won't after the upcoming https://github.com/AleoHQ/snarkOS/pull/1602.
