### ISSUE TITLE
[Feature] Improved network graphing

### ISSUE THREAD

**Issue by niklaslong** [AleoHQ/snarkOS#911]
The current graph uses d3.js rendered with `svg`, which doesn't scale very well. Additionally, rendering the entire mesh is likely not the most useful for extracting actionable information. Rather, subsets of the data could be considered; these could be selected based on the centrality measurements and/or other factors yet tbd. 

Improving the performance of the graph may not be necessary if the data is curated.

**Comment by ljedrz** [comment]
Should we still keep this issue open?

**Comment by niklaslong** [comment]
I think we can close this for now, it's something to consider in future but it likely won't be integrated to snarkOS.
