### ISSUE TITLE
Erratic network test hangs

### ISSUE THREAD

**Issue by niklaslong** [AleoHQ/snarkOS#924]
The `network::sync` tests sometimes hang and cause failures on CI, I've just encountered this locally as well. Re-running the test usually results in a successful run.

**Comment by ljedrz** [comment]
meta: I'm wondering if we should label glitchy tests as `bug`s :thinking: - in this case it's unlikely that there's an actual bug in the runtime code, just some test issue.

**Comment by niklaslong** [comment]
Agreed, updated 👍

**Comment by niklaslong** [comment]
First tweaks: #943.

**Comment by ljedrz** [comment]
The issue seems to happen less often now, but it's still not fully resolved: https://app.circleci.com/pipelines/github/AleoHQ/snarkOS/3106/workflows/fbfd8300-5ee4-4836-a817-d47ffe9d52c8/jobs/11123.

**Comment by niklaslong** [comment]
This seems to have been resolved by #966.
