### ISSUE TITLE
Multi-Network Support in snarkOS

### ISSUE THREAD

**Issue by damons** [AleoHQ/snarkOS#928]
This epic is create functionality in snarkOS to support multiple concurrent networks running (potentially) under one snarkOS node.  Also, it could mean simply the ability to specify which network to run using command-line arguments, etc.  Please add all issues here to describe all dependencies for this epic.

**Comment by Protryon** [comment]
This is contributed to significantly by ongoing blocked storage refactors. See https://github.com/AleoHQ/snarkVM/issues/247
