### ISSUE TITLE
[Feature] Remove the sync layer from the bootnodes

### ISSUE THREAD

**Issue by niklaslong** [AleoHQ/snarkOS#960]
Bootnodes are currently burdened with a sync-layer and as such aren't currently fully dedicated to providing new peers in the network with peer lists. Removing the sync layer would increase bootnode availablilty and increase the utility of the bootnodes as network bootstrappers.

I believe the currently blocker is [aleo.network's reliance on a sync-enabled bootnode](https://github.com/AleoHQ/snarkOS/pull/878#discussion_r662619330). Could this be replaced by a regular node, since the functionality of each was essentially the same until the recent peering changes (starting with #878)?

**Comment by ljedrz** [comment]
@niklaslong I think this was completed with https://github.com/AleoHQ/snarkOS/pull/1134? Or is there anything left to do here?

**Comment by niklaslong** [comment]
Indeed, this can be closed.
