### ISSUE TITLE
[Feature] Refactor miners to be amenable to early, predictable termination

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#970]
We need to be able to start a new block *fast* -- let's refactor the miner management logic to work with this idea in mind.

**Comment by ljedrz** [comment]
Is this feature complete with https://github.com/AleoHQ/snarkVM/issues/351 and https://github.com/AleoHQ/snarkOS/pull/1051 merged?

**Comment by ljedrz** [comment]
Closing, as miner termination is already in place.
