### ISSUE TITLE
[Feature] Use Protobuf for DB (and network?) serialization

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#971]
Protobuf will probably add a few bytes overhead -- worth it for storage for forwards and backwards compatibility, but network is another call. I still think it's worth it.

**Comment by ljedrz** [comment]
Any reason for protobuf as opposed to cap'n'proto already used by the network? It's consistently faster in benchmarks and the schema is simpler.

**Comment by ljedrz** [comment]
`flatbuffers` is likely to be even faster, and it also has a schema-less variant, `flexbuffers`, which might be more practical for pure storage purposes.

**Comment by Protryon** [comment]
https://capnproto.org/news/2014-06-17-capnproto-flatbuffers-sbe.html
I'm not super strongly protobuf-only mode/have a great reason for protobuf, I've just used it a lot, and the difference in performance at the scale of a node makes runtime perf of serialization a non-issue. If others feel strongly in favor of others, I'm open.
I'm not a fan of any schema-less solutions though.

**Comment by ljedrz** [comment]
Closing, as it's no longer applicable to testnet2.
