### ISSUE TITLE
[Feature] Send fork points in block locator hashes

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#979]
To alleviate issues with syncing with forks around, we could see places we have forked > 64 blocks, and include those critical points as hashes in block locator hashes.

**Comment by ljedrz** [comment]
While this could be a good ad-hoc measure, we could improve the general situation if we just decided to send more locator hashes and improve the distances between the provided block hashes; I've updated https://github.com/AleoHQ/snarkOS/pull/809 which does that, and improves the index-picking algorithm.

**Comment by Protryon** [comment]
I ran into an issue and independently came to this conclusion again.
Consider the following cases:

1.

We have a fork that is 90 blocks long locally, 120 blocks back from local canon. In reality, the 90-block chain is canon, so we are marching down a fork. Even if we include every block we have in canon as block locator hashes, we will not include base of real canon + 90-64 block, the minimum block to continue advancing down canon, in any received sync blocks from peers due to peers sending back only 64 sync block hashes.

This has been observed.

2.

We have a fork that is 30 blocks long (notably less than 64 blocks), but its based 600 blocks behind local canon. In reality, the 30-block-long fork is actually canon.

The chances of a block locator hash entering a sufficient range, such that a peer sends back some hash we don't already have is relatively low. We halt syncing since our local canon is at tip of some fork, and we don't try to get any more blocks on the real canon chain,

This has been observed.

A proposed (and tested to work) fix is proposed:
1. Limit scope of block locator hashes to only include the range of the last 1024 blocks (equal to our max fork depth) -- we won't fork any further back then that regardless.
2. Limit proportional step of block locator hashes to 63 or less. This prevents us missing a range of block locator hashes, and is actually more strict than the 1024 limit generally.
3. Add the tip of all forks greater than 1 block deep (there are a lot of trivial 1 block forks we can ignore) to block locator hashes, exceeding the default capacity.

The combination of these items provides us 100% coverage of our 1024 block range and hedges against long forks with #3. There is a slight performance cost to calculating forks and such, but it's minimal in testing and is worth it.

**Comment by ljedrz** [comment]
This was closed by https://github.com/AleoHQ/snarkOS/pull/1026.
