### ISSUE TITLE
[Feature] Filter block broadcast based on received blocks

### ISSUE THREAD

**Issue by Protryon** [AleoHQ/snarkOS#980]
Right now, especially with large peer counts, we get bombarded with new blocks coming in.

Negotiating for the blocks adds to much latency to be practical from a product perspective. A proposal to mitigate this issue is to note which peers have so far sent us a block, then only redistribute to peers that have not sent it to us. The delay here can be natural, just internal IO/verify overhead, or some additional and small synthetic overhead, say 50 ms. I imagine zero synthetic overhead is the direction we would go.

On a similar note, while we can't do negotiations, we could take advantage of the time it takes to verify a block to do a best-case handshake for broadcasting blocks.
I.e.
1. Node A receives a block, begins verification
2. Node A concurrently notifies peers it has this block and is pending verification
3. Nodes B, C, D, E, connected to Node A respond to Node A that they have already received (not verified) that block, and do not need it
4. Node A finishes block validation concurrently to above handshake, begins broadcast
5. Node A has received confirmation from Nodes B, D, but not Node C or Node E at this exact moment, and so Node C and Node E will receive a block broadcast from Node A.

There are also potentials for "slow mode" enabled nodes on high-latency/low-bandwidth environments to enforce handshake is used.

**Comment by unordered-set** [comment]
Looks like a good application for a Bloom filter (just a hint)

**Comment by ljedrz** [comment]
Closing, as it's no longer applicable to testnet2, at least not at this point; we'll revisit it in case we're seeing issues related to block propagation.
